### ISSUE TITLE
Cluster goes haywire when node rejoins cluster

### ISSUE THREAD

**Issue by jonbonazza** [etcd-io/etcd#10180]
**Component:** Raft
**Commit:** 1cab49ef784afe16ee665d6e16f2fc5fa31d8974 (master HEAD at the time of this writing)
**Go version:** 1.11
**os/arch:** linux/amd64**
**config:**
```go
raft.Config{
		ID:              cg.id, // hashed <ip>:<port>
		ElectionTick:    10,
		HeartbeatTick:   1,
		Storage:         cg.storage, // raft.MemoryStore
		MaxSizePerMsg:   math.MaxUint16,
		MaxInflightMsgs: 256,
}
```

I'm using the etcd raft library in a project and during my testing of a cluster of 3 nodes, I've noticed that on initial bootstrap, everything works great, however, if I shut down one of the nodes and then restart it (timing between shutdown and restart doesn't seem to matter) to rejoin the existing cluster, the restarted node goes into a failed election loop, then after a few seconds, the other nodes start to get confused with their elections as well and the cluster essentially becomes fubar.

One thing I noticed is that the README mentions that when a node joins an existing cluster, it should be started with no peers and then the other nodes should use `ProposeConfChange` to make the cluster aware of the new node. I have the requirement that starting a node for the first time be no different than restarting a node that existed previously, but I _do_ have the luxury of knowing all of the nodes that are in the cluster before I start the raft node, so instead of following the README's advice, I simply pass all of the existing cluster peers to the restarted node. Perhaps this is an invalid approach? I don't see how this is different than a node starting up the first time and having a list of all the peers (which works for me), so I don't see why this approach wouldn't also work. 

Anyway, I have attached some logs that may help in pinpointing the issue. Let me know if you need more info. Thanks!

[node1.log](https://github.com/etcd-io/etcd/files/2475168/node1.log)
[node1_restart.log](https://github.com/etcd-io/etcd/files/2475169/node1_restart.log)
[node2.log](https://github.com/etcd-io/etcd/files/2475170/node2.log)
[node3.log](https://github.com/etcd-io/etcd/files/2475171/node3.log)

EDIT: Also, if you wish to see the exact code, it's here: https://github.com/huton-io/huton/blob/etcd-raft/pkg/swarm/raft.go

**Comment by jonbonazza** [comment]
So I decided to take a step back and strip out the gossip protocol for now and just try to get this working purely with Raft. In doing so, I noticed two things:

1. If I don't remove a node from the cluster before shutting it down, when the node attempts to rejoin, I get the following panic:
```
raft2018/10/15 01:11:49 INFO: cdefbd4522712b9e [term: 1] received a MsgHeartbeat message with higher term from cdefbe4522712d51 [term: 2]
raft2018/10/15 01:11:49 INFO: cdefbd4522712b9e became follower at term 2
raft2018/10/15 01:11:49 tocommit(4) is out of range [lastIndex(3)]. Was the raft log corrupted, truncated, or lost?
panic: tocommit(4) is out of range [lastIndex(3)]. Was the raft log corrupted, truncated, or lost?

goroutine 19 [running]:
log.(*Logger).Panicf(0xc0000ae410, 0xb4c17c, 0x5d, 0xc0002f2100, 0x2, 0x2)
        /usr/local/go/src/log/log.go:219 +0xdb
go.etcd.io/etcd/raft.(*DefaultLogger).Panicf(0x1067550, 0xb4c17c, 0x5d, 0xc0002f2100, 0x2, 0x2)
        /home/jbonazza/go/src/go.etcd.io/etcd/raft/logger.go:121 +0x60
go.etcd.io/etcd/raft.(*raftLog).commitTo(0xc00019e070, 0x4)
        /home/jbonazza/go/src/go.etcd.io/etcd/raft/log.go:201 +0x14d
go.etcd.io/etcd/raft.(*raft).handleHeartbeat(0xc0001b8000, 0x8, 0xcdefbd4522712b9e, 0xcdefbe4522712d51, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/jbonazza/go/src/go.etcd.io/etcd/raft/raft.go:1264 +0x54
go.etcd.io/etcd/raft.stepFollower(0xc0001b8000, 0x8, 0xcdefbd4522712b9e, 0xcdefbe4522712d51, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/jbonazza/go/src/go.etcd.io/etcd/raft/raft.go:1209 +0x450
go.etcd.io/etcd/raft.(*raft).Step(0xc0001b8000, 0x8, 0xcdefbd4522712b9e, 0xcdefbe4522712d51, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/jbonazza/go/src/go.etcd.io/etcd/raft/raft.go:920 +0x12d8
go.etcd.io/etcd/raft.(*node).run(0xc000158360, 0xc0001b8000)
        /home/jbonazza/go/src/go.etcd.io/etcd/raft/node.go:347 +0x10b3
created by go.etcd.io/etcd/raft.StartNode
        /home/jbonazza/go/src/go.etcd.io/etcd/raft/node.go:223 +0x423

```
So I beleive the solution to this seems to be to use an actually persistant log store and restore the raft state when the node restarts. 

2. If I explicitly remove the node from the cluster before shutting down, when I restart the node, I no longer get the panic, but I do notice that the other nodes don't receive the ConfChangeAdd that the rejoining node proposes. Apparently this ConfChange needs to be initiated from the _other_ nodes in the cluster (the ones that are still up). Is this correct? If so, it looks like I'll need to add back in the gossip protocol to further test things so that I know when a node joins or leaves the cluster.

**Comment by jonbonazza** [comment]
Anyone able to provide insight here?
