### ISSUE TITLE
&status.statusError{Code:14, Message:"transport is closing", Details:[]*any.Any(nil), XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}

### ISSUE THREAD

**Issue by liukaii** [etcd-io/etcd#10365]
here is my etcd-mash (Docker container):
```
mash@mash:~/GO/src/Honeypot-api/router$ kubectl exec -it etcd-mash -n kube-system /bin/sh
/ # etcd --version
etcd Version: 3.2.24
Git SHA: 420a45226
Go Version: go1.8.7
Go OS/Arch: linux/amd64
/ # 

```

here is main.go:
package main

```
import (
	"Honeypot-api/pkg/etcd"
	"fmt"
)

func main() {
	ecli, err := etcd.NewPodService()
	if err != nil {
		fmt.Println("get podservice client failed! err: ", err)
		return
	}
	//ecli.List("/registry/pods/default")
	ecli.Put("/honeypot/pot/lk", "developer1")
	ecli.Put("/honeypot/pot/qyq", "developer2")
	ecli.Get("/honeypot/pot/lk")
}
```
here is my etcd.go: 
```
package etcd

import (
	"time"
	"fmt"
	"context"
	"go.etcd.io/etcd/clientv3"
)

type PodService struct {
	client		*clientv3.Client
}

func NewPodService() (*PodService, error) {
	cli, err := clientv3.New(clientv3.Config{
		Endpoints:		[]string{"localhost:2379", "localhost:22379", "localhost:32379"},
		DialTimeout: 	5*time.Second,
	})
	if err != nil {
		fmt.Println("connect failed, err:", err)
		return nil, err
	}
	fmt.Println("connect success!")
	return &PodService{client:	cli}, nil
}

func (p *PodService) List(prefix string) {
	//ctx, cancel := context.WithTimeout(context.Background(), 1*time.Minute)
	//defer cancel()
	resp, err := p.client.Get(context.Background(), prefix, clientv3.WithPrefix(), clientv3.WithSort(clientv3.SortByKey, clientv3.SortDescend))
	if err != nil {
		fmt.Printf("List %s failed! err: %#v\n", prefix, err)
	}
	for _, ev := range resp.Kvs {
		fmt.Println("%s: %s\n", ev.Key, ev.Value)
	}
}

func (p * PodService) Put(key, value string) {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	_, err := p.client.Put(ctx, key, value)
	if err != nil {
		fmt.Printf("put key %s failed! err: %#v\n", key, err)
	}
}

func (p *PodService) Get(key string) string {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	resp, err := p.client.Get(ctx, key)
	if err != nil {
		fmt.Printf("get key %s failed! err: %#v\n", key, err)
	}
	return string(resp.Kvs[0].Value)
}
```
when I run main.go, the out put will be :
```
mash@mash:~/GO/src/Honeypot-api/router$ go run main.go 
connect success!
put key /honeypot/pot/lk failed! err: &status.statusError{Code:14, Message:"transport is closing", Details:[]*any.Any(nil), XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}
put key /honeypot/pot/qyq failed! err: &status.statusError{Code:14, Message:"transport is closing", Details:[]*any.Any(nil), XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}
get key /honeypot/pot/lk failed! err: context.deadlineExceededError{}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x8f9c01]

goroutine 1 [running]:
Honeypot-api/pkg/etcd.(*PodService).Get(0xc0000a6630, 0xa475f6, 0x10, 0x0, 0x0)
	/home/mash/GO/src/Honeypot-api/pkg/etcd/etcd.go:55 +0x1e1
main.main()
	/home/mash/GO/src/Honeypot-api/router/main.go:17 +0x12c
exit status 2

```
I don't know how to solve it. Please help me~

**Comment by hexfusion** [comment]
@liukaii what is the output of

`ETCDCTL_API=3 etcdctl --endpoints localhost:2379,localhost:22379,localhost:32379 endpoint status -w table`

I just tested this and it worked fine with a single node, can you show server logs when you get this output?

**Comment by liukaii** [comment]
the output of 
`ETCDCTL_API=3 etcdctl --endpoints localhost:2379,localhost:22379,localhost:32379 endpoint status -w table`
is:
```
/ # ETCDCTL_API=3 etcdctl --endpoints localhost:2379,localhost:22379,localhost:32379 endpoint status -w table
Failed to get the status of endpoint localhost:22379 (context deadline exceeded)
Failed to get the status of endpoint localhost:32379 (context deadline exceeded)
+----------------+------------------+---------+---------+-----------+-----------+------------+
|    ENDPOINT    |        ID        | VERSION | DB SIZE | IS LEADER | RAFT TERM | RAFT INDEX |
+----------------+------------------+---------+---------+-----------+-----------+------------+
| localhost:2379 | 8e9e05c52164694d |  3.2.24 |   25 kB |      true |         2 |          4 |
+----------------+------------------+---------+---------+-----------+-----------+------------+

```

now I think I know why it doesn't work! 
If I just run `go run main.go`, it doesn't work. Then I `go build` the main.go and put it into the container.
Finally I run the container with `docker run --net=container:616a1c2056e9 honeydata`.
the `616a1c2056e9` is the contaienr_id of etcd container.
Then it works!
Thank you!
