### ISSUE TITLE
Runtime error in TestLeasingNonOwnerPutError

### ISSUE THREAD

**Issue by mitake** [etcd-io/etcd#10405]
In the CI run of https://github.com/etcd-io/etcd/pull/10343, I found TestLeasingNonOwnerPutError is causing a runtime error like below:
```
=== RUN   TestLeasingNonOwnerPutError
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0xb0165d]
goroutine 21678 [running]:
go.etcd.io/etcd/vendor/google.golang.org/grpc.(*csAttempt).sendMsg(0xc000184580, 0x149a020, 0xc006014510, 0xc006014518, 0x5, 0x5, 0xc006014520, 0xa, 0xa, 0xc006014520, ...)
	/go/src/go.etcd.io/etcd/vendor/google.golang.org/grpc/stream.go:713 +0x14d
go.etcd.io/etcd/vendor/google.golang.org/grpc.(*clientStream).SendMsg.func2(0xc000184580, 0x48, 0x48)
	/go/src/go.etcd.io/etcd/vendor/google.golang.org/grpc/stream.go:637 +0x186
go.etcd.io/etcd/vendor/google.golang.org/grpc.(*clientStream).withRetry(0xc000a72240, 0xc0003c8d20, 0xc0062c9d40, 0xc006014518, 0x5)
	/go/src/go.etcd.io/etcd/vendor/google.golang.org/grpc/stream.go:530 +0x431
go.etcd.io/etcd/vendor/google.golang.org/grpc.(*clientStream).SendMsg(0xc000a72240, 0x149a020, 0xc006014510, 0x0, 0x0)
	/go/src/go.etcd.io/etcd/vendor/google.golang.org/grpc/stream.go:643 +0x80c
go.etcd.io/etcd/etcdserver/etcdserverpb.(*leaseLeaseKeepAliveClient).Send(0xc001a742c0, 0xc006014510, 0x0, 0x0)
	/go/src/go.etcd.io/etcd/etcdserver/etcdserverpb/rpc.pb.go:3749 +0x6b
go.etcd.io/etcd/clientv3.(*lessor).sendKeepAliveLoop(0xc00171c5a0, 0x17a54a0, 0xc001a742c0)
	/go/src/go.etcd.io/etcd/clientv3/lease.go:573 +0x2fb
created by go.etcd.io/etcd/clientv3.(*lessor).resetRecv
	/go/src/go.etcd.io/etcd/clientv3/lease.go:489 +0x34b
FAIL	go.etcd.io/etcd/clientv3/integration	146.009s
```

Full logs can be found here: https://travis-ci.com/etcd-io/etcd/jobs/169221994

**Comment by mitake** [comment]
This problem happens again in CI of https://github.com/etcd-io/etcd/pull/10343: https://travis-ci.com/etcd-io/etcd/jobs/172753792

**Comment by xiang90** [comment]
it seems like a bug in gRPC-go?
