### ISSUE TITLE
When node poweroff sometimes the etcd cannot restart

### ISSUE THREAD

**Issue by liucimin** [etcd-io/etcd#10518]
￼￼￼￼￼When my k8s master down for many days.Then i start it. 
The etcd can not start again.
the etcd 's  logs.
It seems like the  
**Mar 04 14:32:20 k8s-master etcd[17266]: panic: invalid page allocation: 0**
error。

```
Mar 04 14:32:20 k8s-master systemd[1]: Starting Etcd Server...
Mar 04 14:32:20 k8s-master etcd[17266]: etcd Version: 3.2.11
Mar 04 14:32:20 k8s-master etcd[17266]: Git SHA: 1e1dbb2
Mar 04 14:32:20 k8s-master etcd[17266]: Go Version: go1.8.5
Mar 04 14:32:20 k8s-master etcd[17266]: Go OS/Arch: linux/amd64
Mar 04 14:32:20 k8s-master etcd[17266]: setting maximum number of CPUs to 40, total number of available CPUs is 40
Mar 04 14:32:20 k8s-master etcd[17266]: the server is already initialized as member before, starting as etcd member...
Mar 04 14:32:20 k8s-master etcd[17266]: peerTLS: cert = /etc/kubernetes/ssl/etcd.pem, key = /etc/kubernetes/ssl/etcd-key.pem, ca = , trusted-ca = /etc/kubernetes/ssl/ca.pem, client-cert-auth = false
Mar 04 14:32:20 k8s-master etcd[17266]: listening for peers on https://10.27.244.161:2380
Mar 04 14:32:20 k8s-master etcd[17266]: The scheme of client url http://10.27.244.161:2381 is HTTP while peer key/cert files are presented. Ignored key/cert files.
Mar 04 14:32:20 k8s-master etcd[17266]: listening for client requests on 10.27.244.161:2381
Mar 04 14:32:20 k8s-master etcd[17266]: listening for client requests on 10.27.244.161:2379
Mar 04 14:32:20 k8s-master etcd[17266]: listening for client requests on 127.0.0.1:2379
Mar 04 14:32:20 k8s-master etcd[17266]: skipped unexpected non snapshot file default.etcd
Mar 04 14:32:20 k8s-master etcd[17266]: recovered store from snapshot at index 99101109
Mar 04 14:32:20 k8s-master etcd[17266]: panic: invalid page allocation: 0
Mar 04 14:32:20 k8s-master etcd[17266]: goroutine 1 [running]:
Mar 04 14:32:20 k8s-master etcd[17266]: github.com/coreos/etcd/cmd/vendor/github.com/coreos/bbolt.(*freelist).allocate(0xc42026d440, 0x1695ddc, 0x1df, 0xc420db2000)
Mar 04 14:32:20 k8s-master etcd[17266]: /home/gyuho/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/bbolt/freelist.go:85 +0x37b
Mar 04 14:32:20 k8s-master etcd[17266]: github.com/coreos/etcd/cmd/vendor/github.com/coreos/bbolt.(*DB).allocate(0xc42029a000, 0x1695ddc, 0x1df, 0xc42020fb10, 0x85f42b, 0xc42026d440)
Mar 04 14:32:20 k8s-master etcd[17266]: /home/gyuho/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/bbolt/db.go:906 +0xa6
Mar 04 14:32:20 k8s-master etcd[17266]: github.com/coreos/etcd/cmd/vendor/github.com/coreos/bbolt.(*Tx).allocate(0xc42027a000, 0x1df, 0x1695ddc, 0xc420daa9c0, 0xc420daa9d8)
Mar 04 14:32:20 k8s-master etcd[17266]: /home/gyuho/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/bbolt/tx.go:477 +0x4a
Mar 04 14:32:20 k8s-master etcd[17266]: github.com/coreos/etcd/cmd/vendor/github.com/coreos/bbolt.(*Tx).commitFreelist(0xc42027a000, 0x1695ddc, 0x7f119c960000)
Mar 04 14:32:20 k8s-master etcd[17266]: /home/gyuho/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/bbolt/tx.go:229 +0x8c
Mar 04 14:32:20 k8s-master etcd[17266]: github.com/coreos/etcd/cmd/vendor/github.com/coreos/bbolt.(*Tx).Commit(0xc42027a000, 0x26877d5a, 0x15001a0)
Mar 04 14:32:20 k8s-master etcd[17266]: /home/gyuho/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/bbolt/tx.go:175 +0x676
Mar 04 14:32:20 k8s-master etcd[17266]: github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/backend.(*batchTx).commit(0xc4200176b0, 0x0)
Mar 04 14:32:20 k8s-master etcd[17266]: /home/gyuho/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/backend/batch_tx.go:179 +0x82
Mar 04 14:32:20 k8s-master etcd[17266]: github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/backend.(*batchTxBuffered).unsafeCommit(0xc4200176b0, 0xfb1200)
Mar 04 14:32:20 k8s-master etcd[17266]: /home/gyuho/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/backend/batch_tx.go:251 +0x49
Mar 04 14:32:20 k8s-master etcd[17266]: github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/backend.(*batchTxBuffered).commit(0xc4200176b0, 0xfae200)
Mar 04 14:32:20 k8s-master etcd[17266]: /home/gyuho/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/backend/batch_tx.go:239 +0x80
Mar 04 14:32:20 k8s-master etcd[17266]: github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/backend.(*batchTxBuffered).Commit(0xc4200176b0)
Mar 04 14:32:20 k8s-master etcd[17266]: /home/gyuho/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/backend/batch_tx.go:226 +0x66
Mar 04 14:32:20 k8s-master etcd[17266]: github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/backend.(*backend).ForceCommit(0xc42022a300)
Mar 04 14:32:20 k8s-master etcd[17266]: /home/gyuho/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/backend/backend.go:165 +0x2f
Mar 04 14:32:20 k8s-master etcd[17266]: github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc.NewStore(0x14b77c0, 0xc42022a300, 0x14b8e20, 0x1520a10, 0x14a4c80, 0xc420d9d700, 0xc42020ff78)
Mar 04 14:32:20 k8s-master etcd[17266]: /home/gyuho/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/kvstore.go:127 +0x3ca
Mar 04 14:32:20 k8s-master etcd[17266]: github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc.newWatchableStore(0x14b77c0, 0xc42022a300, 0x14b8e20, 0x1520a10, 0x14a4c80, 0xc420d9d700, 0x1520a10)
Mar 04 14:32:20 k8s-master etcd[17266]: /home/gyuho/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/watchable_store.go:75 +0x81
Mar 04 14:32:20 k8s-master etcd[17266]: github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc.New(0x14b77c0, 0xc42022a300, 0x14b8e20, 0x1520a10, 0x14a4c80, 0xc420d9d700, 0x1, 0xc420210028)
Mar 04 14:32:20 k8s-master etcd[17266]: /home/gyuho/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/watchable_store.go:70 +0x5d
Mar 04 14:32:20 k8s-master etcd[17266]: github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver.recoverSnapshotBackend(0xc420274300, 0x14b77c0, 0xc42022a300, 0xc420c1a000, 0xa6c49, 0xa8000, 0xc420189d28, 0x1, 0x1, 0x0, ...)
Mar 04 14:32:20 k8s-master etcd[17266]: /home/gyuho/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/backend.go:74 +0xe0
Mar 04 14:32:20 k8s-master etcd[17266]: github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver.NewServer(0xc420274300, 0x0, 0x0, 0x0)
Mar 04 14:32:20 k8s-master etcd[17266]: /home/gyuho/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/server.go:378 +0x2d96
Mar 04 14:32:20 k8s-master etcd[17266]: github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/embed.StartEtcd(0xc42024a380, 0xc42027c000, 0x0, 0x0)
Mar 04 14:32:20 k8s-master etcd[17266]: /home/gyuho/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/embed/etcd.go:151 +0x784
Mar 04 14:32:20 k8s-master etcd[17266]: github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain.startEtcd(0xc42024a380, 0x6, 0xf6f4d3, 0x6, 0x1)
Mar 04 14:32:20 k8s-master etcd[17266]: /home/gyuho/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain/etcd.go:186 +0x58
Mar 04 14:32:20 k8s-master etcd[17266]: github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain.startEtcdOrProxyV2()
Mar 04 14:32:20 k8s-master etcd[17266]: /home/gyuho/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain/etcd.go:103 +0x15ba
Mar 04 14:32:20 k8s-master etcd[17266]: github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain.Main()
Mar 04 14:32:20 k8s-master etcd[17266]: /home/gyuho/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain/main.go:39 +0x61
Mar 04 14:32:20 k8s-master etcd[17266]: main.main()
Mar 04 14:32:20 k8s-master etcd[17266]: /home/gyuho/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/etcd/main.go:28 +0x20
Mar 04 14:32:20 k8s-master systemd[1]: etcd.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 04 14:32:20 k8s-master systemd[1]: Failed to start Etcd Server.
Mar 04 14:32:20 k8s-master systemd[1]: Unit etcd.service entered failed state.
Mar 04 14:32:20 k8s-master systemd[1]: etcd.service failed.

```

When i try to restroe it.It also show me the same problem
```
[root@k8s-master ~]# ETCDCTL_API=3 etcdctl snapshot restore /opt/etcd/member/snap/db --skip-hash-check=true
panic: invalid page allocation: 0

goroutine 1 [running]:
github.com/coreos/etcd/cmd/vendor/github.com/coreos/bbolt.(*freelist).allocate(0xc42024c810, 0x1695ddc, 0x1df, 0xc420a56000)
	/home/gyuho/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/bbolt/freelist.go:85 +0x37b
github.com/coreos/etcd/cmd/vendor/github.com/coreos/bbolt.(*DB).allocate(0xc420258000, 0x1695ddc, 0x1df, 0xc42012b3d0, 0xaf077b, 0xc42024c810)
	/home/gyuho/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/bbolt/db.go:906 +0xa6
github.com/coreos/etcd/cmd/vendor/github.com/coreos/bbolt.(*Tx).allocate(0xc4201b41c0, 0x1df, 0x1695ddc, 0xc42001bbc0, 0xc42001bbd8)
	/home/gyuho/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/bbolt/tx.go:477 +0x4a
github.com/coreos/etcd/cmd/vendor/github.com/coreos/bbolt.(*Tx).commitFreelist(0xc4201b41c0, 0x1695ddc, 0x7f3d701cb000)
	/home/gyuho/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/bbolt/tx.go:229 +0x8c
github.com/coreos/etcd/cmd/vendor/github.com/coreos/bbolt.(*Tx).Commit(0xc4201b41c0, 0x359183bd, 0x128a440)
	/home/gyuho/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/bbolt/tx.go:175 +0x676
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/backend.(*batchTx).commit(0xc420019170, 0x0)
	/home/gyuho/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/backend/batch_tx.go:179 +0x82
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/backend.(*batchTxBuffered).unsafeCommit(0xc420019170, 0xdfc500)
	/home/gyuho/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/backend/batch_tx.go:251 +0x49
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/backend.(*batchTxBuffered).commit(0xc420019170, 0xdf9a00)
	/home/gyuho/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/backend/batch_tx.go:239 +0x80
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/backend.(*batchTxBuffered).Commit(0xc420019170)
	/home/gyuho/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/backend/batch_tx.go:226 +0x66
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/backend.(*backend).ForceCommit(0xc42020ea80)
	/home/gyuho/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/backend/backend.go:165 +0x2f
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/lease.(*lessor).initAndRecover(0xc42020ec00)
	/home/gyuho/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/lease/lessor.go:542 +0x417
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/lease.newLessor(0x1247f80, 0xc42020ea80, 0x7fffffffffffffff, 0x280000000)
	/home/gyuho/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/lease/lessor.go:166 +0x1c5
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/lease.NewLessor(0x1247f80, 0xc42020ea80, 0x7fffffffffffffff, 0xc42020ea80, 0x0)
	/home/gyuho/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/lease/lessor.go:152 +0x3f
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdctl/ctlv3/command.makeDB(0xc420225000, 0x18, 0x7ffe735e1803, 0x18, 0x1)
	/home/gyuho/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdctl/ctlv3/command/snapshot_command.go:377 +0x3c1
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdctl/ctlv3/command.snapshotRestoreCommandFunc(0xc42023b800, 0xc420224d40, 0x1, 0x2)
	/home/gyuho/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdctl/ctlv3/command/snapshot_command.go:196 +0x342
github.com/coreos/etcd/cmd/vendor/github.com/spf13/cobra.(*Command).execute(0xc42023b800, 0xc420224c20, 0x2, 0x2, 0xc42023b800, 0xc420224c20)
	/home/gyuho/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/spf13/cobra/command.go:572 +0x203
github.com/coreos/etcd/cmd/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1280a80, 0xdc7910, 0xb, 0xc42021fed8)
	/home/gyuho/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/spf13/cobra/command.go:662 +0x394
github.com/coreos/etcd/cmd/vendor/github.com/spf13/cobra.(*Command).Execute(0x1280a80, 0x0, 0x0)
	/home/gyuho/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/spf13/cobra/command.go:618 +0x2b
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdctl/ctlv3.Start()
	/home/gyuho/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdctl/ctlv3/ctl_nocov.go:25 +0x8e
main.main()
	/home/gyuho/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/etcdctl/main.go:40 +0x1d0
```

**Comment by WIZARD-CXY** [comment]
@liucimin which version of etcd are you using? have you tried to use the lastest one?

**Comment by Pingan2017** [comment]
same issue in my cluster
version 3.1.12

**Comment by pjhdld** [comment]
@Pingan2017  @WIZARD-CXY @xiang90 
I also encountered this problem.
Ways to circumvent:
First, stop etcd;
Second, delete or rename the data directory of etcd;
Third, start etcd.
This etcd will be restored.
But I don't quite understand the principle that it has been restarting or failing. Can you tell me something?

**Comment by WIZARD-CXY** [comment]
when the node poweroff suddenly, the datafile of etcd maybe corrupted. If you delete the data of the failing node, the peer will transfer the data to the new one, This time the whole data is recreated, so etcd will be restored.

**Comment by WIZARD-CXY** [comment]
@pjhdld

**Comment by pjhdld** [comment]
> when the node poweroff suddenly, the datafile of etcd maybe corrupted. If you delete the data of the failing node, the peer will transfer the data to the new one, This time the whole data is recreated, so etcd will be restored.
@WIZARD-CXY  I know, what I want to ask is what is the cause of this ’panic‘.

**Comment by jingyih** [comment]
Might be a bug in underlying bbolt? Is there a way to reproduce this?

**Comment by pjhdld** [comment]
> Might be a bug in underlying bbolt? Is there a way to reproduce this?

@jingyih 
I am here to expand the server, from 4 cores to 8 cores. Then there is this problem after power failure restart.
