### ISSUE TITLE
When compaction/defrag,  Error: panic: cannot free page 0 or 1: 0, The Etcd version is 3.1.9

### ISSUE THREAD

**Issue by veesonsan** [etcd-io/etcd#10520]
**When I tried to defrag the ETCD, the following error occurred:**

`2019-03-01T12:47:30.138770+11:00 E | etcdmain: forgot to set Type=notify in systemd service file?
2019-03-01T12:47:31.408479+11:00 I | etcdserver/api/v3rpc: API: DELETE . Key: /cse/etcdsync/cse-sr/lock/global, RangeEnd: , PrevKv: false
2019-03-01T12:47:31.935690+11:00 I | etcdserver/api/v3rpc: API: DELETE . Key: /cse/etcdsync/cse-sr/lock/global, RangeEnd: , PrevKv: false
2019-03-02T02:00:06.055520+11:00 I | mvcc: store.index: compact 1348
2019-03-02T02:00:07.048784+11:00 I | mvcc: finished scheduled compaction at 1348 (took 3.770854ms)
2019-03-02T02:00:07.049005+11:00 W | etcdserver: apply entries took too long [631.399114ms for 1 entries]
2019-03-02T02:00:07.049056+11:00 W | etcdserver: avoid queries with large range/delete range!
2019-03-02T02:00:07.108783+11:00 N | etcdserver/api/v3rpc: starting to defragment the storage backend...
2019-03-02T02:00:07.127276+11:00 N | etcdserver/api/v3rpc: finished defragmenting the storage backend
2019-03-02T02:00:13.934012+11:00 N | etcdserver/api/v3rpc: starting to defragment the storage backend...
2019-03-02T02:00:13.951599+11:00 N | etcdserver/api/v3rpc: finished defragmenting the storage backend
2019-03-03T02:00:10.159958+11:00 N | etcdserver/api/v3rpc: starting to defragment the storage backend...
2019-03-03T02:00:10.259268+11:00 N | etcdserver/api/v3rpc: finished defragmenting the storage backend
2019-03-04T02:00:03.946184+11:00 N | etcdserver/api/v3rpc: starting to defragment the storage backend...
panic: cannot free page 0 or 1: 0

goroutine 1950475 [running]:
github.com/coreos/etcd/cmd/vendor/github.com/coreos/bbolt.(*freelist).free(0xc420859e00, 0x3, 0x7f5378190000)
        /opt/gPaaS_UK/Code/etcd/third_party/open_source/etcd/etcd-3.1.9/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/bbolt/freelist.go:123 +0x4fa
github.com/coreos/etcd/cmd/vendor/github.com/coreos/bbolt.(*Tx).Commit(0xc420d2aee0, 0xc8699e2aabbc, 0x137ecc0)
        /opt/gPaaS_UK/Code/etcd/third_party/open_source/etcd/etcd-3.1.9/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/bbolt/tx.go:171 +0x1d6
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/backend.(*batchTx).commit(0xc4203112a0, 0xe69b01)
        /opt/gPaaS_UK/Code/etcd/third_party/open_source/etcd/etcd-3.1.9/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/backend/batch_tx.go:183 +0x9d
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/backend.(*backend).defrag(0xc4202ce660, 0x0, 0x0)
        /opt/gPaaS_UK/Code/etcd/third_party/open_source/etcd/etcd-3.1.9/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/backend/backend.go:266 +0xe6
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/backend.(*backend).Defrag(0xc4202ce660, 0xedf840, 0xc4202ce660)
        /opt/gPaaS_UK/Code/etcd/third_party/open_source/etcd/etcd-3.1.9/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/backend/backend.go:244 +0x2b
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc.(*maintenanceServer).Defragment(0xc420274000, 0x7f5377ff6138, 0xc420c53650, 0x13a0ec0, 0x0, 0xc42112fa78, 0x3)
        /opt/gPaaS_UK/Code/etcd/third_party/open_source/etcd/etcd-3.1.9/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc/maintenance.go:68 +0x82
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc.(*authMaintenanceServer).Defragment(0xc420238160, 0x7f5377ff6138, 0xc420c53650, 0x13a0ec0, 0xc420238160, 0xe43ae2, 0xa)
        /opt/gPaaS_UK/Code/etcd/third_party/open_source/etcd/etcd-3.1.9/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc/maintenance.go:168 +0x9e`

**Then I restart Etcd,following error occurred:**

`2019-03-04T02:00:17.878846+11:00 I | embed: listening for metrics requests on http://localhost:2378
2019-03-04T02:00:17.880497+11:00 I | embed: listening for peers on https://n1.manager.node.cluster.local:2380
2019-03-04T02:00:17.880532+11:00 I | embed: pprof is enabled under /debug/pprof
2019-03-04T02:00:17.880616+11:00 I | embed: listening for client requests on 127.0.0.1:30101
2019-03-04T02:00:17.880733+11:00 I | embed: listening for client requests on n1.manager.node.cluster.local:30101
panic: invalid freelist page: 0, page type is unknown<00>

goroutine 94 [running]:
github.com/coreos/etcd/cmd/vendor/github.com/coreos/bbolt.(*freelist).read(0xc420390120, 0x7f6fb3772000)
        /opt/gPaaS_UK/Code/etcd/third_party/open_source/etcd/etcd-3.1.9/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/bbolt/freelist.go:237 +0x2fd
github.com/coreos/etcd/cmd/vendor/github.com/coreos/bbolt.(*DB).loadFreelist.func1()
        /opt/gPaaS_UK/Code/etcd/third_party/open_source/etcd/etcd-3.1.9/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/bbolt/db.go:290 +0x12b
sync.(*Once).Do(0xc420392150, 0xc42007edf0)
        /opt/tools/go/src/sync/once.go:44 +0xbe
github.com/coreos/etcd/cmd/vendor/github.com/coreos/bbolt.(*DB).loadFreelist(0xc420392000)
        /opt/gPaaS_UK/Code/etcd/third_party/open_source/etcd/etcd-3.1.9/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/bbolt/db.go:283 +0x4e
github.com/coreos/etcd/cmd/vendor/github.com/coreos/bbolt.Open(0xc420037200, 0x3e, 0x180, 0x133b540, 0x0, 0x0, 0x0)
        /opt/gPaaS_UK/Code/etcd/third_party/open_source/etcd/etcd-3.1.9/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/bbolt/db.go:260 +0x38b
`

**Comment by hexfusion** [comment]
> panic: cannot free page 0 or 1: 0

>goroutine 1950475 [running]:
github.com/coreos/etcd/cmd/vendor/github.com/coreos/bbolt.(*freelist).free(0xc420859e00, 0x3, 0x7f5378190000)

@veesonsan please try to update to etcd 3.1.11+ we backported some important bbolt fixes that I imagine will resolve this issue. https://github.com/etcd-io/etcd/blob/master/CHANGELOG-3.1.md#v3111-2017-11-28
