### ISSUE TITLE
Etcd deadlock when starting server with a corrupt prefix dir

### ISSUE THREAD

**Issue by purpleidea** [etcd-io/etcd#10600]
Using v.3.3.12...
Using the `embed` package...
If the dir prefix that is used to store the `member/` dir was previously used by a different hostname or doesn't match what is exactly expected by `server, err = embed.StartEtcd(cfg)`, then a `.Stop` and `.Close` will cause a deadlock.

After some time waiting for the `server.Server.ReadyNotify()` or `server.Server.StopNotify()` signals, we decide to timeout (60s) and then run:

```
server.Server.Stop() // doesn't block
server.Close()       // this deadlocks here
```

The relevant logs after kill -9 include:

```
goroutine 134 [chan receive, 9 minutes]:
github.com/purpleidea/mgmt/vendor/github.com/coreos/etcd/embed.(*Etcd).Close(0xc4200fc480)
	/home/james/code/gopath/src/github.com/purpleidea/mgmt/vendor/github.com/coreos/etcd/embed/etcd.go:229 +0x19c

goroutine 161 [chan receive, 10 minutes]:
github.com/soheilhy/cmux.muxListener.Accept(...)
	/home/james/code/gopath/src/github.com/soheilhy/cmux/cmux.go:229
github.com/soheilhy/cmux.(*muxListener).Accept(0xc4201e8de0, 0x1a85840, 0xc4202a7900, 0x1bd5c20, 0xc4201e8de0)
	<autogenerated>:1 +0x5b
github.com/purpleidea/mgmt/vendor/google.golang.org/grpc.(*Server).Serve(0xc4202a7900, 0x1bd5c20, 0xc4201e8de0, 0x0, 0x0)
	/home/james/code/gopath/src/github.com/purpleidea/mgmt/vendor/google.golang.org/grpc/server.go:475 +0x179
created by github.com/purpleidea/mgmt/vendor/github.com/coreos/etcd/embed.(*Etcd).servePeers
	/home/james/code/gopath/src/github.com/purpleidea/mgmt/vendor/github.com/coreos/etcd/embed/etcd.go:366 +0x255

goroutine 178 [chan receive, 10 minutes]:
github.com/soheilhy/cmux.muxListener.Accept(...)
	/home/james/code/gopath/src/github.com/soheilhy/cmux/cmux.go:229
github.com/soheilhy/cmux.(*muxListener).Accept(0xc4201e8e80, 0xc4200d00f0, 0x1715000, 0x27f95c0, 0x19d7be0)
	<autogenerated>:1 +0x5b
net/http.(*Server).Serve(0xc4200cc820, 0x1bd5c20, 0xc4201e8e80, 0x0, 0x0)
	/usr/lib/golang/src/net/http/server.go:2773 +0x1a5
created by github.com/purpleidea/mgmt/vendor/github.com/coreos/etcd/embed.(*Etcd).servePeers
	/home/james/code/gopath/src/github.com/purpleidea/mgmt/vendor/github.com/coreos/etcd/embed/etcd.go:372 +0x445

goroutine 179 [IO wait, 10 minutes]:
internal/poll.runtime_pollWait(0x7f348a837e30, 0x72, 0x0)
	/usr/lib/golang/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc4203daf18, 0x72, 0xc42011cb00, 0x0, 0x0)
	/usr/lib/golang/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc4203daf18, 0xffffffffffffff00, 0x0, 0x0)
	/usr/lib/golang/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Accept(0xc4203daf00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/internal/poll/fd_unix.go:372 +0x1a8
net.(*netFD).accept(0xc4203daf00, 0x457f9b, 0x0, 0x0)
	/usr/lib/golang/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc4203660f8, 0xc420338340, 0xc420426900, 0xc42011cb00)
	/usr/lib/golang/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).Accept(0xc4203660f8, 0x0, 0x0, 0xc42049a700, 0x4462c9)
	/usr/lib/golang/src/net/tcpsock.go:259 +0x49
github.com/purpleidea/mgmt/vendor/github.com/coreos/etcd/pkg/transport.(*rwTimeoutListener).Accept(0xc420362260, 0x1a85b78, 0xc4201edcc0, 0xc420338340, 0xc42049a798)
	/home/james/code/gopath/src/github.com/purpleidea/mgmt/vendor/github.com/coreos/etcd/pkg/transport/timeout_listener.go:48 +0x37
github.com/soheilhy/cmux.(*cMux).Serve(0xc4201edcc0, 0x0, 0x0)
	/home/james/code/gopath/src/github.com/soheilhy/cmux/cmux.go:162 +0x88
github.com/purpleidea/mgmt/vendor/github.com/coreos/etcd/embed.(*Etcd).servePeers.func1(0x476c31, 0xc420464410)
	/home/james/code/gopath/src/github.com/purpleidea/mgmt/vendor/github.com/coreos/etcd/embed/etcd.go:373 +0x2f
github.com/purpleidea/mgmt/vendor/github.com/coreos/etcd/embed.(*Etcd).servePeers.func3(0xc4200fc480, 0xc420362160)
	/home/james/code/gopath/src/github.com/purpleidea/mgmt/vendor/github.com/coreos/etcd/embed/etcd.go:386 +0x2b
created by github.com/purpleidea/mgmt/vendor/github.com/coreos/etcd/embed.(*Etcd).servePeers
	/home/james/code/gopath/src/github.com/purpleidea/mgmt/vendor/github.com/coreos/etcd/embed/etcd.go:385 +0x633

goroutine 182 [chan receive, 10 minutes]:
github.com/purpleidea/mgmt/vendor/github.com/coreos/etcd/embed.(*serveCtx).serve(0xc420463f20, 0xc420434f00, 0xc4200fc658, 0x1bc1e00, 0xc4201e9660, 0xc4202bd5d0, 0xc4202bd5c0, 0x2, 0x2, 0x0, ...)
	/home/james/code/gopath/src/github.com/purpleidea/mgmt/vendor/github.com/coreos/etcd/embed/serve.go:83 +0xff
github.com/purpleidea/mgmt/vendor/github.com/coreos/etcd/embed.(*Etcd).serveClients.func1(0xc4200fc480, 0xc4202bd3b0, 0xc4201e96a0, 0xc420463f20)
	/home/james/code/gopath/src/github.com/purpleidea/mgmt/vendor/github.com/coreos/etcd/embed/etcd.go:519 +0xbb
created by github.com/purpleidea/mgmt/vendor/github.com/coreos/etcd/embed.(*Etcd).serveClients
	/home/james/code/gopath/src/github.com/purpleidea/mgmt/vendor/github.com/coreos/etcd/embed/etcd.go:518 +0x4e2
```

Ideally we'd receive an error somewhere instead of a deadlock.

Thanks!

**Comment by purpleidea** [comment]
hi bot! please stop pinging here
