### ISSUE TITLE
Crash on standalone node - fails to startup

### ISSUE THREAD

**Issue by howels** [etcd-io/etcd#10706]
Version: 3.3.11, 3.3.13 and prior versions too. Using the official image from quay.io

Reproducible very regularly after the pod is shutdown and re-started, due to a reboot of the node.

Storage for data is attached from a GlusterFS PVC, the PV shows no errors that we can see.

We have enabled as much logging as possible but it's hard to see what the issue is from the log data:

```
      - command:
        - etcd
        - --name=test-db
        - --listen-client-urls=https://0.0.0.0:2379
        - --advertise-client-urls=https://etcd.test.svc.cluster.local:2379
        - --data-dir=/var/etcd/data
        - --client-cert-auth
        - --trusted-ca-file=/secure/test-cert/ca.crt
        - --cert-file=/secure/server-certs/tls.crt
        - --key-file=/secure/server-certs/tls.key
        - --debug=true
        - --experimental-initial-corrupt-check=true
        - --log-output=stdout
```

Log output:
```
2019-05-03 17:38:55.423352 [pkg_logger.go:134] I | etcdmain: etcd Version: 3.3.13
2019-05-03 17:38:55.423501 [pkg_logger.go:134] I | etcdmain: Git SHA: 98d3084
2019-05-03 17:38:55.423530 [pkg_logger.go:134] I | etcdmain: Go Version: go1.10.8
2019-05-03 17:38:55.423545 [pkg_logger.go:134] I | etcdmain: Go OS/Arch: linux/amd64
2019-05-03 17:38:55.423558 [pkg_logger.go:134] I | etcdmain: setting maximum number of CPUs to 8, total number of available CPUs is 8
2019-05-03 17:38:55.427974 [pkg_logger.go:124] N | etcdmain: the server is already initialized as member before, starting as etcd member...
2019-05-03 17:38:55.428903 [etcd.go:348] I | embed: listening for peers on http://localhost:2380
2019-05-03 17:38:55.429117 [etcd.go:454] I | embed: listening for client requests on 0.0.0.0:2379
2019-05-03 17:38:55.476851 [pkg_logger.go:134] I | etcdserver: name = test-db
2019-05-03 17:38:55.476900 [pkg_logger.go:134] I | etcdserver: data dir = /var/etcd/data
2019-05-03 17:38:55.476916 [pkg_logger.go:134] I | etcdserver: member dir = /var/etcd/data/member
2019-05-03 17:38:55.476932 [pkg_logger.go:134] I | etcdserver: heartbeat = 100ms
2019-05-03 17:38:55.476944 [pkg_logger.go:134] I | etcdserver: election = 1000ms
2019-05-03 17:38:55.476955 [pkg_logger.go:134] I | etcdserver: snapshot count = 100000
2019-05-03 17:38:55.476979 [pkg_logger.go:134] I | etcdserver: advertise client URLs = https://etcd.test.svc.cluster.local:2379
2019-05-03 17:38:55.494469 [pkg_logger.go:134] I | etcdserver: restarting member 8e9e05c52164694d in cluster cdf818194e3a8c32 at commit index 4
unexpected fault address 0x7f0085e54000
fatal error: fault
2019-05-03 17:38:55.494563 [pkg_logger.go:134] I | raft: 8e9e05c52164694d became follower at term 2
2019-05-03 17:38:55.494606 [pkg_logger.go:134] I | raft: newRaft 8e9e05c52164694d [peers: [], term: 2, commit: 4, applied: 0, lastindex: 4, lastterm: 2]
[signal SIGBUS: bus error code=0x2 addr=0x7f0085e54000 pc=0x87d3ed]

goroutine 1 [running]:
runtime.throw(0xe1b44a, 0x5)
        /usr/local/go/src/runtime/panic.go:616 +0x81 fp=0xc420260ed0 sp=0xc420260eb0 pc=0x42ad71
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:385 +0x273 fp=0xc420260f20 sp=0xc420260ed0 pc=0x440543
github.com/coreos/etcd/cmd/vendor/github.com/coreos/bbolt.(*DB).page(...)
        /tmp/etcd-release-3.3.13/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/bbolt/db.go:859
github.com/coreos/etcd/cmd/vendor/github.com/coreos/bbolt.(*Tx).page(...)
        /tmp/etcd-release-3.3.13/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/bbolt/tx.go:599
github.com/coreos/etcd/cmd/vendor/github.com/coreos/bbolt.(*Bucket).pageNode(0xc420158398, 0x2, 0x18, 0xc4201ed480)
        /tmp/etcd-release-3.3.13/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/bbolt/bucket.go:724 +0xad fp=0xc420260f98 sp=0xc420260f20 pc=0x87d3ed
github.com/coreos/etcd/cmd/vendor/github.com/coreos/bbolt.(*Cursor).search(0xc420261138, 0x13d22d0, 0x7, 0x7, 0x2)
        /tmp/etcd-release-3.3.13/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/bbolt/cursor.go:254 +0x50 fp=0xc420261050 sp=0xc420260f98 pc=0x87e880
github.com/coreos/etcd/cmd/vendor/github.com/coreos/bbolt.(*Cursor).seek(0xc420261138, 0x13d22d0, 0x7, 0x7, 0x0, 0x0, 0x4, 0xc4201fa540, 0x1, 0x1, ...)
        /tmp/etcd-release-3.3.13/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/bbolt/cursor.go:159 +0xa5 fp=0xc4202610a0 sp=0xc420261050 pc=0x87e185
github.com/coreos/etcd/cmd/vendor/github.com/coreos/bbolt.(*Bucket).CreateBucket(0xc420158398, 0x13d22d0, 0x7, 0x7, 0x0, 0x0, 0x0)
        /tmp/etcd-release-3.3.13/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/bbolt/bucket.go:165 +0xfa fp=0xc4202611a0 sp=0xc4202610a0 pc=0x87a75a
github.com/coreos/etcd/cmd/vendor/github.com/coreos/bbolt.(*Tx).CreateBucket(0xc420158380, 0x13d22d0, 0x7, 0x7, 0x2, 0x8e9e05c52164694d, 0x4)
        /tmp/etcd-release-3.3.13/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/bbolt/tx.go:108 +0x4f fp=0xc4202611e8 sp=0xc4202611a0 pc=0x8896bf
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/backend.(*batchTx).UnsafeCreateBucket(0xc4201b52c0, 0x13d22d0, 0x7, 0x7)
        /tmp/etcd-release-3.3.13/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/backend/batch_tx.go:48 +0x6b fp=0xc420261280 sp=0xc4202611e8 pc=0x8db0fb
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/membership.mustCreateBackendBuckets(0xee8980, 0xc42028c4d0)
        /tmp/etcd-release-3.3.13/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/membership/store.go:166 +0xb7 fp=0xc4202612c0 sp=0xc420261280 pc=0x954467
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/membership.(*RaftCluster).SetBackend(0xc4200c5740, 0xee8980, 0xc42028c4d0)
        /tmp/etcd-release-3.3.13/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/membership/cluster.go:203 +0x54 fp=0xc4202612e0 sp=0xc4202612c0 pc=0x94f234
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver.NewServer(0x7ffdc0f5e07b, 0x10, 0x0, 0x0, 0x0, 0x0, 0xc420270a00, 0x1, 0x1, 0xc420270700, ...)
        /tmp/etcd-release-3.3.13/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/server.go:396 +0x921 fp=0xc420261ab0 sp=0xc4202612e0 pc=0xa48e11
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/embed.StartEtcd(0xc42026a480, 0xc42026ad80, 0x0, 0x0)
        /tmp/etcd-release-3.3.13/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/embed/etcd.go:179 +0x811 fp=0xc4202626e8 sp=0xc420261ab0 pc=0xb88e11
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain.startEtcd(0xc42026a480, 0xe1c531, 0x6, 0xc420262d01, 0x2)
        /tmp/etcd-release-3.3.13/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain/etcd.go:181 +0x40 fp=0xc4202627b0 sp=0xc4202626e8 pc=0xbf9670
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain.startEtcdOrProxyV2()
        /tmp/etcd-release-3.3.13/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain/etcd.go:102 +0x1369 fp=0xc420263f08 sp=0xc4202627b0 pc=0xbf9029
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain.Main()
        /tmp/etcd-release-3.3.13/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain/main.go:46 +0x3f fp=0xc420263f78 sp=0xc420263f08 pc=0xc000df
main.main()
        /tmp/etcd-release-3.3.13/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/etcd/main.go:28 +0x20 fp=0xc420263f88 sp=0xc420263f78 pc=0xc02220
runtime.main()
        /usr/local/go/src/runtime/proc.go:198 +0x212 fp=0xc420263fe0 sp=0xc420263f88 pc=0x42c5e2
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc420263fe8 sp=0xc420263fe0 pc=0x459e51

goroutine 4 [chan receive]:
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc42000ac00)
        /tmp/etcd-release-3.3.13/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/logutil/merge_logger.go:174 +0x40d
created by github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/logutil.NewMergeLogger
        /tmp/etcd-release-3.3.13/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/logutil/merge_logger.go:92 +0x85

goroutine 83 [chan receive]:
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc42021b5c0)
        /tmp/etcd-release-3.3.13/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/logutil/merge_logger.go:174 +0x40d
created by github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/logutil.NewMergeLogger
        /tmp/etcd-release-3.3.13/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/logutil/merge_logger.go:92 +0x85

goroutine 54 [chan receive]:
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc4201ecc80)
        /tmp/etcd-release-3.3.13/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/logutil/merge_logger.go:174 +0x40d
created by github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/logutil.NewMergeLogger
        /tmp/etcd-release-3.3.13/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/logutil/merge_logger.go:92 +0x85

goroutine 117 [syscall]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:139 +0xa6
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 63 [select]:
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/wal.(*filePipeline).run(0xc4200db080)
        /tmp/etcd-release-3.3.13/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/wal/file_pipeline.go:89 +0x139
created by github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/wal.newFilePipeline
        /tmp/etcd-release-3.3.13/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/wal/file_pipeline.go:47 +0x11a

goroutine 62 [select]:
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/backend.(*backend).run(0xc42028c4d0)
        /tmp/etcd-release-3.3.13/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/backend/backend.go:267 +0x180
created by github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/backend.newBackend
        /tmp/etcd-release-3.3.13/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/backend/backend.go:161 +0x2ea

goroutine 64 [runnable]:
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/raft.(*node).run(0xc4200c57a0, 0xc4201d4100)
        /tmp/etcd-release-3.3.13/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/raft/node.go:273 +0x17d3
created by github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/raft.RestartNode
        /tmp/etcd-release-3.3.13/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/raft/node.go:223 +0x321
```

**Comment by xiang90** [comment]
will the same thing happen without glusterfs on a local fs?

**Comment by howels** [comment]
What does the error mean? Can we determine what is happening here?
