### ISSUE TITLE
using a docker volume in windows nanoserver fails

### ISSUE THREAD

**Issue by rgl** [etcd-io/etcd#10719]
I'm trying to run etcd in a windows server 2019 container launched by this docker-compose file:

```docker-compose
# see https://docs.docker.com/compose/overview/
# see https://docs.docker.com/compose/compose-file/
version: '3.7'
services:
  etcd:
    build: .
    volumes:
      - etcd:c:/data
    restart: on-failure
volumes:
  etcd: {}
```

And Dockerfile:

```Dockerfile
FROM mcr.microsoft.com/windows/nanoserver:1809 as builder
WORKDIR /Users/ContainerUser/etcd
ADD https://github.com/etcd-io/etcd/releases/download/v3.3.13/etcd-v3.3.13-windows-amd64.zip ../etcd.zip
RUN tar xf ../etcd.zip --strip-components=1 *.exe

FROM mcr.microsoft.com/windows/nanoserver:1809
EXPOSE 2379
VOLUME c:/data
WORKDIR /app
COPY --from=builder /Users/ContainerUser/etcd ./
ENTRYPOINT ["/app/etcd.exe", "--data-dir=c:/data", "--advertise-client-urls=http://0.0.0.0:2379", "--listen-client-urls=http://0.0.0.0:2379"]
```

It fails with:

```
etcd_1   | 2019-05-12 12:30:50.490326 I | etcdmain: etcd Version: 3.3.13
etcd_1   | 2019-05-12 12:30:50.490326 I | etcdmain: Git SHA: 98d3084
etcd_1   | 2019-05-12 12:30:50.490326 I | etcdmain: Go Version: go1.10.8
etcd_1   | 2019-05-12 12:30:50.490326 I | etcdmain: Go OS/Arch: windows/amd64
etcd_1   | 2019-05-12 12:30:50.490326 I | etcdmain: setting maximum number of CPUs to 2, total number of available CPUs is 2
etcd_1   | 2019-05-12 12:30:50.490326 N | etcdmain: failed to detect default host (default host not supported on windows_amd64)
etcd_1   | 2019-05-12 12:30:50.517326 I | embed: listening for peers on http://localhost:2380
etcd_1   | 2019-05-12 12:30:50.519360 I | embed: listening for client requests on 0.0.0.0:2379
etcd_1   | 2019-05-12 12:30:50.550307 I | etcdserver: name = default
etcd_1   | 2019-05-12 12:30:50.550307 I | etcdserver: data dir = c:/data
etcd_1   | 2019-05-12 12:30:50.550307 I | etcdserver: member dir = c:\data\member
etcd_1   | 2019-05-12 12:30:50.550307 I | etcdserver: heartbeat = 100ms
etcd_1   | 2019-05-12 12:30:50.550307 I | etcdserver: election = 1000ms
etcd_1   | 2019-05-12 12:30:50.550307 I | etcdserver: snapshot count = 100000
etcd_1   | 2019-05-12 12:30:50.550307 I | etcdserver: advertise client URLs = http://0.0.0.0:2379
etcd_1   | 2019-05-12 12:30:50.550307 I | etcdserver: initial advertise peer URLs = http://localhost:2380
etcd_1   | 2019-05-12 12:30:50.550307 I | etcdserver: initial cluster = default=http://localhost:2380
etcd_1   | 2019-05-12 12:30:50.572318 I | wal: releasing file lock to rename "c:\\data\\member\\wal.tmp" to "c:\\data\\member\\wal"
etcd_1   | 2019-05-12 12:30:50.574341 C | etcdserver: create wal error: fileutil: file already locked
etcd_1   | panic: create wal error: fileutil: file already locked
etcd_1   |
etcd_1   | goroutine 1 [running]:
etcd_1   | github.com/coreos/etcd/cmd/vendor/github.com/coreos/pkg/capnslog.(*PackageLogger).Panicf(0xc0421e61a0, 0xe48d97, 0x14, 0xc042087208, 0x1, 0x1)
etcd_1   |      /tmp/etcd-release-3.3.13/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/pkg/capnslog/pkg_logger.go:75 +0x169
etcd_1   | github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver.startNode(0xe3e197, 0x7, 0x0, 0x0, 0x0, 0x0, 0xc04218eb00, 0x1, 0x1, 0xc04218e900, ...)
etcd_1   |      /tmp/etcd-release-3.3.13/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/raft.go:406 +0x1ae
etcd_1   | github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver.NewServer(0xe3e197, 0x7, 0x0, 0x0, 0x0, 0x0, 0xc04218eb00, 0x1, 0x1, 0xc04218e900, ...)
etcd_1   |      /tmp/etcd-release-3.3.13/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/server.go:363 +0x2aec
etcd_1   | github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/embed.StartEtcd(0xc042179680, 0xc042179b00, 0x0, 0x0)
etcd_1   |      /tmp/etcd-release-3.3.13/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/embed/etcd.go:179 +0x818
etcd_1   | github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain.startEtcd(0xc042179680, 0xe3b30e, 0x3, 0x1, 0x1)
etcd_1   |      /tmp/etcd-release-3.3.13/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain/etcd.go:181 +0x47
etcd_1   | github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain.startEtcdOrProxyV2()
etcd_1   |      /tmp/etcd-release-3.3.13/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain/etcd.go:111 +0x146b
etcd_1   | github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain.Main()
etcd_1   |      /tmp/etcd-release-3.3.13/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain/main.go:46 +0x46
etcd_1   | main.main()
etcd_1   |      /tmp/etcd-release-3.3.13/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/etcd/main.go:28 +0x27
etcd_1   | 2019-05-12 12:30:55.568321 I | etcdmain: etcd Version: 3.3.13
etcd_1   | 2019-05-12 12:30:55.569601 I | etcdmain: Git SHA: 98d3084
etcd_1   | 2019-05-12 12:30:55.569601 I | etcdmain: Go Version: go1.10.8
etcd_1   | 2019-05-12 12:30:55.569601 I | etcdmain: Go OS/Arch: windows/amd64
etcd_1   | 2019-05-12 12:30:55.569601 I | etcdmain: setting maximum number of CPUs to 2, total number of available CPUs is 2
etcd_1   | 2019-05-12 12:30:55.569601 N | etcdmain: failed to detect default host (default host not supported on windows_amd64)
etcd_1   | 2019-05-12 12:30:55.569601 N | etcdmain: the server is already initialized as member before, starting as etcd member...
etcd_1   | 2019-05-12 12:30:55.576320 I | embed: listening for peers on http://localhost:2380
etcd_1   | 2019-05-12 12:30:55.577317 I | embed: listening for client requests on 0.0.0.0:2379
etcd_1   | 2019-05-12 12:31:05.579426 W | etcdserver: another etcd process is using "c:\\data\\member\\snap\\db" and holds the file lock, or loading backend file is taking >10 seconds
etcd_1   | 2019-05-12 12:31:05.579426 W | etcdserver: waiting for it to exit before starting...  
```

Any idea how to fix this problem?

**Comment by jingyih** [comment]
I am not familiar with this, but the error message says
```
etcd_1   | 2019-05-12 12:31:05.579426 W | etcdserver: another etcd process is using "c:\\data\\member\\snap\\db" and holds the file lock, or loading backend file is taking >10 seconds
etcd_1   | 2019-05-12 12:31:05.579426 W | etcdserver: waiting for it to exit before starting...  
```
Is the same directory used by multiple etcd servers?

**Comment by rgl** [comment]
It's managed by docker-compose as a volume, it should only assign it to a single container/etcd, correct?
