### ISSUE TITLE
grpcproxy wont update keys when consistency=s

### ISSUE THREAD

**Issue by mittonsimon** [etcd-io/etcd#10909]
I have the following setup.
etcd Version: 3.3.12
Go Version: go1.10.8

- 5 member etcd cluster ( across US / EMEA / APAC )
- 10 grpcproxy nodes running 

I have around 10k keys and often running updates to the store.  However, I noticed that sometimes my processes when reading the keys ( using consistency=s) that the latest version of the store was not being retrieved.. 

So I did the following:
Iterate through all the endpoints  and retrieve the keys.  I noticed on 3 out of the 5 grpcproxy endpoints that the version of the keys were stale and would were not updates unless I changed the consistency=l.  I understand that l guarantees quorum but I was also under the impression that eventually the grpcproxy nodes would update after a short period of time (it never updated)

I am not sure how you can reproduce the issue to be honest, but potentially the watches on grpcproxy to the members are not working as expected.  

Looking at the logs There is nothing abnormal On any of the grpcproxy nodes

``````
2019-07-17 19:12:08.557898 I | etcdmain: listening for grpc-proxy client requests on XXXXXXX
WARNING: 2019/07/17 19:13:24 grpc: Server.Serve failed to create ServerTransport:  connection error: desc = "transport: http2Server.HandleStreams failed to read initial settings frame: read tcp XXXXXX:14002->XXXXXX7:46678: read: connection reset by peer"

```````

Would it be recommended to not operate grpcproxy in production?

SIGOUT

```````
SIGQUIT: quit
PC=0x45b521 m=0 sigcode=0

goroutine 0 [idle]:
runtime.futex(0x165f8c8, 0x0, 0x0, 0x0, 0x7fa900000000, 0x9, 0x0, 0x0, 0x7ffe40342e28, 0x40f19b, ...)
    /usr/local/go/src/runtime/sys_linux_amd64.s:530 +0x21
runtime.futexsleep(0x165f8c8, 0xc400000000, 0xffffffffffffffff)
    /usr/local/go/src/runtime/os_linux.go:45 +0x4b
runtime.notesleep(0x165f8c8)
    /usr/local/go/src/runtime/lock_futex.go:151 +0x9b
runtime.stopm()
    /usr/local/go/src/runtime/proc.go:1952 +0xe5
runtime.findrunnable(0xc42008e000, 0x0)
    /usr/local/go/src/runtime/proc.go:2415 +0x50c
runtime.schedule()
    /usr/local/go/src/runtime/proc.go:2541 +0x13b
runtime.park_m(0xc420504d80)
    /usr/local/go/src/runtime/proc.go:2604 +0xb6
runtime.mcall(0x0)
    /usr/local/go/src/runtime/asm_amd64.s:351 +0x5b

goroutine 1 [chan receive, 7222 minutes]:
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain.startGRPCProxy(0xc42036c600, 0xc420305a40, 0x0, 0xa)
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain/grpc_proxy.go:202 +0x3ba
github.com/coreos/etcd/cmd/vendor/github.com/spf13/cobra.(*Command).execute(0xc42036c600, 0xc420305900, 0xa, 0xa, 0xc42036c600, 0xc420305900)
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/spf13/cobra/command.go:572 +0x216
github.com/coreos/etcd/cmd/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1651a20, 0x0, 0x0, 0xd28300)
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/spf13/cobra/command.go:662 +0x32d
github.com/coreos/etcd/cmd/vendor/github.com/spf13/cobra.(*Command).Execute(0x1651a20, 0xc, 0x0)
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/spf13/cobra/command.go:618 +0x2b
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain.Main()
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain/main.go:38 +0xd0
main.main()
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/etcd/main.go:28 +0x20

goroutine 27 [chan receive]:
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc42024ffa0)
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/logutil/merge_logger.go:174 +0x40d
created by github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/logutil.NewMergeLogger
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/logutil/merge_logger.go:92 +0x85

goroutine 63 [chan receive]:
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc4202d2720)
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/logutil/merge_logger.go:174 +0x40d
created by github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/logutil.NewMergeLogger
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/logutil/merge_logger.go:92 +0x85

goroutine 98 [chan receive]:
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc4202d28c0)
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/logutil/merge_logger.go:174 +0x40d
created by github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/logutil.NewMergeLogger
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/logutil/merge_logger.go:92 +0x85

goroutine 76 [select, 7222 minutes]:
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/clientv3.(*healthBalancer).updateNotifyLoop(0xc420218400)
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/clientv3/health_balancer.go:339 +0x379
created by github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/clientv3.newHealthBalancer
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/clientv3/health_balancer.go:128 +0x330

goroutine 84 [syscall, 7222 minutes]:
os/signal.signal_recv(0x0)
    /usr/local/go/src/runtime/sigqueue.go:139 +0xa6
os/signal.loop()
    /usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
    /usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 75 [IO wait]:
internal/poll.runtime_pollWait(0x7fa985094f00, 0x72, 0x0)
    /usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc420214618, 0x72, 0xc4205b0900, 0x0, 0x0)
    /usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc420214618, 0xffffffffffffff00, 0x0, 0x0)
    /usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Accept(0xc420214600, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/internal/poll/fd_unix.go:372 +0x1a8
net.(*netFD).accept(0xc420214600, 0x348, 0xfb0540, 0x0)
    /usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc42000c158, 0xc4211faf00, 0x4101b9, 0xc42026eaf0)
    /usr/local/go/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).Accept(0xc42000c158, 0x10, 0x10, 0xc42026eaf0, 0x0)
    /usr/local/go/src/net/tcpsock.go:259 +0x49
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/transport.(*keepaliveListener).Accept(0xc420306800, 0x434024, 0xc4211faf30, 0x410a08, 0x10)
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/transport/keepalive_listener.go:49 +0x37
crypto/tls.(*listener).Accept(0xc42038b5a0, 0xc42026eaf0, 0xc42026e440, 0xc42029a7c0, 0xc42029a7b8)
    /usr/local/go/src/crypto/tls/tls.go:52 +0x37
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/transport.(*tlsListener).acceptLoop(0xc420100e40)
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/transport/listener_tls.go:126 +0x206
created by github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/transport.newTLSListener
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/transport/listener_tls.go:84 +0x35c

goroutine 77 [select]:
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/clientv3.(*healthBalancer).updateUnhealthy(0xc420218400)
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/clientv3/health_balancer.go:236 +0xed
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/clientv3.newHealthBalancer.func1(0xc420218400)
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/clientv3/health_balancer.go:132 +0x5a
created by github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/clientv3.newHealthBalancer
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/clientv3/health_balancer.go:130 +0x370

goroutine 78 [select, 7222 minutes]:
github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc4203928d0)
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:117 +0x135
created by github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc.newCCBalancerWrapper
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:108 +0x12e
goroutine 79 [chan receive, 7222 minutes]:
github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc.(*balancerWrapper).lbWatcher(0xc420103800)
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc/balancer_v1_wrapper.go:115 +0x177
created by github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc.(*balancerWrapperBuilder).Build
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc/balancer_v1_wrapper.go:53 +0x1f8

goroutine 114 [select, 7222 minutes]:
github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc.(*addrConn).transportMonitor(0xc4203b8400)
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc/clientconn.go:1012 +0x140
github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc.(*addrConn).connect.func1(0xc4203b8400)
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc/clientconn.go:703 +0x1b5
created by github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc.(*addrConn).connect
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc/clientconn.go:694 +0x3c3

goroutine 182927 [select, 7059 minutes]:
context.propagateCancel.func1(0x10aafa0, 0xc4202f0fe0, 0x10a0520, 0xc42074b2c0)
    /usr/local/go/src/context/context.go:260 +0xff
created by context.propagateCancel
    /usr/local/go/src/context/context.go:259 +0x1a7

goroutine 182997 [select, 7059 minutes]:
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/clientv3.(*watchGrpcStream).serveSubstream(0xc42042c8f0, 0xc4202a8bb0, 0xc420bc56e0)
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/clientv3/watch.go:611 +0x2c1
created by github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/clientv3.(*watchGrpcStream).run
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/clientv3/watch.go:452 +0xfea

goroutine 182928 [select, 7059 minutes]:
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/clientv3.(*watchGrpcStream).run(0xc42042c8f0)
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/clientv3/watch.go:438 +0x38e
created by github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/clientv3.(*watcher).newWatcherGrpcStream
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/clientv3/watch.go:236 +0x327

goroutine 132 [chan receive, 7222 minutes]:
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/proxy/grpcproxy.NewWatchProxy.func1(0xc4203d0300, 0xc4203ba240, 0xc4203ce070)
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/proxy/grpcproxy/watch.go:61 +0x7e
created by github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/proxy/grpcproxy.NewWatchProxy
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/proxy/grpcproxy/watch.go:59 +0x1cd

goroutine 133 [chan receive, 7059 minutes]:
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/proxy/grpcproxy.(*leader).recvLoop(0xc4203de1e0)
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/proxy/grpcproxy/leader.go:79 +0x27e
created by github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/proxy/grpcproxy.newLeader
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/proxy/grpcproxy/leader.go:54 +0x169

goroutine 134 [chan receive, 7222 minutes]:
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/proxy/grpcproxy.NewLeaseProxy.func1(0xc4203d04e0, 0xc4203ba2a0, 0xc4203ce090)
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/proxy/grpcproxy/lease.go:60 +0x7e
created by github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/proxy/grpcproxy.NewLeaseProxy
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/proxy/grpcproxy/lease.go:58 +0x1c1

goroutine 182995 [select, 7059 minutes]:
github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc/transport.(*recvBufferReader).read(0xc420b40dc0, 0xc4202784b0, 0x5, 0x5, 0x1c, 0xc4203ea600, 0xc420bca400)
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc/transport/transport.go:133 +0x23f
github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc/transport.(*recvBufferReader).Read(0xc420b40dc0, 0xc4202784b0, 0x5, 0x5, 0xc42004ca70, 0xc42004ca00, 0xc420439b98)
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc/transport/transport.go:122 +0x67
github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc/transport.(*transportReader).Read(0xc42024a9c0, 0xc4202784b0, 0x5, 0x5, 0x47003e, 0xc420bca4c8, 0xc4205acf60)
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc/transport/transport.go:403 +0x55
io.ReadAtLeast(0x109e0a0, 0xc42024a9c0, 0xc4202784b0, 0x5, 0x5, 0x5, 0xc4203ea600, 0xc420bca400, 0x5)
    /usr/local/go/src/io/io.go:309 +0x86
io.ReadFull(0x109e0a0, 0xc42024a9c0, 0xc4202784b0, 0x5, 0x5, 0xc4206a6100, 0xc4206a6100, 0xc420b7dc08)
    /usr/local/go/src/io/io.go:327 +0x58
github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc/transport.(*Stream).Read(0xc420bca400, 0xc4202784b0, 0x5, 0x5, 0x42cbbb, 0xc420b7dc30, 0x455ff0)
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc/transport/transport.go:387 +0xbf
github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc.(*parser).recvMsg(0xc4202784a0, 0x7fffffff, 0x2, 0x0, 0x2, 0x2, 0x2, 0x0)
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc/rpc_util.go:270 +0x65
github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc.recv(0xc4202784a0, 0x10aa620, 0x167f170, 0xc420bca400, 0x0, 0x0, 0xf58000, 0xc420b40e10, 0x7fffffff, 0x0, ...)
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc/rpc_util.go:356 +0x4d
github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc.(*clientStream).RecvMsg(0xc420cd6870, 0xf58000, 0xc420b40e10, 0x0, 0x0)
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc/stream.go:392 +0xcb
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/etcdserverpb.(*watchWatchClient).Recv(0xc4202f1040, 0x0, 0x0, 0x0)
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/etcdserverpb/rpc.pb.go:3459 +0x62
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/clientv3.(*watchGrpcStream).serveWatchClient(0xc42042c8f0, 0x10b1fc0, 0xc4202f1040)
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/clientv3/watch.go:565 +0x4e
created by github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/clientv3.(*watchGrpcStream).newWatchClient
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/clientv3/watch.go:720 +0x58f
goroutine 132 [chan receive, 7222 minutes]:
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/proxy/grpcproxy.NewWatchProxy.func1(0xc4203d0300, 0xc4203ba240, 0xc4203ce070)
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/proxy/grpcproxy/watch.go:61 +0x7e
created by github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/proxy/grpcproxy.NewWatchProxy
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/proxy/grpcproxy/watch.go:59 +0x1cd

goroutine 133 [chan receive, 7059 minutes]:
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/proxy/grpcproxy.(*leader).recvLoop(0xc4203de1e0)
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/proxy/grpcproxy/leader.go:79 +0x27e
created by github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/proxy/grpcproxy.newLeader
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/proxy/grpcproxy/leader.go:54 +0x169

goroutine 134 [chan receive, 7222 minutes]:
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/proxy/grpcproxy.NewLeaseProxy.func1(0xc4203d04e0, 0xc4203ba2a0, 0xc4203ce090)
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/proxy/grpcproxy/lease.go:60 +0x7e
created by github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/proxy/grpcproxy.NewLeaseProxy
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/proxy/grpcproxy/lease.go:58 +0x1c1

goroutine 182995 [select, 7059 minutes]:
github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc/transport.(*recvBufferReader).read(0xc420b40dc0, 0xc4202784b0, 0x5, 0x5, 0x1c, 0xc4203ea600, 0xc420bca400)
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc/transport/transport.go:133 +0x23f
github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc/transport.(*recvBufferReader).Read(0xc420b40dc0, 0xc4202784b0, 0x5, 0x5, 0xc42004ca70, 0xc42004ca00, 0xc420439b98)
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc/transport/transport.go:122 +0x67
github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc/transport.(*transportReader).Read(0xc42024a9c0, 0xc4202784b0, 0x5, 0x5, 0x47003e, 0xc420bca4c8, 0xc4205acf60)
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc/transport/transport.go:403 +0x55
io.ReadAtLeast(0x109e0a0, 0xc42024a9c0, 0xc4202784b0, 0x5, 0x5, 0x5, 0xc4203ea600, 0xc420bca400, 0x5)
    /usr/local/go/src/io/io.go:309 +0x86
io.ReadFull(0x109e0a0, 0xc42024a9c0, 0xc4202784b0, 0x5, 0x5, 0xc4206a6100, 0xc4206a6100, 0xc420b7dc08)
    /usr/local/go/src/io/io.go:327 +0x58
github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc/transport.(*Stream).Read(0xc420bca400, 0xc4202784b0, 0x5, 0x5, 0x42cbbb, 0xc420b7dc30, 0x455ff0)
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc/transport/transport.go:387 +0xbf
github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc.(*parser).recvMsg(0xc4202784a0, 0x7fffffff, 0x2, 0x0, 0x2, 0x2, 0x2, 0x0)
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc/rpc_util.go:270 +0x65
github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc.recv(0xc4202784a0, 0x10aa620, 0x167f170, 0xc420bca400, 0x0, 0x0, 0xf58000, 0xc420b40e10, 0x7fffffff, 0x0, ...)
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc/rpc_util.go:356 +0x4d
github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc.(*clientStream).RecvMsg(0xc420cd6870, 0xf58000, 0xc420b40e10, 0x0, 0x0)
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc/stream.go:392 +0xcb
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/etcdserverpb.(*watchWatchClient).Recv(0xc4202f1040, 0x0, 0x0, 0x0)
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/etcdserverpb/rpc.pb.go:3459 +0x62
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/clientv3.(*watchGrpcStream).serveWatchClient(0xc42042c8f0, 0x10b1fc0, 0xc4202f1040)
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/clientv3/watch.go:565 +0x4e
created by github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/clientv3.(*watchGrpcStream).newWatchClient
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/clientv3/watch.go:720 +0x58f


goroutine 182996 [select, 7059 minutes]:
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/clientv3.(*watchGrpcStream).serveSubstream(0xc42042c8f0, 0xc4202a8b00, 0xc420bc56e0)
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/clientv3/watch.go:611 +0x2c1
created by github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/clientv3.(*watchGrpcStream).run
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/clientv3/watch.go:452 +0xfea

goroutine 182994 [select, 7059 minutes]:
github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc.newClientStream.func4(0x10b2440, 0xc4203ea600, 0xc4203a6000, 0xc420cd6870, 0xc420bca400)
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc/stream.go:255 +0x19b
created by github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc.newClientStream
    /tmp/etcd-release-3.3.12/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/google.golang.org/grpc/stream.go:254 +0xcc4


```````

**Comment by jingyih** [comment]
"consistency=s" by definition does not guarantee linearizability, which means the reading result could be stale.

https://github.com/etcd-io/etcd/blob/master/Documentation/learning/api_guarantees.md#linearizability

**Comment by jingyih** [comment]
More reference: https://en.wikipedia.org/wiki/Linearizability

**Comment by mittonsimon** [comment]
Hi,

I understand that. The point I am making is that some grpcproxy nodes are never getting updated ever.

Do I need to therefore always use consistency=l when querying via grpcproxy? Is there some interval the grpcproxy will ask for the updated keys from the members?
