### ISSUE TITLE
Fail to start if parent program incorporates embed server

### ISSUE THREAD

**Issue by liyimeng** [etcd-io/etcd#11098]
When using the latest version (3.4.0) in my program, which is also using protobuf, I go error like this: 

`
2019/08/30 23:25:21 proto: duplicate proto type registered: authpb.User
2019/08/30 23:25:21 proto: duplicate proto type registered: authpb.Permission
2019/08/30 23:25:21 proto: duplicate proto type registered: authpb.Role
panic: proto: duplicate enum registered: authpb.Permission_Type

goroutine 1 [running]:
github.com/golang/protobuf/proto.RegisterEnum(...)
        /Users/liyi/golang/pkg/mod/github.com/golang/protobuf@v1.3.2/proto/properties.go:458
go.etcd.io/etcd/auth/authpb.init.0()
        /Users/liyi/golang/pkg/mod/go.etcd.io/etcd@v0.0.0-20190830150955-898bd1351fcf/auth/authpb/auth.pb.go:115 +0x1e6
`

Similar issue was reported in https://github.com/etcd-io/etcd/issues/5986

**Comment by liyimeng** [comment]
Sorry, it is because of part of my program using etcd from GitHub while another part for go.etcd.io
