### ISSUE TITLE
Discover the panic using the etcd distributed lock feature

### ISSUE THREAD

**Issue by guonaihong** [etcd-io/etcd#11185]
#### etcd run command
```shell
./etcd
```
#### version
```
./etcd -version
etcd Version: 3.4.1
Git SHA: a14579fbf
Go Version: go1.12.9
Go OS/Arch: linux/amd64

```

#### test code
```go
package test

import (
	"context"
	"fmt"
	//"github.com/etcd-io/etcd/clientv3"
	"github.com/coreos/etcd/clientv3"
	"github.com/etcd-io/etcd/clientv3/concurrency"
	"sync"
	"sync/atomic"
	"testing"
	"time"
)

// sync.atomic
func Benchmark_atomic(b *testing.B) {
	// t.Fatal("not implemented")
	i := int64(0)
	b.ReportAllocs()
	b.RunParallel(func(pb *testing.PB) {

		for pb.Next() {
			atomic.AddInt64(&i, 1)
		}
	})
}

// sync.Lock
func Benchmark_lock(b *testing.B) {
	i := int64(0)
	var lock sync.Mutex

	b.ReportAllocs()
	b.RunParallel(func(pb *testing.PB) {

		for pb.Next() {
			lock.Lock()
			i++
			lock.Unlock()

		}
	})
}

// etcd 单个进程 lock
func Benchmark_etcdOneLock(b *testing.B) {
	i := int64(0)
	b.Logf("start etcd\n")
	fmt.Printf("start etcd\n")
	cli, err := clientv3.New(clientv3.Config{Endpoints: []string{"127.0.0.1:2379"}, DialTimeout: 3 * time.Second})
	if err != nil {
		fmt.Printf("client v3 fail:%s\n", err)
		return
	}

	fmt.Printf("start new session\n")
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	ss2, err := concurrency.NewSession(cli, concurrency.WithContext(ctx))
	if err != nil {
		fmt.Printf("new session fail:%s\n", err)
		return
	}

	b.ReportAllocs()

	mu2 := concurrency.NewMutex(ss2, "/my-lock/")

	b.RunParallel(func(pb *testing.PB) {
		for pb.Next() {
			err = mu2.Lock(context.Background())
			if err != nil {
				fmt.Println("get lock2 failed!")
				return
			}

			i++
			err = mu2.Unlock(context.Background())
			if err != nil {
				fmt.Println("free lock2 failed!")
				return
			}
		}
	})
}

```
#### run command
```go
env GO111MODULE=on GOPROXY=https://goproxy.cn go test -test.bench="Benchmark_etcdOneLock"
```
#### panic message
```
start etcd
start new session
goos: linux
goarch: amd64
pkg: test
Benchmark_etcdOneLock-4   	start etcd
start new session
panic: runtime error: index out of range [0] with length 0

goroutine 60 [running]:
github.com/etcd-io/etcd/clientv3/concurrency.(*Mutex).Lock(0xc000272640, 0xc1f280, 0xc0000b2010, 0x0, 0x0)
	/home/guo/go/pkg/mod/github.com/etcd-io/etcd@v3.3.15+incompatible/clientv3/concurrency/mutex.go:60 +0xd39
test.Benchmark_etcdOneLock.func1(0xc0001589c0)
	/home/guo/go-bench-code/lock/lock_test.go:72 +0xd0
testing.(*B).RunParallel.func1(0xc00027c140, 0xc00027c138, 0xc00027c130, 0xc0000ea000, 0xc0001585a0)
	/home/guo/go-version/go1.13.1/src/testing/benchmark.go:742 +0xa1
created by testing.(*B).RunParallel
	/home/guo/go-version/go1.13.1/src/testing/benchmark.go:735 +0x192
exit status 2
FAIL	test	0.309s

```

**Comment by wanhl1990** [comment]
Anyone met this error？ I met this
`
panic: runtime error: index out of range

goroutine 81 [running]:
github.com/coreos/etcd/clientv3/concurrency.(*Mutex).Lock(0xc00029ab40, 0x1402fe0, 0xc000565920, 0x1402fe0, 0xc000565920)
	/root/go/src/container-scan/src/vendor/github.com/coreos/etcd/clientv3/concurrency/mutex.go:60 +0xd38

`

**Comment by penglongli** [comment]
Same problem with large concurrency.

https://github.com/etcd-io/etcd/blob/v3.3.18/clientv3/concurrency/mutex.go#L60

Hi @xiang90 Can this issue be reopened?
