### ISSUE TITLE
got unexpected response error (etcdserver: request timed out)

### ISSUE THREAD

**Issue by Tekchanddagar** [etcd-io/etcd#11290]
Hello Team,

Yesterday night i was facing a issue that my patroni unable to communicate with etcd server. Then i checked logs in patroni and etcd server. Over patroni logs showing that patroni unable to communicate with etcd and its timeout. 

Below are the logs from patroni:
```
2019-10-24 22:19:21,520 WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=0, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='10.133.238.133', port=2379): Read timed out. (read timeout=3.3333333333333335)",)': /v2/keys/db/promobi/optime/leader
2019-10-24 22:19:24,861 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='10.133.238.133', port=2379): Read timed out. (read timeout=3.3333333333333335)",)': /v2/keys/db/promobi/optime/leader
2019-10-24 22:19:28,201 ERROR: Request to server http://10.133.238.133:2379 failed: MaxRetryError('HTTPConnectionPool(host=\'10.133.238.133\', port=2379): Max retries exceeded with url: /v2/keys/db/promobi/optime/leader (Caused by ReadTimeoutError("HTTPConnectionPool(host=\'10.133.238.133\', port=2379): Read timed out. (read timeout=3.3333333333333335)",))',)
2019-10-24 22:19:28,201 INFO: Reconnection allowed, looking for another server.
2019-10-24 22:19:28,201 ERROR: Machines cache is empty, no machines to try.
2019-10-24 22:19:28,201 ERROR: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1213, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 307, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='10.133.238.133', port=2379): Read timed out. (read timeout=3.3333333333333335)
```

Then i checked the logs over etcd machine and getting below logs:
```
Oct 24 22:19:46 sf-db-etcd etcd[2594]: got unexpected response error (etcdserver: request timed out) [merged 1 repeated lines in 1.74s]
Oct 24 22:19:46 sf-db-etcd etcd[2594]: got unexpected response error (etcdserver: request timed out)
Oct 24 22:19:46 sf-db-etcd etcd[2594]: got unexpected response error (etcdserver: request timed out) [merged 1 repeated lines in 1.41s]
Oct 24 22:19:46 sf-db-etcd etcd[2594]: got unexpected response error (etcdserver: request timed out)
Oct 24 22:19:46 sf-db-etcd etcd[2594]: got unexpected response error (etcdserver: request timed out) [merged 1 repeated lines in 1.05s]
Oct 24 22:19:46 sf-db-etcd etcd[2594]: sync duration of 28.303778988s, expected less than 1s
Oct 24 22:20:05 sf-db-etcd etcd[2594]: got unexpected response error (etcdserver: request timed out)
Oct 24 22:20:06 sf-db-etcd etcd[2594]: got unexpected response error (etcdserver: request timed out) [merged 1 repeated lines in 1.06s]
Oct 24 22:20:08 sf-db-etcd etcd[2594]: got unexpected response error (etcdserver: request timed out)
Oct 24 22:20:10 sf-db-etcd etcd[2594]: got unexpected response error (etcdserver: request timed out) [merged 1 repeated lines in 1.72s]
Oct 24 22:20:11 sf-db-etcd etcd[2594]: got unexpected response error (etcdserver: request timed out)
Oct 24 22:20:13 sf-db-etcd etcd[2594]: got unexpected response error (etcdserver: request timed out) [merged 1 repeated lines in 1.38s]
Oct 24 22:20:14 sf-db-etcd etcd[2594]: sync duration of 23.959374995s, expected less than 1s

```

is it disk performance issue at etcd machine? If yes then how we can fix it? Because we are using digitalocean cloud and we are using SSD disk which is provided by DigitalOcean cloud.

Please help me.

Thanks.

**Comment by Tekchanddagar** [comment]
Hello Team,

Can you please help me on above issue? Its become serious issue for us.

Thanks.

**Comment by Tekchanddagar** [comment]
Hello Team,

Any help?

Thanks.

**Comment by gabricar** [comment]
I'm seeing the same issues on one of my clusters. But I don't have disk latency
