### ISSUE TITLE
v3.3.10 panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by zhangguanzhang** [etcd-io/etcd#11444]
command
```
/opt/kube/bin/etcd --name=etcd1 \
  --cert-file=/etc/etcd/ssl/etcd.pem \
  --key-file=/etc/etcd/ssl/etcd-key.pem \
  --peer-cert-file=/etc/etcd/ssl/etcd.pem \
  --peer-key-file=/etc/etcd/ssl/etcd-key.pem \
  --trusted-ca-file=/etc/kubernetes/ssl/ca.pem \
  --peer-trusted-ca-file=/etc/kubernetes/ssl/ca.pem \
  --initial-advertise-peer-urls=https://192.168.9.182:2380 \
  --listen-peer-urls=https://192.168.9.182:2380 \
  --listen-client-urls=https://192.168.9.182:2379,http://127.0.0.1:2379 \
  --advertise-client-urls=https://192.168.9.182:2379 \
  --initial-cluster-token=etcd-cluster-0 \
  --initial-cluster=etcd1=https://192.168.9.182:2380 \
  --initial-cluster-state=existing \
  --data-dir=/var/lib/etcd \
  --debug
```
output
```
2019-12-12 08:15:35.892834 I | etcdmain: etcd Version: 3.3.10
2019-12-12 08:15:35.892891 I | etcdmain: Git SHA: 27fc7e2
2019-12-12 08:15:35.892895 I | etcdmain: Go Version: go1.10.4
2019-12-12 08:15:35.892897 I | etcdmain: Go OS/Arch: linux/amd64
2019-12-12 08:15:35.892900 I | etcdmain: setting maximum number of CPUs to 2, total number of available CPUs is 2
2019-12-12 08:15:35.892937 N | etcdmain: the server is already initialized as member before, starting as etcd member...
2019-12-12 08:15:35.892950 I | embed: peerTLS: cert = /etc/etcd/ssl/etcd.pem, key = /etc/etcd/ssl/etcd-key.pem, ca = , trusted-ca = /etc/kubernetes/ssl/ca.pem, client-cert-auth = false, crl-file = 
2019-12-12 08:15:35.893364 I | embed: listening for peers on https://192.168.9.182:2380
2019-12-12 08:15:35.893380 W | embed: The scheme of client url http://127.0.0.1:2379 is HTTP while peer key/cert files are presented. Ignored key/cert files.
2019-12-12 08:15:35.893400 I | embed: listening for client requests on 127.0.0.1:2379
2019-12-12 08:15:35.893419 I | embed: listening for client requests on 192.168.9.182:2379
2019-12-12 08:15:35.895634 I | etcdserver: recovered store from snapshot at index 342999
2019-12-12 08:15:35.895929 I | mvcc: restore compact to 372652
panic: runtime error: slice bounds out of range

goroutine 113 [running]:
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc.bytesToRev(0x7fc979b8c0b0, 0x5, 0x5, 0x0, 0x1680360)
	/tmp/etcd-release-3.3.10/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/revision.go:58 +0x73
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc.restoreIntoIndex.func1(0xc42018a460, 0xc4202eb4a0, 0x10b42e0, 0xc4202f9f60)
	/tmp/etcd-release-3.3.10/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/kvstore.go:428 +0x229
created by github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc.restoreIntoIndex
	/tmp/etcd-release-3.3.10/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/kvstore.go:403 +0xa0

```

**Comment by xiang90** [comment]
can you reproduce it?

**Comment by zhangguanzhang** [comment]
sorry，I rebuild the cluster with the new version after the problem

**Comment by mkarg** [comment]
Same happened to me today after updating all parts of Photon 3 to latest versions using `tdnf update`:

```
Feb 16 14:59:41 photon-machine etcd[2674]: panic: runtime error: slice bounds out of range [:8] with capacity 5
Feb 16 14:59:41 photon-machine etcd[2674]: goroutine 93 [running]:
Feb 16 14:59:41 photon-machine etcd[2674]: github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc.bytesToRev(0x7fb6b8b360b0, 0x5, 0x5, 0x0, 0x172ae80)
Feb 16 14:59:41 photon-machine etcd[2674]:         /usr/src/photon/BUILD/etcd-3.3.13/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/revision.go:58 +0x81
Feb 16 14:59:41 photon-machine etcd[2674]: github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc.restoreIntoIndex.func1(0xc000148380, 0xc0001ca060, 0x10272e0, 0xc0002c9060)
Feb 16 14:59:41 photon-machine etcd[2674]:         /usr/src/photon/BUILD/etcd-3.3.13/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/kvstore.go:428 +0x249
Feb 16 14:59:41 photon-machine etcd[2674]: created by github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc.restoreIntoIndex
Feb 16 14:59:41 photon-machine etcd[2674]:         /usr/src/photon/BUILD/etcd-3.3.13/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/kvstore.go:403 +0xa0
```

**Comment by zhangguanzhang** [comment]
，

**Comment by bessyosper** [comment]
i got the similar issue when i am trying to upgrade to v3.0.0  from 2.3.1.I migrated the etcd data and tried to start the etcd service . 
`panic: runtime error: slice bounds out of range

goroutine 1 [running]:
panic(0xf59ee0, 0xc82000e0a0)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
`
