### ISSUE TITLE
Power went down, restore from snapshot gives SIGSEGV

### ISSUE THREAD

**Issue by MarcoStuurman** [etcd-io/etcd#11560]
The power of my cluster went down. The restore of the snapshot doesn't work:

```
2020-01-28 10:03:44.617587 I | pkg/flags: recognized and used environment variable ETCD_ADVERTISE_CLIENT_URLS=https://10.1.0.13:2379
2020-01-28 10:03:44.617752 I | pkg/flags: recognized and used environment variable ETCD_CERT_FILE=/etc/etcd/ssl/kube3.local.pem
2020-01-28 10:03:44.617878 I | pkg/flags: recognized and used environment variable ETCD_DATA_DIR=/var/lib/etcd
2020-01-28 10:03:44.617900 I | pkg/flags: recognized and used environment variable ETCD_INITIAL_ADVERTISE_PEER_URLS=https://10.1.0.13:2380
2020-01-28 10:03:44.617983 I | pkg/flags: recognized and used environment variable ETCD_INITIAL_CLUSTER=kube1.local=https://10.1.0.11:2380,kube2.local=https://10.1.0.12:2380,kube3.local=https://10.1.0.13:2380
2020-01-28 10:03:44.617992 I | pkg/flags: recognized and used environment variable ETCD_INITIAL_CLUSTER_STATE=new
2020-01-28 10:03:44.617998 I | pkg/flags: recognized and used environment variable ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster-01
2020-01-28 10:03:44.618004 I | pkg/flags: recognized and used environment variable ETCD_KEY_FILE=/etc/etcd/ssl/kube3.localx-key.pem
2020-01-28 10:03:44.618041 I | pkg/flags: recognized and used environment variable ETCD_LISTEN_CLIENT_URLS=https://10.1.0.13:2379
2020-01-28 10:03:44.618104 I | pkg/flags: recognized and used environment variable ETCD_LISTEN_PEER_URLS=https://10.1.0.13:2380
2020-01-28 10:03:44.618115 I | pkg/flags: recognized and used environment variable ETCD_NAME=kube3.local
2020-01-28 10:03:44.618124 I | pkg/flags: recognized and used environment variable ETCD_PEER_CERT_FILE=/etc/etcd/ssl/kube3.local.pem
2020-01-28 10:03:44.618130 I | pkg/flags: recognized and used environment variable ETCD_PEER_CLIENT_CERT_AUTH=true
2020-01-28 10:03:44.618140 I | pkg/flags: recognized and used environment variable ETCD_PEER_KEY_FILE=/etc/etcd/ssl/kube3.local-key.pem
2020-01-28 10:03:44.618202 I | pkg/flags: recognized and used environment variable ETCD_PEER_TRUSTED_CA_FILE=/etc/etcd/ssl/ca.pem
2020-01-28 10:03:44.618218 I | pkg/flags: recognized and used environment variable ETCD_TRUSTED_CA_FILE=/etc/etcd/ssl/ca.pem
2020-01-28 10:03:44.618268 I | etcdmain: etcd Version: 3.3.13
2020-01-28 10:03:44.618323 I | etcdmain: Git SHA: 98d3084
2020-01-28 10:03:44.618330 I | etcdmain: Go Version: go1.10.8
2020-01-28 10:03:44.618335 I | etcdmain: Go OS/Arch: linux/amd64
2020-01-28 10:03:44.618340 I | etcdmain: setting maximum number of CPUs to 4, total number of available CPUs is 4
2020-01-28 10:03:44.618435 N | etcdmain: the server is already initialized as member before, starting as etcd member...
2020-01-28 10:03:44.618477 I | embed: peerTLS: cert = /etc/etcd/ssl/kube3.localx.pem, key = /etc/etcd/ssl/kube3.local-key.pem, ca = , trusted-ca = /etc/etcd/ssl/ca.pem, client-cert-auth = true, crl-file =
2020-01-28 10:03:44.618872 I | embed: listening for peers on https://10.1.0.13:2380
2020-01-28 10:03:44.619034 I | embed: listening for client requests on 10.1.0.13:2379
2020-01-28 10:03:44.620352 I | etcdserver: recovered store from snapshot at index 18200185
2020-01-28 10:03:44.621741 C | etcdserver: recovering backend from snapshot error: database snapshot file path error: snap: snapshot file doesn't exist
panic: recovering backend from snapshot error: database snapshot file path error: snap: snapshot file doesn't exist
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xa5f6b0]

goroutine 1 [running]:
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver.NewServer.func1(0xc420263ca0, 0xc420263758)
        /tmp/etcd-release-3.3.13/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/server.go:291 +0x40
panic(0xc94460, 0xc420538070)
        /usr/local/go/src/runtime/panic.go:502 +0x229
github.com/coreos/etcd/cmd/vendor/github.com/coreos/pkg/capnslog.(*PackageLogger).Panicf(0xc420252000, 0xe3e791, 0x2a, 0xc4202637f8, 0x1, 0x1)
        /tmp/etcd-release-3.3.13/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/pkg/capnslog/pkg_logger.go:75 +0x162
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver.NewServer(0xc4200380ea, 0xb, 0x0, 0x0, 0x0, 0x0, 0xc420284900, 0x1, 0x1, 0xc420284a00, ...)
        /tmp/etcd-release-3.3.13/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/server.go:386 +0x26bb
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/embed.StartEtcd(0xc420280480, 0xc420280900, 0x0, 0x0)
        /tmp/etcd-release-3.3.13/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/embed/etcd.go:179 +0x811
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain.startEtcd(0xc420280480, 0xe1c531, 0x6, 0xc420264d01, 0x2)
        /tmp/etcd-release-3.3.13/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain/etcd.go:181 +0x40
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain.startEtcdOrProxyV2()
        /tmp/etcd-release-3.3.13/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain/etcd.go:102 +0x1369
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain.Main()
        /tmp/etcd-release-3.3.13/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain/main.go:46 +0x3f
main.main()
        /tmp/etcd-release-3.3.13/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/etcd/main.go:28 +0x20
```

I'm trying to figure out if this is a bug or this is something I could fix myself. There are 3 nodes, all have the same issue and all went down together.

I hope someone here can shine a light on this.

edit:

It's missing /var/lib/etcd/member/snap/000000000115b679.snap.db

I only have  /var/lib/etcd/member/snap/0000000000000069-000000000115b679.snap

**Comment by tedyu** [comment]
Have you encountered similar issue since January ?

Which etcd release are you using ?

Thanks
