### ISSUE TITLE
Proto panics in Raft

### ISSUE THREAD

**Issue by parasssh** [etcd-io/etcd#12115]
```
panic: proto: illegal wireType 6

goroutine 294 [running]:
http://go.etcd.io/etcd/raft.(*raftLog).slice(0xc00057e150, 0x199c0f, 0x199c10, 0x4000000, 0xc06e0c93b0, 0x1, 0x1, 0x0, 0xc033054978)
/go/pkg/mod/go.etcd.io/etcd@v0.0.0-20190228193606-a943ad0ee4c9/raft/log.go:322 +0x711
http://go.etcd.io/etcd/raft.(*raftLog).nextEnts(0xc00057e150, 0xc06df6dc60, 0x0, 0x0)
/go/pkg/mod/go.etcd.io/etcd@v0.0.0-20190228193606-a943ad0ee4c9/raft/log.go:154 +0x79
http://go.etcd.io/etcd/raft.newReady(0xc0001d4000, 0xc0474136a0, 0x5, 0x0, 0x199c0e, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
/go/pkg/mod/go.etcd.io/etcd@v0.0.0-20190228193606-a943ad0ee4c9/raft/node.go:583 +0x8f
http://go.etcd.io/etcd/raft.(*node).run(0xc023272900, 0xc0001d4000)
/go/pkg/mod/go.etcd.io/etcd@v0.0.0-20190228193606-a943ad0ee4c9/raft/node.go:319 +0x1621
created by http://go.etcd.io/etcd/raft.StartNode
/go/pkg/mod/go.etcd.io/etcd@v0.0.0-20190228193606-a943ad0ee4c9/raft/node.go:233 +0x407
```

This was seen when we used the dgraph DB. It is not reproducible and was reported in our version Dgrpah v20.03.1 from the field via sentry. The panic stack trace is as shown above.

**Comment by gyuho** [comment]
Do you have raw data from your WAL? This also can happen when proto body is not encoded in binary

**Comment by parasssh** [comment]
Unfortunately, no. This happened from an instance of the Dgraph DB in the field and was reported via sentry. We don't know who owns that instance (reports are anonymized), so cannot get much more info.

**Comment by tedyu** [comment]
20190228193606 seems to be old.
