### ISSUE TITLE
When power failure,  single node etcd cluster can not restored from snapshot

### ISSUE THREAD

**Issue by bingerambo** [etcd-io/etcd#12237]
I deployed single node etcd cluster in a production environment. 
When power failure, The etcd server failed to restart.

### 2.  etcd env config:

```
# Environment file for etcd v3.3.10
ETCD_DATA_DIR=/var/lib/etcd
ETCD_ADVERTISE_CLIENT_URLS=https://192.168.1.2:2379
ETCD_INITIAL_ADVERTISE_PEER_URLS=https://192.168.1.2:2380
ETCD_INITIAL_CLUSTER_STATE=existing
#ETCD_INITIAL_CLUSTER_STATE=new
ETCD_METRICS=basic
ETCD_LISTEN_CLIENT_URLS=https://192.168.1.2:2379,https://127.0.0.1:2379
ETCD_ELECTION_TIMEOUT=5000
ETCD_HEARTBEAT_INTERVAL=250
ETCD_INITIAL_CLUSTER_TOKEN=k8s_etcd
ETCD_LISTEN_PEER_URLS=https://192.168.1.2:2380
ETCD_NAME=etcd1
ETCD_PROXY=off
ETCD_INITIAL_CLUSTER=etcd1=https://192.168.1.2:2380
ETCD_AUTO_COMPACTION_RETENTION=8
ETCD_SNAPSHOT_COUNT=10000
ETCD_QUOTA_BACKEND_BYTES=4294967296

# TLS settings
ETCD_TRUSTED_CA_FILE=/etc/ssl/etcd/ssl/ca.pem
ETCD_CERT_FILE=/etc/ssl/etcd/ssl/member-node1.pem
ETCD_KEY_FILE=/etc/ssl/etcd/ssl/member-node1-key.pem
ETCD_CLIENT_CERT_AUTH=true

ETCD_PEER_TRUSTED_CA_FILE=/etc/ssl/etcd/ssl/ca.pem
ETCD_PEER_CERT_FILE=/etc/ssl/etcd/ssl/member-node1.pem
ETCD_PEER_KEY_FILE=/etc/ssl/etcd/ssl/member-node1-key.pem
ETCD_PEER_CLIENT_CERT_AUTH=True
```

### 3. Log information of node abnormal power failure:
```
Aug  8 23:49:39 node1 systemd: Stopping libcontainer_223897_systemd_test_default.slice.
Aug  8 23:49:39 node1 systemd: Created slice libcontainer_223942_systemd_test_default.slice.
Aug  8 23:49:39 node1 systemd: Starting libcontainer_223942_systemd_test_default.slice.
Aug  8 23:49:39 node1 systemd: Removed slice libcontainer_223942_systemd_test_default.slice.
Aug  8 23:49:39 node1 systemd: Stopping libcontainer_223942_systemd_test_default.slice.
Aug  8 23:49:39 node1 systemd: Created slice libcontainer_223958_systemd_test_default.slice.
Aug  8 23:49:39 node1 systemd: Starting libcontainer_223958_systemd_test_default.slice.
Aug  8 23:49:39 node1 systemd: Removed slice libcontainer_223958_systemd_test_default.slice.
Aug  8 23:49:39 node1 systemd: Stopping libcontainer_223958_systemd_test_default.slice.
Aug  8 23:49:39 node1 systemd: Created slice libcontainer_223983_systemd_test_default.slice.
Aug  8 23:49:39 node1 systemd: Starting libcontainer_223983_systemd_test_default.slice.
Aug  8 23:49:39 node1 systemd: Removed slice libcontainer_223983_systemd_test_default.slice.
Aug  8 23:49:39 node1 systemd: Stopping libcontainer_223983_systemd_test_default.slice.
Aug  8 23:49:39 node1 systemd: Created slice libcontainer_223983_systemd_test_default.slice.
Aug  8 23:49:39 node1 systemd: Starting libcontainer_223983_systemd_test_default.slice.
Aug  8 23:49:39 node1 systemd: Removed slice libcontainer_223983_systemd_test_default.slice.
Aug  8 23:49:39 node1 systemd: Stopping libcontainer_223983_systemd_test_default.slice.
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@Aug  9 00:11:02 node1 kernel: Initializing cgroup subsys cpuset
Aug  9 00:11:02 node1 kernel: Initializing cgroup subsys cpu
Aug  9 00:11:02 node1 kernel: Initializing cgroup subsys cpuacct
Aug  9 00:11:02 node1 kernel: Linux version 3.10.0-862.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-28) (GCC) ) #1 SMP Fri Apr 20 16:44:24 UTC 2018
Aug  9 00:11:02 node1 kernel: Command line: BOOT_IMAGE=/vmlinuz-3.10.0-862.el7.x86_64 root=UUID=ba0225a4-6a3f-4df9-a30e-004d476ccd1d ro crashkernel=auto rhgb quiet LANG=en_US.UTF-8
Aug  9 00:11:02 node1 kernel: e820: BIOS-provided physical RAM map:
Aug  9 00:11:02 node1 kernel: BIOS-e820: [mem 0x0000000000000000-0x000000000009ffff] usable
Aug  9 00:11:02 node1 kernel: BIOS-e820: [mem 0x00000000000a0000-0x00000000000fffff] reserved
Aug  9 00:11:02 node1 kernel: BIOS-e820: [mem 0x0000000000100000-0x0000000059d7dfff] usable
Aug  9 00:11:02 node1 kernel: BIOS-e820: [mem 0x0000000059d7e000-0x000000005c619fff] reserved
Aug  9 00:11:02 node1 kernel: BIOS-e820: [mem 0x000000005c61a000-0x000000005c789fff] usable
Aug  9 00:11:02 node1 kernel: BIOS-e820: [mem 0x000000005c78a000-0x000000005d1c8fff] ACPI NVS
Aug  9 00:11:02 node1 kernel: BIOS-e820: [mem 0x000000005d1c9000-0x000000005f345fff] reserved
Aug  9 00:11:02 node1 kernel: BIOS-e820: [mem 0x000000005f346000-0x000000006f7fffff] usable
Aug  9 00:11:02 node1 kernel: BIOS-e820: [mem 0x000000006f800000-0x000000008fffffff] reserved
Aug  9 00:11:02 node1 kernel: BIOS-e820: [mem 0x00000000fd000000-0x00000000fe7fffff] reserved
```

### 4. etcd log info:
```
2020-08-19 03:30:40.015177 I | pkg/flags: recognized and used environment variable ETCD_INITIAL_CLUSTER_STATE=existing
2020-08-19 03:30:40.015186 I | pkg/flags: recognized and used environment variable ETCD_INITIAL_CLUSTER_TOKEN=k8s_etcd
2020-08-19 03:30:40.015194 I | pkg/flags: recognized and used environment variable ETCD_KEY_FILE=/etc/ssl/etcd/ssl/member-node1-key.pem
2020-08-19 03:30:40.015204 I | pkg/flags: recognized and used environment variable ETCD_LISTEN_CLIENT_URLS=https://192.168.1.2:2379,https://127.0.0.1:2379
2020-08-19 03:30:40.015218 I | pkg/flags: recognized and used environment variable ETCD_LISTEN_PEER_URLS=https://192.168.1.2:2380
2020-08-19 03:30:40.015231 I | pkg/flags: recognized and used environment variable ETCD_METRICS=basic
2020-08-19 03:30:40.015237 I | pkg/flags: recognized and used environment variable ETCD_NAME=etcd1
2020-08-19 03:30:40.015246 I | pkg/flags: recognized and used environment variable ETCD_PEER_CERT_FILE=/etc/ssl/etcd/ssl/member-node1.pem
2020-08-19 03:30:40.015253 I | pkg/flags: recognized and used environment variable ETCD_PEER_CLIENT_CERT_AUTH=True
2020-08-19 03:30:40.015262 I | pkg/flags: recognized and used environment variable ETCD_PEER_KEY_FILE=/etc/ssl/etcd/ssl/member-node1-key.pem
2020-08-19 03:30:40.015269 I | pkg/flags: recognized and used environment variable ETCD_PEER_TRUSTED_CA_FILE=/etc/ssl/etcd/ssl/ca.pem
2020-08-19 03:30:40.015275 I | pkg/flags: recognized and used environment variable ETCD_PROXY=off
2020-08-19 03:30:40.015286 I | pkg/flags: recognized and used environment variable ETCD_QUOTA_BACKEND_BYTES=4294967296
2020-08-19 03:30:40.015294 I | pkg/flags: recognized and used environment variable ETCD_SNAPSHOT_COUNT=10000
2020-08-19 03:30:40.015302 I | pkg/flags: recognized and used environment variable ETCD_TRUSTED_CA_FILE=/etc/ssl/etcd/ssl/ca.pem
2020-08-19 03:30:40.015354 I | etcdmain: etcd Version: 3.3.10
2020-08-19 03:30:40.015366 I | etcdmain: Git SHA: 27fc7e2
2020-08-19 03:30:40.015370 I | etcdmain: Go Version: go1.10.4
2020-08-19 03:30:40.015375 I | etcdmain: Go OS/Arch: linux/amd64
2020-08-19 03:30:40.015380 I | etcdmain: setting maximum number of CPUs to 16, total number of available CPUs is 16
2020-08-19 03:30:40.015465 W | etcdmain: found invalid file/dir .bash_logout under data dir /var/lib/etcd (Ignore this if you are upgrading etcd)
2020-08-19 03:30:40.015475 W | etcdmain: found invalid file/dir .bash_profile under data dir /var/lib/etcd (Ignore this if you are upgrading etcd)
2020-08-19 03:30:40.015480 W | etcdmain: found invalid file/dir .bashrc under data dir /var/lib/etcd (Ignore this if you are upgrading etcd)
2020-08-19 03:30:40.015493 N | etcdmain: the server is already initialized as member before, starting as etcd member...
2020-08-19 03:30:40.015542 I | embed: peerTLS: cert = /etc/ssl/etcd/ssl/member-node1.pem, key = /etc/ssl/etcd/ssl/member-node1-key.pem, ca = , trusted-ca = /etc/ssl/etcd/ssl/ca.pem, client-cert-auth = true, crl-file = 
2020-08-19 03:30:40.016454 I | embed: listening for peers on https://192.168.1.2:2380
2020-08-19 03:30:40.016509 I | embed: listening for client requests on 127.0.0.1:2379
2020-08-19 03:30:40.016547 I | embed: listening for client requests on 192.168.1.2:2379
2020-08-19 03:30:40.021397 I | etcdserver: recovered store from snapshot at index 57425989
2020-08-19 03:30:40.026305 C | etcdserver: recovering backend from snapshot error: database snapshot file path error: snap: snapshot file doesn't exist
panic: recovering backend from snapshot error: database snapshot file path error: snap: snapshot file doesn't exist
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xb8cb90]

goroutine 1 [running]:
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver.NewServer.func1(0xc4202c7ca0, 0xc4202c7758)
	/tmp/etcd-release-3.3.10/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/server.go:291 +0x40
panic(0xde0ce0, 0xc420640030)
	/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/coreos/etcd/cmd/vendor/github.com/coreos/pkg/capnslog.(*PackageLogger).Panicf(0xc420222ac0, 0xfe8789, 0x2a, 0xc4202c77f8, 0x1, 0x1)
	/tmp/etcd-release-3.3.10/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/pkg/capnslog/pkg_logger.go:75 +0x162
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver.NewServer(0xc42003401a, 0x5, 0x0, 0x0, 0x0, 0x0, 0xc4202bc980, 0x1, 0x1, 0xc4202bca80, ...)
	/tmp/etcd-release-3.3.10/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/server.go:386 +0x26bb
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/embed.StartEtcd(0xc420346000, 0xc420346480, 0x0, 0x0)
	/tmp/etcd-release-3.3.10/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/embed/etcd.go:179 +0x811
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain.startEtcd(0xc420346000, 0xfc62b7, 0x6, 0xc4202c8d01, 0x2)
	/tmp/etcd-release-3.3.10/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain/etcd.go:181 +0x40
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain.startEtcdOrProxyV2()
	/tmp/etcd-release-3.3.10/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain/etcd.go:102 +0x1369
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain.Main()
	/tmp/etcd-release-3.3.10/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain/main.go:46 +0x3f
main.main()
	/tmp/etcd-release-3.3.10/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/etcd/main.go:28 +0x20
2020-08-19 03:30:40.927421 I | pkg/flags: recognized and used environment variable ETCD_ADVERTISE_CLIENT_URLS=https://192.168.1.2:2379
2020-08-19 03:30:40.927507 I | pkg/flags: recognized and used environment variable ETCD_AUTO_COMPACTION_RETENTION=8
2020-08-19 03:30:40.927520 I | pkg/flags: recognized and used environment variable ETCD_CERT_FILE=/etc/ssl/etcd/ssl/member-node1.pem
2020-08-19 03:30:40.927530 I | pkg/flags: recognized and used environment variable ETCD_CLIENT_CERT_AUTH=true
2020-08-19 03:30:40.927551 I | pkg/flags: recognized and used environment variable ETCD_DATA_DIR=/var/lib/etcd
2020-08-19 03:30:40.927570 I | pkg/flags: recognized and used environment variable ETCD_ELECTION_TIMEOUT=5000
2020-08-19 03:30:40.927590 I | pkg/flags: recognized and used environment variable ETCD_HEARTBEAT_INTERVAL=250
2020-08-19 03:30:40.927606 I | pkg/flags: recognized and used environment variable ETCD_INITIAL_ADVERTISE_PEER_URLS=https://192.168.1.2:2380
2020-08-19 03:30:40.927618 I | pkg/flags: recognized and used environment variable ETCD_INITIAL_CLUSTER=etcd1=https://192.168.1.2:2380
2020-08-19 03:30:40.927626 I | pkg/flags: recognized and used environment variable ETCD_INITIAL_CLUSTER_STATE=existing
2020-08-19 03:30:40.927640 I | pkg/flags: recognized and used environment variable ETCD_INITIAL_CLUSTER_TOKEN=k8s_etcd
2020-08-19 03:30:40.927649 I | pkg/flags: recognized and used environment variable ETCD_KEY_FILE=/etc/ssl/etcd/ssl/member-node1-key.pem
2020-08-19 03:30:40.927664 I | pkg/flags: recognized and used environment variable ETCD_LISTEN_CLIENT_URLS=https://192.168.1.2:2379,https://127.0.0.1:2379
2020-08-19 03:30:40.927682 I | pkg/flags: recognized and used environment variable ETCD_LISTEN_PEER_URLS=https://192.168.1.2:2380
2020-08-19 03:30:40.927699 I | pkg/flags: recognized and used environment variable ETCD_METRICS=basic
2020-08-19 03:30:40.927709 I | pkg/flags: recognized and used environment variable ETCD_NAME=etcd1
2020-08-19 03:30:40.927722 I | pkg/flags: recognized and used environment variable ETCD_PEER_CERT_FILE=/etc/ssl/etcd/ssl/member-node1.pem
2020-08-19 03:30:40.927731 I | pkg/flags: recognized and used environment variable ETCD_PEER_CLIENT_CERT_AUTH=True
2020-08-19 03:30:40.927742 I | pkg/flags: recognized and used environment variable ETCD_PEER_KEY_FILE=/etc/ssl/etcd/ssl/member-node1-key.pem
2020-08-19 03:30:40.927750 I | pkg/flags: recognized and used environment variable ETCD_PEER_TRUSTED_CA_FILE=/etc/ssl/etcd/ssl/ca.pem
2020-08-19 03:30:40.927758 I | pkg/flags: recognized and used environment variable ETCD_PROXY=off
2020-08-19 03:30:40.927773 I | pkg/flags: recognized and used environment variable ETCD_QUOTA_BACKEND_BYTES=4294967296
2020-08-19 03:30:40.927783 I | pkg/flags: recognized and used environment variable ETCD_SNAPSHOT_COUNT=10000
2020-08-19 03:30:40.927795 I | pkg/flags: recognized and used environment variable ETCD_TRUSTED_CA_FILE=/etc/ssl/etcd/ssl/ca.pem
2020-08-19 03:30:40.927861 I | etcdmain: etcd Version: 3.3.10
2020-08-19 03:30:40.927873 I | etcdmain: Git SHA: 27fc7e2
2020-08-19 03:30:40.927879 I | etcdmain: Go Version: go1.10.4
2020-08-19 03:30:40.927886 I | etcdmain: Go OS/Arch: linux/amd64
2020-08-19 03:30:40.927893 I | etcdmain: setting maximum number of CPUs to 16, total number of available CPUs is 16
2020-08-19 03:30:40.927988 W | etcdmain: found invalid file/dir .bash_logout under data dir /var/lib/etcd (Ignore this if you are upgrading etcd)
2020-08-19 03:30:40.927998 W | etcdmain: found invalid file/dir .bash_profile under data dir /var/lib/etcd (Ignore this if you are upgrading etcd)
2020-08-19 03:30:40.928005 W | etcdmain: found invalid file/dir .bashrc under data dir /var/lib/etcd (Ignore this if you are upgrading etcd)
2020-08-19 03:30:40.928019 N | etcdmain: the server is already initialized as member before, starting as etcd member...
2020-08-19 03:30:40.928066 I | embed: peerTLS: cert = /etc/ssl/etcd/ssl/member-node1.pem, key = /etc/ssl/etcd/ssl/member-node1-key.pem, ca = , trusted-ca = /etc/ssl/etcd/ssl/ca.pem, client-cert-auth = true, crl-file = 
2020-08-19 03:30:40.929096 I | embed: listening for peers on https://192.168.1.2:2380
2020-08-19 03:30:40.929155 I | embed: listening for client requests on 127.0.0.1:2379
2020-08-19 03:30:40.929192 I | embed: listening for client requests on 192.168.1.2:2379
2020-08-19 03:30:40.934553 I | etcdserver: recovered store from snapshot at index 57425989
2020-08-19 03:30:40.939524 C | etcdserver: recovering backend from snapshot error: database snapshot file path error: snap: snapshot file doesn't exist
panic: recovering backend from snapshot error: database snapshot file path error: snap: snapshot file doesn't exist
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xb8cb90]

goroutine 1 [running]:
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver.NewServer.func1(0xc4202b7ca0, 0xc4202b7758)
	/tmp/etcd-release-3.3.10/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/server.go:291 +0x40
panic(0xde0ce0, 0xc4200b8260)
	/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/coreos/etcd/cmd/vendor/github.com/coreos/pkg/capnslog.(*PackageLogger).Panicf(0xc42027c8e0, 0xfe8789, 0x2a, 0xc4202b77f8, 0x1, 0x1)
	/tmp/etcd-release-3.3.10/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/pkg/capnslog/pkg_logger.go:75 +0x162
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver.NewServer(0xc42003401a, 0x5, 0x0, 0x0, 0x0, 0x0, 0xc4202a6a80, 0x1, 0x1, 0xc4202a6b80, ...)
	/tmp/etcd-release-3.3.10/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/server.go:386 +0x26bb
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/embed.StartEtcd(0xc420344000, 0xc420344480, 0x0, 0x0)
	/tmp/etcd-release-3.3.10/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/embed/etcd.go:179 +0x811
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain.startEtcd(0xc420344000, 0xfc62b7, 0x6, 0xc4202b8d01, 0x2)
	/tmp/etcd-release-3.3.10/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain/etcd.go:181 +0x40
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain.startEtcdOrProxyV2()
	/tmp/etcd-release-3.3.10/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain/etcd.go:102 +0x1369
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain.Main()
	/tmp/etcd-release-3.3.10/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain/main.go:46 +0x3f
main.main()
	/tmp/etcd-release-3.3.10/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/etcd/main.go:28 +0x20
[root@node1 ~]# 

```

### 4. snapshot, wal, db files about etcd:
```
[root@node1 snap]# ll
total 13428
-rw-r--r--  1 root root     9243 Aug  8 22:19 0000000000000008-00000000036ba401.snap
-rw-r--r--  1 root root     9243 Aug  8 22:38 0000000000000008-00000000036bcb12.snap
-rw-r--r--  1 root root     9243 Aug  8 22:57 0000000000000008-00000000036bf223.snap
-rw-r--r--  1 root root     9243 Aug  8 23:16 0000000000000008-00000000036c1934.snap
-rw-r--r--  1 root root     9243 Aug  8 23:35 0000000000000008-00000000036c4045.snap
-rw-------. 1 root root 13684736 Aug 19 11:28 db

[root@node1 wal]# ll
total 375016
-rw------- 1 root root 64000776 Aug  8 16:07 000000000000035a-000000000367a171.wal
-rw------- 1 root root 64001632 Aug  8 18:12 000000000000035b-000000000368a283.wal
-rw------- 1 root root 64000920 Aug  8 20:16 000000000000035c-000000000369a398.wal
-rw------- 1 root root 64001768 Aug  8 22:20 000000000000035d-00000000036aa4a8.wal
-rw------- 1 root root 64000000 Aug  8 23:50 000000000000035e-00000000036ba5bb.wal
-rw------- 1 root root 64000000 Aug  8 22:20 0.tmp
```

- The point at which I am stuck is snapshot file doesn't exist. I'm not sure if the snapshot file is broken.
- The single etcd server did not have "*.snap.db" for recovering, and why the etcd server always tries to find the  *.snap.db of snapshot.
- This single etcd server didn't have backup data, so I only clear all data-dir files to restart the etcd server. It is not suitable for production environment.

**Comment by mamiapatrick** [comment]
Hello @bingerambo 
I'm struggling with the same issue since several days. Did you find any solution?? Hope that someone help us
