### ISSUE TITLE
etcd 3.4.13: segmentation violation on etcd shutdown

### ISSUE THREAD

**Issue by mborsz** [etcd-io/etcd#12441]
The etcd process has been killed by kubelet's health check mechanism, but segmentation violation shouldn't happen anyway:

```
2020-11-02 00:11:37.138496 W | etcdserver: read-only range request "key:\"/registry/events/kube-system/etcd-server-events-gce-scale-cluster-master.1643886980c61776\" " with result "range_response_count:1 size:873" took too long (8.135828734s) to execute
2020-11-02 00:11:38.984288 W | etcdserver/api/etcdhttp: /health error; QGET failed etcdserver: request timed out (status code 503)
2020-11-02 00:11:39.006595 N | pkg/osutil: received terminated signal, shutting down...
WARNING: 2020/11/02 00:11:39 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/11/02 00:11:39 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/11/02 00:11:39 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/11/02 00:11:39 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/11/02 00:11:39 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/11/02 00:11:39 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/11/02 00:11:39 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/11/02 00:11:39 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/11/02 00:11:39 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/11/02 00:11:39 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/11/02 00:11:39 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/11/02 00:11:39 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/11/02 00:11:39 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/11/02 00:11:39 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/11/02 00:11:39 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/11/02 00:11:39 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/11/02 00:11:39 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/11/02 00:11:39 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/11/02 00:11:39 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/11/02 00:11:39 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/11/02 00:11:39 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/11/02 00:11:39 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/11/02 00:11:39 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/11/02 00:11:39 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/11/02 00:11:39 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/11/02 00:11:39 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/11/02 00:11:39 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/11/02 00:11:39 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/11/02 00:11:39 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/11/02 00:11:39 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/11/02 00:11:39 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/11/02 00:11:39 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/11/02 00:11:39 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/11/02 00:11:39 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/11/02 00:11:39 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/11/02 00:11:39 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/11/02 00:11:39 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/11/02 00:11:39 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/11/02 00:11:39 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/11/02 00:11:39 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/11/02 00:11:39 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/11/02 00:11:39 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/11/02 00:11:39 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/11/02 00:11:39 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/11/02 00:11:39 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/11/02 00:11:39 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/11/02 00:11:39 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
2020-11-02 00:11:39.008788 I | etcdserver: skipped leadership transfer for single voting member cluster
WARNING: 2020/11/02 00:11:39 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/11/02 00:11:39 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/11/02 00:11:39 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/11/02 00:11:39 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/11/02 00:11:39 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/11/02 00:11:39 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/11/02 00:11:39 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
2020-11-02 00:11:39.008992 W | etcdserver: read-only range request "key:\"/registry/events/test-wnkup6-12/big-service-0.1643886b5ec6327d\" " with result "error:context canceled" took too long (4.968040357s) to execute
2020-11-02 00:11:39.009031 W | etcdserver: read-only range request "key:\"/registry/events/test-wnkup6-49/medium-service-2.16438866ee73ad48\" " with result "error:context canceled" took too long (3.450527005s) to execute
WARNING: 2020/11/02 00:11:39 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
WARNING: 2020/11/02 00:11:39 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing"
2020-11-02 00:11:39.146220 W | etcdserver: request "header:<ID:4165114449061124701 > txn:<compare:<target:MOD key:\"/registry/events/test-wnkup6-12/big-deployment-0-76677bd886-sw98q.1643886aba1dc853\" mod_revision:0 > success:<request_put:<key:\"/registry/events/test-wnkup6-12/big-deployment-0-76677bd886-sw98q.1643886aba1dc853\" value_size:753 lease:4165114449061116461 >> failure:<>>" with result "size:18" took too long (100.896215ms) to execute
2020-11-02 00:11:39.991807 W | etcdserver: request "header:<ID:4165114449061124775 > txn:<compare:<target:MOD key:\"/registry/events/test-wnkup6-12/big-deployment-0-76677bd886-csrzd.16438869c849abdf\" mod_revision:0 > success:<request_put:<key:\"/registry/events/test-wnkup6-12/big-deployment-0-76677bd886-csrzd.16438869c849abdf\" value_size:753 lease:4165114449061116461 >> failure:<>>" with result "size:18" took too long (118.846804ms) to execute
2020-11-02 00:11:40.738733 W | etcdserver: request "header:<ID:4165114449061124837 > txn:<compare:<target:MOD key:\"/registry/events/test-wnkup6-2/small-deployment-261-9695cbd7b-krxxj.1643886a0043eeb6\" mod_revision:0 > success:<request_put:<key:\"/registry/events/test-wnkup6-2/small-deployment-261-9695cbd7b-krxxj.1643886a0043eeb6\" value_size:765 lease:4165114449061116461 >> failure:<>>" with result "size:18" took too long (142.587292ms) to execute
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8a640e]

goroutine 323 [running]:
go.etcd.io/bbolt.(*Tx).Bucket(...)
        /home/ANT.AMAZON.COM/leegyuho/go/pkg/mod/go.etcd.io/bbolt@v1.3.3/tx.go:101
go.etcd.io/etcd/mvcc/backend.(*concurrentReadTx).UnsafeRange(0xc02bf8faa0, 0x1a6906a, 0x3, 0x3, 0xc015540160, 0x11, 0x12, 0x0, 0x0, 0x0, ...)
        /tmp/etcd-release-3.4.13/etcd/release/etcd/mvcc/backend/read_tx.go:195 +0x67e
go.etcd.io/etcd/mvcc.(*storeTxnRead).rangeKeys(0xc02bf8fb30, 0xc022f30be0, 0x4f, 0x50, 0x0, 0x0, 0x0, 0xc8976, 0x0, 0xc7e93, ...)
        /tmp/etcd-release-3.4.13/etcd/release/etcd/mvcc/kvstore_txn.go:147 +0x29e
go.etcd.io/etcd/mvcc.(*storeTxnRead).Range(0xc02bf8fb30, 0xc022f30be0, 0x4f, 0x50, 0x0, 0x0, 0x0, 0x0, 0xc7e93, 0x8a4e00, ...)
        /tmp/etcd-release-3.4.13/etcd/release/etcd/mvcc/kvstore_txn.go:51 +0xb0
go.etcd.io/etcd/mvcc.(*metricsTxnWrite).Range(0xc02bf8fbf0, 0xc022f30be0, 0x4f, 0x50, 0x0, 0x0, 0x0, 0x0, 0xc7e93, 0xfee900, ...)
        /tmp/etcd-release-3.4.13/etcd/release/etcd/mvcc/metrics_txn.go:37 +0xaf
go.etcd.io/etcd/mvcc.(*readView).Range(0xc000268000, 0xc022f30be0, 0x4f, 0x50, 0x0, 0x0, 0x0, 0x0, 0xc7e93, 0x84000, ...)
        /tmp/etcd-release-3.4.13/etcd/release/etcd/mvcc/kv_view.go:39 +0x125
go.etcd.io/etcd/etcdserver/api/v3rpc.(*serverWatchStream).sendLoop(0xc00018c600)
        /tmp/etcd-release-3.4.13/etcd/release/etcd/etcdserver/api/v3rpc/watch.go:395 +0x1da
go.etcd.io/etcd/etcdserver/api/v3rpc.(*watchServer).Watch.func1(0xc00018c600)
        /tmp/etcd-release-3.4.13/etcd/release/etcd/etcdserver/api/v3rpc/watch.go:180 +0x2b
created by go.etcd.io/etcd/etcdserver/api/v3rpc.(*watchServer).Watch
        /tmp/etcd-release-3.4.13/etcd/release/etcd/etcdserver/api/v3rpc/watch.go:179 +0x275
```

Full logs: https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/1323037480215121920/artifacts/gce-scale-cluster-master/etcd-events.log

**Comment by cfc4n** [comment]
> /cc @ptabor

Can you give a demo to reproduce it ?

**Comment by mborsz** [comment]
I guess it may be hard to reproduce. Logs is all we have.

**Comment by pacoxu** [comment]
https://github.com/kubernetes/kubernetes/issues/98784 is the same issue according to the trace.
Kuberenetes is use 3.4.13 as well.

**Comment by dims** [comment]
still happening : https://github.com/kubernetes/kubernetes/issues/98784#issuecomment-787495451
