### ISSUE TITLE
Panic with nil pointer dereference inside (*Session.Orphan)

### ISSUE THREAD

**Issue by christarazi** [etcd-io/etcd#12643]
Seen on version v3.4.14. I don't have any reproduction steps as this was observed in a staging environment. I have an idea on what triggers it: there was a policy in-place blocking traffic *coming from* etcd, but traffic *going to* etcd was allowed.

Let me know if I can provide any more information. 

```
2021-01-21T20:46:46.099242000Z panic: runtime error: invalid memory address or nil pointer dereference
2021-01-21T20:46:46.099863000Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x19c2eea]
2021-01-21T20:46:46.099996000Z goroutine 472 [running]:
2021-01-21T20:46:46.100057000Z go.etcd.io/etcd/clientv3/concurrency.(*Session).Orphan(...)
2021-01-21T20:46:46.100098000Z 	/go/src/github.com/cilium/cilium/vendor/go.etcd.io/etcd/clientv3/concurrency/session.go:90
2021-01-21T20:46:46.100137000Z go.etcd.io/etcd/clientv3/concurrency.(*Session).Close(0xc000fd0180, 0xc002b24120, 0x2)
2021-01-21T20:46:46.100176000Z 	/go/src/github.com/cilium/cilium/vendor/go.etcd.io/etcd/clientv3/concurrency/session.go:96 +0x2a
2021-01-21T20:46:46.100224000Z github.com/cilium/cilium/pkg/kvstore.(*etcdClient).Close(0xc000239ef0)
2021-01-21T20:46:46.100269000Z 	/go/src/github.com/cilium/cilium/pkg/kvstore/etcd.go:1653 +0xc8
2021-01-21T20:46:46.100308000Z github.com/cilium/cilium/pkg/clustermesh.(*remoteCluster).restartRemoteConnection.func1(0x2b1e500, 0xc0003f2e40, 0x3c61c00, 0x0)
2021-01-21T20:46:46.100348000Z 	/go/src/github.com/cilium/cilium/pkg/clustermesh/remote_cluster.go:178 +0x40c
2021-01-21T20:46:46.100389000Z github.com/cilium/cilium/pkg/controller.(*Controller).runController(0xc00084d300)
2021-01-21T20:46:46.100428000Z 	/go/src/github.com/cilium/cilium/pkg/controller/controller.go:205 +0xa77
2021-01-21T20:46:46.100480000Z created by github.com/cilium/cilium/pkg/controller.(*Manager).updateController
2021-01-21T20:46:46.100523000Z 	/go/src/github.com/cilium/cilium/pkg/controller/manager.go:120 +0xb50
```

**Comment by xiang90** [comment]
@christarazi 

Is 3.4.14 the client version?

**Comment by christarazi** [comment]
@xiang90 Yes
