### ISSUE TITLE
Etcd crash under many txn and lock requests

### ISSUE THREAD

**Issue by sighingnow** [etcd-io/etcd#12672]
We have encounter a crash when working with etcd 3.4.13 (from the quay.io/coreos/etcd image).

It is not easy to provide a script for reproduce, but since it is a crash I think the backtrace could help as well:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8a640e]

goroutine 9041 [running]:
go.etcd.io/bbolt.(*Tx).Bucket(...)
        /home/ANT.AMAZON.COM/leegyuho/go/pkg/mod/go.etcd.io/bbolt@v1.3.3/tx.go:101
go.etcd.io/etcd/mvcc/backend.(*concurrentReadTx).UnsafeRange(0xc0016f6ae0, 0x1a6906a, 0x3, 0x3, 0xc00303f160, 0x11, 0x12, 0x0, 0x0, 0x0, ...)
        /tmp/etcd-release-3.4.13/etcd/release/etcd/mvcc/backend/read_tx.go:195 +0x67e
go.etcd.io/etcd/mvcc.(*storeTxnRead).rangeKeys(0xc0016f6b10, 0xc001166aa0, 0x1f, 0x20, 0x0, 0x0, 0x0, 0x57a, 0x0, 0x56b, ...)
        /tmp/etcd-release-3.4.13/etcd/release/etcd/mvcc/kvstore_txn.go:147 +0x29e
go.etcd.io/etcd/mvcc.(*storeTxnRead).Range(0xc0016f6b10, 0xc001166aa0, 0x1f, 0x20, 0x0, 0x0, 0x0, 0x0, 0x56b, 0x8a4e00, ...)
        /tmp/etcd-release-3.4.13/etcd/release/etcd/mvcc/kvstore_txn.go:51 +0xb0
go.etcd.io/etcd/mvcc.(*metricsTxnWrite).Range(0xc0016f6c00, 0xc001166aa0, 0x1f, 0x20, 0x0, 0x0, 0x0, 0x0, 0x56b, 0xfee900, ...)
        /tmp/etcd-release-3.4.13/etcd/release/etcd/mvcc/metrics_txn.go:37 +0xaf
go.etcd.io/etcd/mvcc.(*readView).Range(0xc0002200d0, 0xc001166aa0, 0x1f, 0x20, 0x0, 0x0, 0x0, 0x0, 0x56b, 0x400, ...)
        /tmp/etcd-release-3.4.13/etcd/release/etcd/mvcc/kv_view.go:39 +0x125
go.etcd.io/etcd/etcdserver/api/v3rpc.(*serverWatchStream).sendLoop(0xc0025b2c00)
        /tmp/etcd-release-3.4.13/etcd/release/etcd/etcdserver/api/v3rpc/watch.go:395 +0x1da
go.etcd.io/etcd/etcdserver/api/v3rpc.(*watchServer).Watch.func1(0xc0025b2c00)
        /tmp/etcd-release-3.4.13/etcd/release/etcd/etcdserver/api/v3rpc/watch.go:180 +0x2b
created by go.etcd.io/etcd/etcdserver/api/v3rpc.(*watchServer).Watch
        /tmp/etcd-release-3.4.13/etcd/release/etcd/etcdserver/api/v3rpc/watch.go:179 +0x275
```

Before crashing, there are many txn/lease failure and etcd server responses very slow. There is only one etcd server in our cluster.

**Comment by xiang90** [comment]
@ptabor @gyuho @wilsonwang371 

Are you aware of this? Seems like a bug.

**Comment by wilsonwang371** [comment]
Is this because of a nil baseReadTx.tx pointer in transactions?

**Comment by wilsonwang371** [comment]
@sighingnow Do you have more information about this failure? Such as other error messages a few seconds before this failure.

**Comment by sighingnow** [comment]
I didn't keep a log but I could reproduce it later.

More information I can tell:

+ there's only one etcd server, runs on kubernetes as a pod
+ before crash, there are many request pattern like "lease grant -> keep alive -> lock -> watch -> txn -> lease revoke -> unlock", and from the log we have observed many warnings like "take too long to execute".
+ after we increase the CPU cores from `2` to `24` the panic disappear under our workload.
+ mounting a `medium: Memory` volume to pod's `/dev/shm` and then changing the datadir to `/dev/shm/data.dir` doesn't help

I would paste the log here once I reproduces the error.

**Comment by wilsonwang371** [comment]
> I didn't keep a log but I could reproduce it later.
> 
> More information I can tell:
> 
> * there's only one etcd server, runs on kubernetes as a pod
> * before crash, there are many request pattern like "lease grant -> keep alive -> lock -> watch -> txn -> lease revoke -> unlock", and from the log we have observed many warnings like "take too long to execute".
> * after we increase the CPU cores from `2` to `24` the panic disappear under our workload.
> * mounting a `medium: Memory` volume to pod's `/dev/shm` and then changing the datadir to `/dev/shm/data.dir` doesn't help
> 
> I would paste the log here once I reproduces the error.

Do you just have 2 cores?

**Comment by sighingnow** [comment]
> Do you just have 2 cores?

2 cores it the cpu resource request in the pod spec. It might be 2 or 4, if I remember it correctly.

**Comment by wilsonwang371** [comment]
> > Do you just have 2 cores?
> 
> 2 cores it the cpu resource request in the pod spec. It might be 2 or 4, if I remember it correctly.

Ok, the number of cores is a little low. But there is nothing wrong with it. Let me know if you have more logs available.
