### ISSUE TITLE
panic: field raftpb.Entry.Type has invalid type: got raftpb.EntryType, want pointer

### ISSUE THREAD

**Issue by NamanJain8** [etcd-io/etcd#12834]
In [dgraph](https://github.com/dgraph-io/dgraph), we use etcd's raft. On a HA cluster, I was adding/removing the nodes. I faced the following crash. Note that the `golang/protobuf` is from version `v1.4.1` and not of `v1.2.0` as it was superseded by the higher version in dgraph's `go.mod`

How can this be fixed and is there any workaround for this as I feel like this might be some compatibility issue in the protobuf libraries?
```
W0406 14:15:00.235795      15 node.go:420] Unable to send message to peer: 0x4. Error: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: lookup alpha3 on 127.0.0.11:53: no such host"
W0406 14:15:09.739071      15 node.go:420] Unable to send message to peer: 0x4. Error: Unhealthy connection
W0406 14:15:19.839091      15 node.go:420] Unable to send message to peer: 0x4. Error: Unhealthy connection
W0406 14:15:29.939072      15 node.go:420] Unable to send message to peer: 0x4. Error: Unhealthy connection
W0406 14:15:30.840348      15 pool.go:130] DISCONNECTING from alpha3:7083
W0406 14:15:30.840360      15 pool.go:204] Shutting down extra connection to alpha3:7083
panic: field raftpb.Entry.Type has invalid type: got raftpb.EntryType, want pointer
goroutine 218 [running]:
google.golang.org/protobuf/internal/impl.fieldInfoForScalar(0x23a70c0, 0xc00624d180, 0x1ec8723, 0x4, 0x0, 0x0, 0x23a71e0, 0x1f3cb20, 0x1ec8729, 0x43, ...)
	/home/algod/go/pkg/mod/google.golang.org/protobuf@v1.25.0/internal/impl/message_reflect_field.go:228 +0x7d7
google.golang.org/protobuf/internal/impl.(*MessageInfo).makeKnownFieldsFunc(0xc000344b40, 0xffffffffffffffff, 0xffffffffffffffff, 0x30, 0xffffffffffffffff, 0xc00832b320, 0xc00832b350, 0xc00832b380, 0xc00832b3b0)
	/home/algod/go/pkg/mod/google.golang.org/protobuf@v1.25.0/internal/impl/message_reflect.go:67 +0x97d
google.golang.org/protobuf/internal/impl.(*MessageInfo).makeReflectFuncs(0xc000344b40, 0x23a71e0, 0x202fac0, 0xffffffffffffffff, 0xffffffffffffffff, 0x30, 0xffffffffffffffff, 0xc00832b320, 0xc00832b350, 0xc00832b380, ...)
	/home/algod/go/pkg/mod/google.golang.org/protobuf@v1.25.0/internal/impl/message_reflect.go:36 +0x65
google.golang.org/protobuf/internal/impl.(*MessageInfo).initOnce(0xc000344b40)
	/home/algod/go/pkg/mod/google.golang.org/protobuf@v1.25.0/internal/impl/message.go:90 +0x192
google.golang.org/protobuf/internal/impl.(*MessageInfo).init(...)
	/home/algod/go/pkg/mod/google.golang.org/protobuf@v1.25.0/internal/impl/message.go:72
google.golang.org/protobuf/internal/impl.(*messageReflectWrapper).Has(0xc0047b9a60, 0x23a70c0, 0xc00624d180, 0xc00624d180)
	/home/algod/go/pkg/mod/google.golang.org/protobuf@v1.25.0/internal/impl/message_reflect_gen.go:185 +0xf9
github.com/golang/protobuf/proto.(*textWriter).writeMessage(0xc00832b2f0, 0x239e860, 0xc0047b9a60, 0x0, 0x0)
	/home/algod/go/pkg/mod/github.com/golang/protobuf@v1.4.1/proto/text_encode.go:278 +0x935
github.com/golang/protobuf/proto.(*TextMarshaler).marshal(0x2cfda40, 0x237cdc0, 0xc0019c8cd0, 0xc00624e438, 0x1, 0x3, 0xb6e42a, 0xc00004f000)
	/home/algod/go/pkg/mod/github.com/golang/protobuf@v1.4.1/proto/text_encode.go:86 +0x190
github.com/golang/protobuf/proto.(*TextMarshaler).Text(...)
	/home/algod/go/pkg/mod/github.com/golang/protobuf@v1.4.1/proto/text_encode.go:44
github.com/golang/protobuf/proto.CompactTextString(...)
	/home/algod/go/pkg/mod/github.com/golang/protobuf@v1.4.1/proto/text_encode.go:106
go.etcd.io/etcd/raft/raftpb.(*Entry).String(...)
	/home/algod/go/pkg/mod/go.etcd.io/etcd@v0.0.0-20190228193606-a943ad0ee4c9/raft/raftpb/raft.pb.go:212
go.etcd.io/etcd/raft.stepLeader(0xc0003c2b40, 0x2, 0x0, 0x2, 0x0, 0x0, 0x0, 0xc001ef5720, 0x1, 0x1, ...)
	/home/algod/go/pkg/mod/go.etcd.io/etcd@v0.0.0-20190228193606-a943ad0ee4c9/raft/raft.go:1012 +0x290
go.etcd.io/etcd/raft.(*raft).Step(0xc0003c2b40, 0x2, 0x0, 0x2, 0x0, 0x0, 0x0, 0xc001ef5720, 0x1, 0x1, ...)
	/home/algod/go/pkg/mod/go.etcd.io/etcd@v0.0.0-20190228193606-a943ad0ee4c9/raft/raft.go:971 +0x1218
go.etcd.io/etcd/raft.(*node).run(0xc00064ed20, 0xc0003c2b40)
	/home/algod/go/pkg/mod/go.etcd.io/etcd@v0.0.0-20190228193606-a943ad0ee4c9/raft/node.go:349 +0x1258
created by go.etcd.io/etcd/raft.StartNode
	/home/algod/go/pkg/mod/go.etcd.io/etcd@v0.0.0-20190228193606-a943ad0ee4c9/raft/node.go:233 +0x449
W0406 14:15:30.864573       1 sentry_integration.go:140] unable to read CID from file /tmp/dgraph-alpha-cid-sentry open /tmp/dgraph-alpha-cid-sentry: no such file or directory. Skip
[Sentry] 2021/04/06 14:15:30 Sending fatal event [1641bf9717a140198db5887e6af588f8] to o318308.ingest.sentry.io project: 5208688
[Sentry] 2021/04/06 14:15:32 Buffer flushed successfully.
```

**Comment by ptabor** [comment]
Protobuf 1.4.x is not compatible with gogo-generated protos. 
There were some improvements in 1.5.1 protobuf runtime that enabled some basic compatiblity. 
Please upgrade protobuf runtime to 1.5.1.

**Comment by NamanJain8** [comment]
Thanks, @ptabor for resolving the query
