### ISSUE TITLE
signal SIGSEGV occurs after call clientv3/concurrency.(*Session).Orphan(...)

### ISSUE THREAD

**Issue by jiapeish** [etcd-io/etcd#12934]
### Issue Overview 
Hi,

I have found a possible bug related to clientv3.

### Steps to reproduce
- ETCD v3.4.10
- Go 1.14.8
- We repeat to run this piece of code: 
```go
        cctx, cancel := context.WithTimeout(ctx, 5 * time.Second)
	txnResp, err := c.client.Txn(cctx).If(cmp).Then(put).Else(get).Commit()
	cancel()
	if err != nil {
		c.session.Close() // this line trigger the panic !
		return err
	}
	if txnResp.Succeeded {
		c.sessionDonec = c.session.Done()
		c.leaderRev = txnResp.Header.Revision
	} else {
		c.session.Close()   
	}
```

### Log is here:
```shell
dockerlogs.log.4.gz:2021-05-07T23:53:33.110419+00:00|err|docker_918c2d75d1ce[25192]|{"level":"warn","ts":"2021-05-07T23:53:33.107Z","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-58147283-da49-48cf-ab35-b50c7a9ec707/176.158.0.116:2379","attempt":0,"error":"rpc error: code = Canceled desc = context canceled"}
dockerlogs.log.4.gz:2021-05-07T23:53:33.149618+00:00|err|docker_918c2d75d1ce[25192]|panic: runtime error: invalid memory address or nil pointer dereference
dockerlogs.log.4.gz:2021-05-07T23:53:33.149658+00:00|err|docker_918c2d75d1ce[25192]|[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1fcb8f6]
dockerlogs.log.4.gz:2021-05-07T23:53:33.149701+00:00|err|docker_918c2d75d1ce[25192]|
dockerlogs.log.4.gz:2021-05-07T23:53:33.149752+00:00|err|docker_918c2d75d1ce[25192]|goroutine 10411 [running]:
dockerlogs.log.4.gz:2021-05-07T23:53:33.149812+00:00|err|docker_918c2d75d1ce[25192]|etcdclient/vendor/go.etcd.io/etcd/clientv3/concurrency.(*Session).Orphan(...)
dockerlogs.log.4.gz:2021-05-07T23:53:33.149855+00:00|err|docker_918c2d75d1ce[25192]|#011/usr1/home/workspace/Master.98d70eb5.Package.gocell-hakit/.gogradle/project_gopath/src/etcdclient/vendor/go.etcd.io/etcd/clientv3/concurrency/session.go:90
dockerlogs.log.4.gz:2021-05-07T23:53:33.149901+00:00|err|docker_918c2d75d1ce[25192]|etcdclient/vendor/go.etcd.io/etcd/clientv3/concurrency.(*Session).Close(0x0, 0x0, 0x2bb8b80)
dockerlogs.log.4.gz:2021-05-07T23:53:33.149962+00:00|err|docker_918c2d75d1ce[25192]|#011/usr1/home/workspace/Master.98d70eb5.Package.gocell-hakit/.gogradle/project_gopath/src/etcdclient/vendor/go.etcd.io/etcd/clientv3/concurrency/session.go:96 +0x26
dockerlogs.log.4.gz:2021-05-07T23:53:33.150005+00:00|err|docker_918c2d75d1ce[25192]|etcdclient/vendor/haagent/agent/election.(*candidate).aquireLock(0xc001bae240, 0x2c06340, 0xc002b6a880, 0xc001ddfcd0, 0xc, 0x0, 0x0)
dockerlogs.log.4.gz:2021-05-07T23:53:33.150058+00:00|err|docker_918c2d75d1ce[25192]|#011/usr1/home/workspace/Master.98d70eb5.Package.gocell-hakit/.gogradle/project_gopath/src/etcdclient/vendor/haagent/agent/election/election.go:957 +0x703
dockerlogs.log.4.gz:2021-05-07T23:53:33.150103+00:00|err|docker_918c2d75d1ce[25192]|etcdclient/vendor/haagent/agent/election.(*candidate).lock(0xc001bae240, 0x2c06340, 0xc002b6a880, 0x1, 0x1)
dockerlogs.log.4.gz:2021-05-07T23:53:33.150142+00:00|err|docker_918c2d75d1ce[25192]|#011/usr1/home/workspace/Master.98d70eb5.Package.gocell-hakit/.gogradle/project_gopath/src/etcdclient/vendor/haagent/agent/election/election.go:931 +0x314
dockerlogs.log.4.gz:2021-05-07T23:53:33.150182+00:00|err|docker_918c2d75d1ce[25192]|etcdclient/vendor/haagent/agent/election.(*candidate).campaign(0xc001bae240, 0x2c06340, 0xc002b6a880)
dockerlogs.log.4.gz:2021-05-07T23:53:33.150219+00:00|err|docker_918c2d75d1ce[25192]|#011/usr1/home/workspace/Master.98d70eb5.Package.gocell-hakit/.gogradle/project_gopath/src/etcdclient/vendor/haagent/agent/election/election.go:892 +0x5d
dockerlogs.log.4.gz:2021-05-07T23:53:33.150261+00:00|err|docker_918c2d75d1ce[25192]|created by etcdclient/vendor/haagent/agent/election.(*candidate).createCampaign
dockerlogs.log.4.gz:2021-05-07T23:53:33.150300+00:00|err|docker_918c2d75d1ce[25192]|#011/usr1/home/workspace/Master.98d70eb5.Package.gocell-hakit/.gogradle/project_gopath/src/etcdclient/vendor/haagent/agent/election/election.go:887 +0x126
```

### What we expect
1. We expect that the panic should not be triggered even session.Close() is called not properly.
2. We're wondering why the  pointer becomes nil?

**Comment by jiapeish** [comment]
Closed, my code bugs...
