### ISSUE TITLE
etcd snapshot restore is failing  

### ISSUE THREAD

**Issue by PayalSasmal10** [etcd-io/etcd#13189]
Hi Team,

We have 2.6GB of AWS dynamodb data which we migrated in etcd format. We want to restore those data in the GCP etcd operator. We are using etcd bitnami helm version as CR and etcd operator.  while trying to restore with the command below command, we are getting error. The same way we can restore snapshot if we have less than 2 GB of data.
Could you please help us @geauxvirtual @hexfusion 

etcdctl snapshot restore /bitnami/etcd/snapshot/db  \
	 --data-dir /bitnami/etcd/data  \
	 --name etcdl  \
	 --initial-cluster "<IP>:2380"  \
	 --initial-cluster-token "<Token>" \
	 --initial-advertise-peer-urls <URL>:2380 \
	 --skip-hash-check=true

{"level":"info","ts":1625570287.9687092,"caller":"snapshot/v3_snapshot.go:287","msg":"restoring snapshot","path":"/bitnami/etcd/snapshot/db","wal-dir":"/bitnami/etcd/data/member/wal","data-dir":"/bitnami/etcd/data","snap-dir":"/bitnami/etcd/data/member/snap"}
unexpected fault address 0x7f2cd61ce008
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x7f2cd61ce008 pc=0x84d537]

goroutine 1 [running]:
runtime.throw(0xd45b2f, 0x5)
        /usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc0002f0dd8 sp=0xc0002f0da8 pc=0x42c862
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:387 +0x47e fp=0xc0002f0e08 sp=0xc0002f0dd8 pc=0x44144e
go.etcd.io/bbolt.(*freelist).read(0xc000262180, 0x7f2cd61ce000)
        /home/ANT.AMAZON.COM/leegyuho/go/pkg/mod/go.etcd.io/bbolt@v1.3.3/freelist.go:265 +0x37 fp=0xc0002f0e98 sp=0xc0002f0e08 pc=0x84d537
go.etcd.io/bbolt.(*DB).loadFreelist.func1()
        /home/ANT.AMAZON.COM/leegyuho/go/pkg/mod/go.etcd.io/bbolt@v1.3.3/db.go:316 +0xd1 fp=0xc0002f0ed0 sp=0xc0002f0e98 pc=0x857931
sync.(*Once).Do(0xc0003de168, 0xc0002f0f10)
        /usr/local/go/src/sync/once.go:44 +0xb3 fp=0xc0002f0f00 sp=0xc0002f0ed0 pc=0x46f483
go.etcd.io/bbolt.(*DB).loadFreelist(0xc0003de000)
        /home/ANT.AMAZON.COM/leegyuho/go/pkg/mod/go.etcd.io/bbolt@v1.3.3/db.go:309 +0x56 fp=0xc0002f0f30 sp=0xc0002f0f00 pc=0x8488a6
go.etcd.io/bbolt.Open(0xc0001d6930, 0x26, 0xc000000180, 0xc0002f11d8, 0xc0002f1048, 0xc0002f1058, 0x4355cf)
        /home/ANT.AMAZON.COM/leegyuho/go/pkg/mod/go.etcd.io/bbolt@v1.3.3/db.go:286 +0x326 fp=0xc0002f0ff0 sp=0xc0002f0f30 pc=0x848376
go.etcd.io/etcd/mvcc/backend.newBackend(0xc0001d6930, 0x26, 0x5f5e100, 0x2710, 0x0, 0x0, 0x280000000, 0x0, 0x0)
        /tmp/etcd-release-3.4.7/etcd/release/etcd/mvcc/backend/backend.go:154 +0xfe fp=0xc0002f1238 sp=0xc0002f0ff0 pc=0x87cbfe
go.etcd.io/etcd/mvcc/backend.NewDefaultBackend(...)
        /tmp/etcd-release-3.4.7/etcd/release/etcd/mvcc/backend/backend.go:143
go.etcd.io/etcd/clientv3/snapshot.(*v3Manager).saveDB(0xc000138a80, 0x0, 0x0)
        /tmp/etcd-release-3.4.7/etcd/release/etcd/clientv3/snapshot/v3_snapshot.go:382 +0x463 fp=0xc0002f13d0 sp=0xc0002f1238 pc=0xb3fe33
go.etcd.io/etcd/clientv3/snapshot.(*v3Manager).Restore(0xc000138a80, 0x7ffcd8b5b3b8, 0x19, 0x7ffcd8b5b3d9, 0xc, 0x7ffcd8b5b5e1, 0x17, 0xc0001d66c0, 0x22, 0xc0001c6b10, ...)
        /tmp/etcd-release-3.4.7/etcd/release/etcd/clientv3/snapshot/v3_snapshot.go:294 +0x89b fp=0xc0002f1b98 sp=0xc0002f13d0 pc=0xb3efdb
go.etcd.io/etcd/etcdctl/ctlv3/command.snapshotRestoreCommandFunc(0xc00030f180, 0xc0001f0180, 0x1, 0xc)
        /tmp/etcd-release-3.4.7/etcd/release/etcd/etcdctl/ctlv3/command/snapshot_command.go:160 +0x2a5 fp=0xc0002f1d30 sp=0xc0002f1b98 pc=0xb6a6c5
github.com/spf13/cobra.(*Command).execute(0xc00030f180, 0xc0001f00c0, 0xc, 0xc, 0xc00030f180, 0xc0001f00c0)
        /home/ANT.AMAZON.COM/leegyuho/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2ae fp=0xc0002f1e18 sp=0xc0002f1d30 pc=0xab99fe
github.com/spf13/cobra.(*Command).ExecuteC(0x14b8240, 0xb, 0xc000168b20, 0xb7f801)
        /home/ANT.AMAZON.COM/leegyuho/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ec fp=0xc0002f1ee8 sp=0xc0002f1e18 pc=0xaba64c
github.com/spf13/cobra.(*Command).Execute(...)
        /home/ANT.AMAZON.COM/leegyuho/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
go.etcd.io/etcd/etcdctl/ctlv3.Start()
        /tmp/etcd-release-3.4.7/etcd/release/etcd/etcdctl/ctlv3/ctl_nocov.go:25 +0x81 fp=0xc0002f1f18 sp=0xc0002f1ee8 pc=0xb7f6c1
main.main()
        /tmp/etcd-release-3.4.7/etcd/release/etcd/etcdctl/main.go:35 +0x77 fp=0xc0002f1f98 sp=0xc0002f1f18 pc=0xb809b7
runtime.main()
        /usr/local/go/src/runtime/proc.go:200 +0x20c fp=0xc0002f1fe0 sp=0xc0002f1f98 pc=0x42e1cc
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc0002f1fe8 sp=0xc0002f1fe0 pc=0x459211

goroutine 11 [syscall]:
os/signal.signal_recv(0x459216)
        /usr/local/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
        /usr/local/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 81 [chan receive]:
go.etcd.io/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc0001c54a0)
        /tmp/etcd-release-3.4.7/etcd/release/etcd/pkg/logutil/merge_logger.go:173 +0x3a2
created by go.etcd.io/etcd/pkg/logutil.NewMergeLogger
        /tmp/etcd-release-3.4.7/etcd/release/etcd/pkg/logutil/merge_logger.go:91 +0x80

**Comment by raindylong** [comment]
How about to start the etcd daemon with "--quota-backend-bytes 8943040000"? It's to configure the dbszie to 8G because your snapshot is 2.6G.

**Comment by PayalSasmal10** [comment]
Hi @raindylong,

Thank you so much for your quick response.

I have checked this flag but not sure where to place that. We are using https://github.com/bitnami/charts/tree/master/bitnami/etcd. 

Could you please provide us few links which we can follow?

**Comment by MakDon** [comment]
> How about to start the etcd daemon with "--quota-backend-bytes 8943040000"? It's to configure the dbszie to 8G because your snapshot is 2.6G.

Following the [code](https://github.com/etcd-io/bbolt/blob/master/db.go#L347), we could see that if the file's size is greater than the `options.InitialMmapSize`, the file's size would be used.
So maybe this problem is not caused by the `quota-backend-bytes`. But it's still worth trying to run with `--quota-backend-bytes 8943040000` becasue "we can restore snapshots if we have less than 2 GB of data."

This issue occurs when trying to read freelist page from the snapshot.
When loading the bbolt db, it tries to read from the freelist page, first by mmap the file, and then read the freelist page associated with the pageid in meta page.
But the address of the page seems to be too large, which is `0x7f2cd61ce000`, and seems to be overfloated:
`go.etcd.io/bbolt.(*freelist).read(0xc000262180, 0x7f2cd61ce000)`
And it panic when trying to access this address.

Could you try restore the snapshot on another platform like an etcd cluster installed on your local machine?

And could you copy and paste the meta of the bbolt? This is store in the first page, the first 4 KB of the file by default. It includes [these info](https://github.com/etcd-io/bbolt/blob/master/db.go#L1172).

I am new at etcd and bbolt. If these's anything not correct, plz point it out. Thanks.
