### ISSUE TITLE
WARNING: DATA RACE on TestWatchOverlapDropConnContextCancel

### ISSUE THREAD

**Issue by ahrtr** [etcd-io/etcd#14003]
```

WARNING: DATA RACE
Write at 0x00c0000e0d28 by goroutine 461:
  go.etcd.io/etcd/tests/v3/framework/integration.(*Member).Close()
      /home/runner/work/etcd/etcd/tests/framework/integration/cluster.go:1131 +0x98
  go.etcd.io/etcd/tests/v3/framework/integration.(*Member).Terminate()
      /home/runner/work/etcd/etcd/tests/framework/integration/cluster.go:1255 +0x5e4
  go.etcd.io/etcd/tests/v3/framework/integration.(*Cluster).Terminate.func1()
      /home/runner/work/etcd/etcd/tests/framework/integration/cluster.go:1387 +0xb7
  go.etcd.io/etcd/tests/v3/framework/integration.(*Cluster).Terminate·dwrap·9()
      /home/runner/work/etcd/etcd/tests/framework/integration/cluster.go:1388 +0x47

Previous read at 0x00c0000e0d28 by goroutine 718:
  go.etcd.io/etcd/tests/v3/framework/integration.(*Member).Bridge()
      /home/runner/work/etcd/etcd/tests/framework/integration/cluster.go:808 +0xc4
  go.etcd.io/etcd/tests/v3/integration/clientv3.TestWatchOverlapDropConnContextCancel.func1()
      /home/runner/work/etcd/etcd/tests/integration/clientv3/watch_test.go:1049 +0x27
  go.etcd.io/etcd/tests/v3/integration/clientv3.testWatchOverlapContextCancel.func1()
      /home/runner/work/etcd/etcd/tests/integration/clientv3/watch_test.go:1082 +0x2be

Goroutine 461 (running) created at:
  go.etcd.io/etcd/tests/v3/framework/integration.(*Cluster).Terminate()
      /home/runner/work/etcd/etcd/tests/framework/integration/cluster.go:1385 +0x30c
  go.etcd.io/etcd/tests/v3/integration/clientv3.testWatchOverlapContextCancel·dwrap·93()
      /home/runner/work/etcd/etcd/tests/integration/clientv3/watch_test.go:1057 +0x58
  runtime.deferCallSave()
      /opt/hostedtoolcache/go/1.17.8/x64/src/runtime/panic.go:950 +0x81
  testing.(*common).Fatalf()
      /opt/hostedtoolcache/go/1.17.8/x64/src/testing/testing.go:830 +0x84
  go.etcd.io/etcd/tests/v3/integration/clientv3.testWatchOverlapContextCancel()
      /home/runner/work/etcd/etcd/tests/integration/clientv3/watch_test.go:1108 +0x9b7
  go.etcd.io/etcd/tests/v3/integration/clientv3.TestWatchOverlapDropConnContextCancel()
      /home/runner/work/etcd/etcd/tests/integration/clientv3/watch_test.go:1051 +0x35
  testing.tRunner()
      /opt/hostedtoolcache/go/1.17.8/x64/src/testing/testing.go:1259 +0x22f
  testing.(*T).Run·dwrap·21()
      /opt/hostedtoolcache/go/1.17.8/x64/src/testing/testing.go:1306 +0x47

Goroutine 718 (running) created at:
  go.etcd.io/etcd/tests/v3/integration/clientv3.testWatchOverlapContextCancel()
      /home/runner/work/etcd/etcd/tests/integration/clientv3/watch_test.go:1076 +0x62a
  go.etcd.io/etcd/tests/v3/integration/clientv3.TestWatchOverlapDropConnContextCancel()
      /home/runner/work/etcd/etcd/tests/integration/clientv3/watch_test.go:1051 +0x35
  testing.tRunner()
      /opt/hostedtoolcache/go/1.17.8/x64/src/testing/testing.go:1259 +0x22f
  testing.(*T).Run·dwrap·21()
      /opt/hostedtoolcache/go/1.17.8/x64/src/testing/testing.go:1306 +0x47
==================
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1253326]

goroutine 54151 [running]:
go.etcd.io/etcd/tests/v3/framework/integration.(*bridge).DropConnections(0x0)
	/home/runner/work/etcd/etcd/tests/framework/integration/bridge.go:71 +0x46
go.etcd.io/etcd/tests/v3/integration/clientv3.TestWatchOverlapDropConnContextCancel.func1(0xc002edef00)
	/home/runner/work/etcd/etcd/tests/integration/clientv3/watch_test.go:1049 +0xd6
go.etcd.io/etcd/tests/v3/integration/clientv3.testWatchOverlapContextCancel.func1()
	/home/runner/work/etcd/etcd/tests/integration/clientv3/watch_test.go:1082 +0x2bf
created by go.etcd.io/etcd/tests/v3/integration/clientv3.testWatchOverlapContextCancel
	/home/runner/work/eFAIL: (code:1):
  % (cd tests && 'env' 'ETCD_VERIFY=all' 'go' 'test' '-timeout=30m' '-tags' 'cluster_proxy' '--race=true' '--cpu=4' 'go.etcd.io/etcd/tests/v3/integration/clientv3')
tcd/etcd/tests/integration/clientv3/watch_test.go:1076 +0x62b
FAIL	go.etcd.io/etcd/tests/v3/integration/clientv3	112.082s
FAIL
FAIL: 'grpcproxy_integration' failed at Sun May  1 11:03:59 UTC 2022

Error: Process completed with exit code 1.

```

**Comment by eval-exec** [comment]
What's your git commit hash?

**Comment by ahrtr** [comment]
> What's your git commit hash?

The latest code/commit in main branch

**Comment by eval-exec** [comment]
I  reproduced it and figured it out. 
https://github.com/etcd-io/etcd/blob/00d6d40aea0de3430f88a7adf25807ed919387ea/tests/integration/clientv3/watch_test.go#L1107

It's `testWatchOverlapContextCancel()` get timeout , then `defer clus.Terminate(t)` is running. but meanwhile `clus.Members[0].Bridge().DropConnections()` is runnning on another goroutine.

**Comment by ahrtr** [comment]
I am well aware of the root cause, I just don't have bandwidth to fix it. Thanks anyway. 

Feel free to submit a PR to fix it.

**Comment by ahrtr** [comment]
This issue has already been fixed in [pull/14004](https://github.com/etcd-io/etcd/pull/14004)
