### ISSUE TITLE
panic: Log in goroutine after TestNewDirectorScheme has completed

### ISSUE THREAD

**Issue by ahrtr** [etcd-io/etcd#14021]
I see this panic multiple times. 

It's an issue on the main branch, but probably previous releases have this issue as well. Let's fix it in main branch firstly.  See also [step:5:1022](https://github.com/etcd-io/etcd/runs/6332845004?check_suite_focus=true#step:5:1022)

The [goroutine](https://github.com/etcd-io/etcd/blob/b7be91f98b7a7a6202ed9e9bc37b692d484585a8/server/proxy/httpproxy/director.go#L46-L71) is out of control once it being created. We need to figure out a solution to make it under control. 

```

panic: Log in goroutine after TestNewDirectorScheme has completed: 2022-05-07T06:52:44.542Z	INFO	endpoints found	{"endpoints": ["http://example.com:8080/", "http://192.0.2.8:4002/"]}

goroutine 13 [running]:
testing.(*common).logDepth(0x8c00f00, {0x8c26600, 0x71}, 0x3)
	/opt/hostedtoolcache/go/1.17.8/x64/src/testing/testing.go:779 +0x482
testing.(*common).log(...)
	/opt/hostedtoolcache/go/1.17.8/x64/src/testing/testing.go:761
testing.(*common).Logf(0x8c00f00, {0x83d6620, 0x2}, {0x8c0daf8, 0x1, 0x1})
	/opt/hostedtoolcache/go/1.17.8/x64/src/testing/testing.go:807 +0x65
go.uber.org/zap/zaptest.testingWriter.Write({{0x845c2f4, 0x8c00f00}, 0x0}, {0x8d9c800, 0x72, 0x400})
	/home/runner/go/pkg/mod/go.uber.org/zap@v1.17.0/zaptest/logger.go:130 +0xee
go.uber.org/zap/zapcore.(*ioCore).Write(0x8d02888, {0x0, {0xc095a3af2057fbdf, 0x27395f, 0x8688a20}, {0x0, 0x0}, {0x83da80c, 0xf}, {0x0, ...}, ...}, ...)
	/home/runner/go/pkg/mod/go.uber.org/zap@v1.17.0/zapcore/core.go:90 +0xac
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0x8c67b90, {0x8c58e10, 0x1, 0x1})
	/home/runner/go/pkg/mod/go.uber.org/zap@v1.17.0/zapcore/entry.go:220 +0x1e8
go.uber.org/zap.(*Logger).Info(0x8c589f0, {0x83da80c, 0xf}, {0x8c58e10, 0x1, 0x1})
	/home/runner/go/pkg/mod/go.uber.org/zap@v1.17.0/logger.go:189 +0x5e
go.etcd.io/etcd/server/v3/proxy/httpproxy.newDirector.func1.1()
	/home/runner/work/etcd/etcd/server/proxy/httpproxy/director.go:65 +0x1e6
sync.(*Once).doSlow(0x869cba8, 0x8c34fc8)
	/opt/hostedtoolcache/go/1.17.8/x64/src/sync/once.go:68 +0x93
sync.(*Once).Do(0x869cba8, 0x8c34fc8)
	/opt/hostedtoolcache/go/1.17.8/x64/src/sync/once.go:59 +0x3f
go.etcd.io/etcd/server/v3/proxy/httpproxy.newDirector.func1(0x8c58a20, 0xdf8475800, 0x8c589f0)
	/home/runner/work/etcd/etcd/server/proxy/httpproxy/director.go:60 +0xe4
created by go.etcd.io/etcd/server/v3/proxy/httpproxy.newDirector
	/home/runner/work/etcd/etcd/server/proxy/httpproxy/director.go:46 +0x1c3
FAIL	go.etcd.io/etcd/server/v3/proxy/httpproxy	0.007s
```

**Comment by caproven** [comment]
@ahrtr mind if I take a stab at this?

**Comment by ahrtr** [comment]
> @ahrtr mind if I take a stab at this?

Sure. Feel free to deliver a PR for review.

**Comment by caproven** [comment]
Able to reproduce this test error at will by running the tests with GOMAXPROCS=1. Hopefully this is close enough for mimicking the "linux-386-unit-1-cpu" environment where the error occurred.

```
❯ GOMAXPROCS=1 go test ./proxy/httpproxy -count=100000
panic: Log in goroutine after TestNewDirectorScheme has completed: 2022-05-10T23:47:31.427-0400 INFO    endpoints found{"endpoints": ["http://example.com:8080", "http://192.0.2.8:4002"]}

goroutine 13 [running]:
testing.(*common).logDepth(0xc00009bba0, {0xc000098180, 0x75}, 0x3)
        /usr/local/go/src/testing/testing.go:887 +0x4c7
testing.(*common).log(...)
        /usr/local/go/src/testing/testing.go:869
testing.(*common).Logf(0xc00009bba0, {0x85468c?, 0x400?}, {0xc00041e380?, 0x0?, 0x1?})
        /usr/local/go/src/testing/testing.go:920 +0x5a
go.uber.org/zap/zaptest.testingWriter.Write({{0x8fe7e8?, 0xc00009bba0?}, 0x0?}, {0xc00047e400?, 0x76, 0xc00041e370?})
        /home/caproven/dev/go/pkg/mod/go.uber.org/zap@v1.17.0/zaptest/logger.go:130 +0xe6
go.uber.org/zap/zapcore.(*ioCore).Write(0xc000132ba0, {0x0, {0xc096ea54d9799690, 0x3bd5f9, 0xb93ae0}, {0x0, 0x0}, {0x858def, 0xf}, {0x0, ...}, ...}, ...)
        /home/caproven/dev/go/pkg/mod/go.uber.org/zap@v1.17.0/zapcore/core.go:90 +0xb5
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0000dc540, {0xc0004276c0, 0x1, 0x1})
        /home/caproven/dev/go/pkg/mod/go.uber.org/zap@v1.17.0/zapcore/entry.go:220 +0x204
go.uber.org/zap.(*Logger).Info(0xc000439160?, {0x858def?, 0x2?}, {0xc0004276c0, 0x1, 0x1})
        /home/caproven/dev/go/pkg/mod/go.uber.org/zap@v1.17.0/logger.go:189 +0x59
go.etcd.io/etcd/server/v3/proxy/httpproxy.newDirector.func1.1()
        /home/caproven/dev/temp/etcd/server/proxy/httpproxy/director.go:65 +0x267
sync.(*Once).doSlow(0xc000021a40?, 0x512a60?)
        /usr/local/go/src/sync/once.go:68 +0xc2
sync.(*Once).Do(...)
        /usr/local/go/src/sync/once.go:59
go.etcd.io/etcd/server/v3/proxy/httpproxy.newDirector.func1()
        /home/caproven/dev/temp/etcd/server/proxy/httpproxy/director.go:60 +0xe5
created by go.etcd.io/etcd/server/v3/proxy/httpproxy.newDirector
        /home/caproven/dev/temp/etcd/server/proxy/httpproxy/director.go:46 +0x1f0
FAIL    go.etcd.io/etcd/server/v3/proxy/httpproxy       0.008s
FAIL
```
