### ISSUE TITLE
etcd restart make panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by sunnoy** [etcd-io/etcd#14431]
### What happened?

etcd restart all time 

```bash
2022-08-13 20:54:21.757713 I | etcdmain: etcd Version: 3.0.17
2022-08-13 20:54:21.757796 I | etcdmain: Git SHA: cc198e2
2022-08-13 20:54:21.757805 I | etcdmain: Go Version: go1.6.4
2022-08-13 20:54:21.757813 I | etcdmain: Go OS/Arch: linux/amd64
2022-08-13 20:54:21.757822 I | etcdmain: setting maximum number of CPUs to 16, total number of available CPUs is 16
2022-08-13 20:54:21.757907 N | etcdmain: the server is already initialized as member before, starting as etcd member...
2022-08-13 20:54:21.758056 I | etcdmain: listening for peers on http://127.0.0.1:2380
2022-08-13 20:54:21.758165 I | etcdmain: listening for client requests on 127.0.0.1:2379
2022-08-13 20:54:21.780511 I | etcdserver: recovered store from snapshot at index 10078388
2022-08-13 20:54:21.780533 I | etcdserver: name = etcd-private-k8s
2022-08-13 20:54:21.780541 I | etcdserver: data dir = /var/etcd/data
2022-08-13 20:54:21.780571 I | etcdserver: member dir = /var/etcd/data/member
2022-08-13 20:54:21.780579 I | etcdserver: heartbeat = 100ms
2022-08-13 20:54:21.780586 I | etcdserver: election = 1000ms
2022-08-13 20:54:21.780594 I | etcdserver: snapshot count = 100
2022-08-13 20:54:21.780608 I | etcdserver: advertise client URLs = http://127.0.0.1:2379
2022-08-13 20:54:22.551267 I | etcdserver: restarting member 8e9e05c52164694d in cluster cdf818194e3a8c32 at commit index 10078436
2022-08-13 20:54:22.551465 I | raft: 8e9e05c52164694d became follower at term 4
2022-08-13 20:54:22.551499 I | raft: newRaft 8e9e05c52164694d [peers: [8e9e05c52164694d], term: 4, commit: 10078436, applied: 10078388, lastindex: 10078436, lastterm: 4]
2022-08-13 20:54:22.551915 I | api: enabled capabilities for version 3.0
2022-08-13 20:54:22.551943 I | membership: added member 8e9e05c52164694d [http://localhost:2380] to cluster cdf818194e3a8c32 from store
2022-08-13 20:54:22.551959 I | membership: set the cluster version to 3.0 from store
2022-08-13 20:54:22.578512 I | mvcc: restore compact to 13300669
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
panic(0xf5ada0, 0xc820010030)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc.(*store).restore(0xc820212300, 0x0, 0x0)
	/home/gyuho/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/kvstore.go:389 +0x1e6d
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc.NewStore(0x7fc6170286a8, 0xc8202a9920, 0x7fc61706fb90, 0xc820078ba0, 0x7fc61706fc10, 0xc820222250, 0x1768280)
	/home/gyuho/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/kvstore.go:120 +0x39e
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc.newWatchableStore(0x7fc6170286a8, 0xc8202a9920, 0x7fc61706fb90, 0xc820078ba0, 0x7fc61706fc10, 0xc820222250, 0x7fc61706fc10)
	/home/gyuho/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/watchable_store.go:73 +0x71
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc.New(0x7fc6170286a8, 0xc8202a9920, 0x7fc61706fb90, 0xc820078ba0, 0x7fc61706fc10, 0xc820222250, 0x0, 0x0)
	/home/gyuho/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/watchable_store.go:68 +0x66
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver.NewServer(0xc8200af4a0, 0xc820222240, 0x0, 0x0)
	/home/gyuho/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/server.go:405 +0x1d6c
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain.startEtcd(0xc820064c00, 0x0, 0x0, 0x0)
	/home/gyuho/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain/etcd.go:374 +0x245f
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain.startEtcdOrProxyV2()
	/home/gyuho/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain/etcd.go:116 +0x2101
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain.Main()
	/home/gyuho/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain/main.go:36 +0x21e
main.main()
	/home/gyuho/go/src/github.com/coreos/etcd/cmd/main.go:28 +0x14
Warn: INITIAL_CLUSTER variable unset - defaulting to etcd-private-docker-main=http://localhost:2380
Warn: LISTEN_PEER_URLS variable unset - defaulting to http://localhost:2380
Warn: INITIAL_ADVERTISE_PEER_URLS variable unset - defaulting to http://localhost:2380
E0813 20:59:29.953096      12 migrate.go:170] Migration failed: existing data directory '/var/etcd/data' is missing version.txt file, unable to migrate
```

### What did you expect to happen?

normal restart

### How can we reproduce it (as minimally and precisely as possible)?

I can not how to reproduce it 

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
# paste output here
2022-08-13 20:54:21.757713 I | etcdmain: etcd Version: 3.0.17
2022-08-13 20:54:21.757796 I | etcdmain: Git SHA: cc198e2
2022-08-13 20:54:21.757805 I | etcdmain: Go Version: go1.6.4
2022-08-13 20:54:21.757813 I | etcdmain: Go OS/Arch: linux/amd64
$ etcdctl version
# paste output here

2022-08-13 20:54:21.757713 I | etcdmain: etcd Version: 3.0.17
2022-08-13 20:54:21.757796 I | etcdmain: Git SHA: cc198e2
2022-08-13 20:54:21.757805 I | etcdmain: Go Version: go1.6.4
2022-08-13 20:54:21.757813 I | etcdmain: Go OS/Arch: linux/amd64
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

### Relevant log output

```shell
2022-08-13 20:54:21.757713 I | etcdmain: etcd Version: 3.0.17
2022-08-13 20:54:21.757796 I | etcdmain: Git SHA: cc198e2
2022-08-13 20:54:21.757805 I | etcdmain: Go Version: go1.6.4
2022-08-13 20:54:21.757813 I | etcdmain: Go OS/Arch: linux/amd64
2022-08-13 20:54:21.757822 I | etcdmain: setting maximum number of CPUs to 16, total number of available CPUs is 16
2022-08-13 20:54:21.757907 N | etcdmain: the server is already initialized as member before, starting as etcd member...
2022-08-13 20:54:21.758056 I | etcdmain: listening for peers on http://127.0.0.1:2380
2022-08-13 20:54:21.758165 I | etcdmain: listening for client requests on 127.0.0.1:2379
2022-08-13 20:54:21.780511 I | etcdserver: recovered store from snapshot at index 10078388
2022-08-13 20:54:21.780533 I | etcdserver: name = etcd-private-k8s
2022-08-13 20:54:21.780541 I | etcdserver: data dir = /var/etcd/data
2022-08-13 20:54:21.780571 I | etcdserver: member dir = /var/etcd/data/member
2022-08-13 20:54:21.780579 I | etcdserver: heartbeat = 100ms
2022-08-13 20:54:21.780586 I | etcdserver: election = 1000ms
2022-08-13 20:54:21.780594 I | etcdserver: snapshot count = 100
2022-08-13 20:54:21.780608 I | etcdserver: advertise client URLs = http://127.0.0.1:2379
2022-08-13 20:54:22.551267 I | etcdserver: restarting member 8e9e05c52164694d in cluster cdf818194e3a8c32 at commit index 10078436
2022-08-13 20:54:22.551465 I | raft: 8e9e05c52164694d became follower at term 4
2022-08-13 20:54:22.551499 I | raft: newRaft 8e9e05c52164694d [peers: [8e9e05c52164694d], term: 4, commit: 10078436, applied: 10078388, lastindex: 10078436, lastterm: 4]
2022-08-13 20:54:22.551915 I | api: enabled capabilities for version 3.0
2022-08-13 20:54:22.551943 I | membership: added member 8e9e05c52164694d [http://localhost:2380] to cluster cdf818194e3a8c32 from store
2022-08-13 20:54:22.551959 I | membership: set the cluster version to 3.0 from store
2022-08-13 20:54:22.578512 I | mvcc: restore compact to 13300669
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
panic(0xf5ada0, 0xc820010030)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc.(*store).restore(0xc820212300, 0x0, 0x0)
	/home/gyuho/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/kvstore.go:389 +0x1e6d
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc.NewStore(0x7fc6170286a8, 0xc8202a9920, 0x7fc61706fb90, 0xc820078ba0, 0x7fc61706fc10, 0xc820222250, 0x1768280)
	/home/gyuho/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/kvstore.go:120 +0x39e
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc.newWatchableStore(0x7fc6170286a8, 0xc8202a9920, 0x7fc61706fb90, 0xc820078ba0, 0x7fc61706fc10, 0xc820222250, 0x7fc61706fc10)
	/home/gyuho/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/watchable_store.go:73 +0x71
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc.New(0x7fc6170286a8, 0xc8202a9920, 0x7fc61706fb90, 0xc820078ba0, 0x7fc61706fc10, 0xc820222250, 0x0, 0x0)
	/home/gyuho/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/watchable_store.go:68 +0x66
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver.NewServer(0xc8200af4a0, 0xc820222240, 0x0, 0x0)
	/home/gyuho/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/server.go:405 +0x1d6c
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain.startEtcd(0xc820064c00, 0x0, 0x0, 0x0)
	/home/gyuho/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain/etcd.go:374 +0x245f
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain.startEtcdOrProxyV2()
	/home/gyuho/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain/etcd.go:116 +0x2101
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain.Main()
	/home/gyuho/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdmain/main.go:36 +0x21e
main.main()
	/home/gyuho/go/src/github.com/coreos/etcd/cmd/main.go:28 +0x14
Warn: INITIAL_CLUSTER variable unset - defaulting to etcd-private-docker-main=http://localhost:2380
Warn: LISTEN_PEER_URLS variable unset - defaulting to http://localhost:2380
Warn: INITIAL_ADVERTISE_PEER_URLS variable unset - defaulting to http://localhost:2380
E0813 20:59:29.953096      12 migrate.go:170] Migration failed: existing data directory '/var/etcd/data' is missing version.txt file, unable to migrate
```

**Comment by serathius** [comment]
```
2022-08-13 20:54:21.757713 I | etcdmain: etcd Version: 3.0.17
```
Version v3.0.17 is over 5 years old and no longer supported. Please upgrade.

**Comment by sunnoy** [comment]
Is this a bug ？
Can an update fix this “bug“?

**Comment by serathius** [comment]
> Is this a bug ？ 

Yes, panics are not expected in code.

> Can an update fix this “bug“?

Yes, it should.
