### ISSUE TITLE
use restore to recover occurred panic

### ISSUE THREAD

**Issue by walleliu1016** [etcd-io/etcd#14668]
### What happened?

The etcd I use has 3 nodes, but they all restarted accidentally. I hope to restore the cluster through the restore function, and try to restore from the backup file of machine A. The restoration is successful on machine A, but the same backup file from machine A occurred panic error when execute restoration on machine B and C.

### What did you expect to happen?

It can also be restored normally on the machine B and C.

### How can we reproduce it (as minimally and precisely as possible)?

1. shutdown all etcd node
2. resore all node base on the same backup file from node A
3. execute restore function on A (successfully)
4. execute restore function on B or C (panic occurred)

### Anything else we need to know?

nothing

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
etcd Version: 3.4.0
Git SHA: 898bd1351
Go Version: go1.12.9
Go OS/Arch: linux/amd64

$ etcdctl version
etcdctl version: 3.4.0
API version: 3.4
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

### Relevant log output

```shell
{"level":"info","ts":1667208439.311402,"caller":"snapshot/v3_snapshot.go:286","msg":"restoring snapshot","path":"restore.db","wal-dir":"/dev/shm/wcs-etcd/data/member/wal","data-dir":"/dev/shm/wcs-etcd/data","snap-dir":"/dev/shm/wcs-etcd/data/member/snap"}
unexpected fault address 0x7f990db9c000
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x7f990db9c000 pc=0x8580ba]

goroutine 1 [running]:
runtime.throw(0xd3ffc9, 0x5)
        /usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc000206848 sp=0xc000206818 pc=0x42c862
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:387 +0x47e fp=0xc000206878 sp=0xc000206848 pc=0x44144e
go.etcd.io/bbolt.(*Tx).checkBucket.func1(0x7f990db9c000, 0x3)
        /Users/leegyuho/go/pkg/mod/go.etcd.io/bbolt@v1.3.3/tx.go:466 +0x6a fp=0xc0002069b8 sp=0xc000206878 pc=0x8580ba
go.etcd.io/bbolt.(*Tx).forEachPage(0xc0002bc000, 0x8006, 0x3, 0xc000206af8)
        /Users/leegyuho/go/pkg/mod/go.etcd.io/bbolt@v1.3.3/tx.go:628 +0x83 fp=0xc000206a00 sp=0xc0002069b8 pc=0x856b33
go.etcd.io/bbolt.(*Tx).forEachPage(0xc0002bc000, 0x2192, 0x2, 0xc000206af8)
        /Users/leegyuho/go/pkg/mod/go.etcd.io/bbolt@v1.3.3/tx.go:634 +0xd4 fp=0xc000206a48 sp=0xc000206a00 pc=0x856b84
go.etcd.io/bbolt.(*Tx).forEachPage(0xc0002bc000, 0x2b8f, 0x1, 0xc000206af8)
        /Users/leegyuho/go/pkg/mod/go.etcd.io/bbolt@v1.3.3/tx.go:634 +0xd4 fp=0xc000206a90 sp=0xc000206a48 pc=0x856b84
go.etcd.io/bbolt.(*Tx).forEachPage(0xc0002bc000, 0x967, 0x0, 0xc000206af8)
        /Users/leegyuho/go/pkg/mod/go.etcd.io/bbolt@v1.3.3/tx.go:634 +0xd4 fp=0xc000206ad8 sp=0xc000206a90 pc=0x856b84
go.etcd.io/bbolt.(*Tx).checkBucket(0xc0002bc000, 0xc0001e4c80, 0xc000206dc8, 0xc000206d98, 0xc0001e20c0)
        /Users/leegyuho/go/pkg/mod/go.etcd.io/bbolt@v1.3.3/tx.go:465 +0xd4 fp=0xc000206b68 sp=0xc000206ad8 pc=0x8562a4
go.etcd.io/bbolt.(*Tx).checkBucket.func2(0x7f990651d1b9, 0x3, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/leegyuho/go/pkg/mod/go.etcd.io/bbolt@v1.3.3/tx.go:490 +0xc0 fp=0xc000206bc0 sp=0xc000206b68 pc=0x858780
go.etcd.io/bbolt.(*Bucket).ForEach(0xc0002bc018, 0xc000206c80, 0x0, 0xc000206c50)
        /Users/leegyuho/go/pkg/mod/go.etcd.io/bbolt@v1.3.3/bucket.go:388 +0xfe fp=0xc000206c30 sp=0xc000206bc0 pc=0x8442fe
go.etcd.io/bbolt.(*Tx).checkBucket(0xc0002bc000, 0xc0002bc018, 0xc000206dc8, 0xc000206d98, 0xc0001e20c0)
        /Users/leegyuho/go/pkg/mod/go.etcd.io/bbolt@v1.3.3/tx.go:488 +0x146 fp=0xc000206cc0 sp=0xc000206c30 pc=0x856316
go.etcd.io/bbolt.(*DB).freepages(0xc0002b8000, 0x0, 0x0, 0x0)
        /Users/leegyuho/go/pkg/mod/go.etcd.io/bbolt@v1.3.3/db.go:1006 +0x1f8 fp=0xc000206e98 sp=0xc000206cc0 pc=0x84b458
go.etcd.io/bbolt.(*DB).loadFreelist.func1()
        /Users/leegyuho/go/pkg/mod/go.etcd.io/bbolt@v1.3.3/db.go:313 +0x10e fp=0xc000206ed0 sp=0xc000206e98 pc=0x85785e
sync.(*Once).Do(0xc0002b8168, 0xc000206f10)
        /usr/local/go/src/sync/once.go:44 +0xb3 fp=0xc000206f00 sp=0xc000206ed0 pc=0x46f483
go.etcd.io/bbolt.(*DB).loadFreelist(0xc0002b8000)
        /Users/leegyuho/go/pkg/mod/go.etcd.io/bbolt@v1.3.3/db.go:309 +0x56 fp=0xc000206f30 sp=0xc000206f00 pc=0x848796
go.etcd.io/bbolt.Open(0xc0001e6450, 0x25, 0xc000000180, 0xc0002071d8, 0xc000207048, 0xc000207058, 0x4355cf)
        /Users/leegyuho/go/pkg/mod/go.etcd.io/bbolt@v1.3.3/db.go:286 +0x326 fp=0xc000206ff0 sp=0xc000206f30 pc=0x848266
go.etcd.io/etcd/mvcc/backend.newBackend(0xc0001e6450, 0x25, 0x5f5e100, 0x2710, 0x0, 0x0, 0x280000000, 0x0, 0x0)
        /tmp/etcd-release-3.4.0/etcd/release/etcd/mvcc/backend/backend.go:154 +0xfe fp=0xc000207238 sp=0xc000206ff0 pc=0x87caee
go.etcd.io/etcd/mvcc/backend.NewDefaultBackend(...)
        /tmp/etcd-release-3.4.0/etcd/release/etcd/mvcc/backend/backend.go:143
go.etcd.io/etcd/clientv3/snapshot.(*v3Manager).saveDB(0xc00013cf60, 0x0, 0x0)
        /tmp/etcd-release-3.4.0/etcd/release/etcd/clientv3/snapshot/v3_snapshot.go:381 +0x463 fp=0xc0002073d0 sp=0xc000207238 pc=0xb3af33
go.etcd.io/etcd/clientv3/snapshot.(*v3Manager).Restore(0xc00013cf60, 0x7ffd862a2681, 0xa, 0x7ffd862a26a5, 0x13, 0x7ffd862a26c4, 0x16, 0xc0001e6240, 0x21, 0xc000128be0, ...)
        /tmp/etcd-release-3.4.0/etcd/release/etcd/clientv3/snapshot/v3_snapshot.go:293 +0x89b fp=0xc000207b98 sp=0xc0002073d0 pc=0xb3a0db
go.etcd.io/etcd/etcdctl/ctlv3/command.snapshotRestoreCommandFunc(0xc000221b80, 0xc0001ee5b0, 0x1, 0x7)
        /tmp/etcd-release-3.4.0/etcd/release/etcd/etcdctl/ctlv3/command/snapshot_command.go:160 +0x2a5 fp=0xc000207d30 sp=0xc000207b98 pc=0xb659d5
github.com/spf13/cobra.(*Command).execute(0xc000221b80, 0xc0001ee540, 0x7, 0x7, 0xc000221b80, 0xc0001ee540)
        /Users/leegyuho/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2ae fp=0xc000207e18 sp=0xc000207d30 pc=0xab8ade
github.com/spf13/cobra.(*Command).ExecuteC(0x14ad220, 0xb, 0xc000064be0, 0xb7ab01)
        /Users/leegyuho/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ec fp=0xc000207ee8 sp=0xc000207e18 pc=0xab972c
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/leegyuho/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
go.etcd.io/etcd/etcdctl/ctlv3.Start()
        /tmp/etcd-release-3.4.0/etcd/release/etcd/etcdctl/ctlv3/ctl_nocov.go:25 +0x81 fp=0xc000207f18 sp=0xc000207ee8 pc=0xb7a9d1
main.main()
        /tmp/etcd-release-3.4.0/etcd/release/etcd/etcdctl/main.go:35 +0x77 fp=0xc000207f98 sp=0xc000207f18 pc=0xb7bcc7
runtime.main()
        /usr/local/go/src/runtime/proc.go:200 +0x20c fp=0xc000207fe0 sp=0xc000207f98 pc=0x42e1cc
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000207fe8 sp=0xc000207fe0 pc=0x459211

goroutine 39 [syscall]:
os/signal.signal_recv(0x459216)
        /usr/local/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
        /usr/local/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 65 [chan receive]:
go.etcd.io/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc00014db80)
        /tmp/etcd-release-3.4.0/etcd/release/etcd/pkg/logutil/merge_logger.go:173 +0x3a2
created by go.etcd.io/etcd/pkg/logutil.NewMergeLogger
        /tmp/etcd-release-3.4.0/etcd/release/etcd/pkg/logutil/merge_logger.go:91 +0x80

goroutine 92 [chan receive]:
go.etcd.io/bbolt.(*DB).freepages.func2(0xc0001e20c0)
        /Users/leegyuho/go/pkg/mod/go.etcd.io/bbolt@v1.3.3/db.go:1002 +0x41
created by go.etcd.io/bbolt.(*DB).freepages
        /Users/leegyuho/go/pkg/mod/go.etcd.io/bbolt@v1.3.3/db.go:1001 +0x1b5
```

**Comment by lavacat** [comment]
is this reproducible in latest 3.4 release? Your stack trace has bbolt@v1.3.3, but latest release has 1.3.6
https://github.com/etcd-io/etcd/blob/v3.4.21/go.mod#L42

**Comment by lavacat** [comment]
It's possible that your snapshot file got corrupted during copy to B and C. Can you confirm that `md5sum` is the same on all hosts?

**Comment by walleliu1016** [comment]
> It's possible that your snapshot file got corrupted during copy to B and C. Can you confirm that `md5sum` is the same on all hosts?
it looks like the reason, i checked the file with different md5 value, maybe the rz/sz problems.
thanks a lot
