### ISSUE TITLE
TestKVDelete flake

### ISSUE THREAD

**Issue by tjungblu** [etcd-io/etcd#14762]
### Which github workflows are flaking?

E2E

### Which tests are flaking?
```

2022-11-15T08:05:39.3154955Z --- FAIL: TestKVDelete (38.24s)
2022-11-15T08:05:39.3155298Z     before.go:35: Changing working directory to: /tmp/TestKVDelete1103204917/001
2022-11-15T08:05:39.3155623Z     --- FAIL: TestKVDelete/ClientAutoTLS (15.02s)
2022-11-15T08:05:39.3156371Z         logger.go:130: 2022-11-15T08:05:20.896Z	INFO	starting server...	{"name": "TestKVDeleteClientAutoTLS-test-0"}
2022-11-15T08:05:39.3163193Z         logger.go:130: 2022-11-15T08:05:20.896Z	INFO	spawning process	{"args": ["/home/runner/work/etcd/etcd/bin/etcd", "--name", "TestKVDeleteClientAutoTLS-test-0", "--listen-client-urls", "https://localhost:20000", "--advertise-client-urls", "https://localhost:20000", "--listen-peer-urls", "http://localhost:20001", "--initial-advertise-peer-urls", "http://localhost:20001", "--initial-cluster-token", "new", "--data-dir", "/tmp/TestKVDeleteClientAutoTLS565676333/001", "--snapshot-count", "100000", "--strict-reconfig-check=false", "--auto-tls", "--initial-cluster", "TestKVDeleteClientAutoTLS-test-0=http://localhost:20001", "--initial-cluster-state", "new"], "working-dir": "/tmp/TestKVDelete1103204917/001", "name": "TestKVDeleteClientAutoTLS-test-0", "environment-variables": ["ETCD_VERIFY=all", "EXPECT_DEBUG=true", "PATH=/opt/hostedtoolcache/go/1.19.3/x64/bin:/home/runner/go/bin:/opt/hostedtoolcache/go/1.19.3/x64/bin:/home/runner/.local/bin:/opt/pipx_bin:/home/runner/.cargo/bin:/home/runner/.config/composer/vendor/bin:/usr/local/.ghcup/bin:/home/runner/.dotnet/tools:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin", "ETCD_UNSUPPORTED_ARCH=386"]}
2022-11-15T08:05:39.3164016Z         logger.go:130: 2022-11-15T08:05:21.452Z	INFO	started server.	{"name": "TestKVDeleteClientAutoTLS-test-0", "pid": 23377}
2022-11-15T08:05:39.3164685Z         testutil.go:56: ---> Test failed: test timed out after 14.443641403s, err: context deadline exceeded
2022-11-15T08:05:39.3164999Z         testutil.go:57: goroutine 1007 [running]:
2022-11-15T08:05:39.3165531Z             go.etcd.io/etcd/client/pkg/v3/testutil.FatalStack(0x9d44ff0, {0x9c4a730, 0x42})
2022-11-15T08:05:39.3166080Z             	/home/runner/work/etcd/etcd/client/pkg/testutil/testutil.go:55 +0x5c
2022-11-15T08:05:39.3166969Z             go.etcd.io/etcd/tests/v3/framework/testutils.ExecuteUntil({0x8d5ff80, 0x9f24ec0}, 0x9d44ff0, 0x9de1e18)
2022-11-15T08:05:39.3167530Z             	/home/runner/work/etcd/etcd/tests/framework/testutils/execute.go:47 +0x27c
2022-11-15T08:05:39.3168133Z             go.etcd.io/etcd/tests/v3/common.TestKVDelete.func1(0x9d44ff0)
2022-11-15T08:05:39.3168647Z             	/home/runner/work/etcd/etcd/tests/common/kv_test.go:131 +0x294
2022-11-15T08:05:39.3168937Z             testing.tRunner(0x9d44ff0, 0x9e91138)
2022-11-15T08:05:39.3169495Z             	/opt/hostedtoolcache/go/1.19.3/x64/src/testing/testing.go:1446 +0x113
2022-11-15T08:05:39.3169757Z             created by testing.(*T).Run
2022-11-15T08:05:39.3170304Z             	/opt/hostedtoolcache/go/1.19.3/x64/src/testing/testing.go:1493 +0x374
2022-11-15T08:05:39.3170426Z             
2022-11-15T08:05:39.3170683Z             goroutine 1 [chan receive]:
2022-11-15T08:05:39.3171079Z             testing.(*T).Run(0x9c06d20, {0x8bd2ad4, 0xc}, 0x8c2d524)
2022-11-15T08:05:39.3171638Z             	/opt/hostedtoolcache/go/1.19.3/x64/src/testing/testing.go:1494 +0x393
2022-11-15T08:05:39.3172080Z             testing.runTests.func1(0x9c06d20)
2022-11-15T08:05:39.3172798Z             	/opt/hostedtoolcache/go/1.19.3/x64/src/testing/testing.go:1846 +0x5e
2022-11-15T08:05:39.3173105Z             testing.tRunner(0x9c06d20, 0xa11fdf8)
2022-11-15T08:05:39.3173658Z             	/opt/hostedtoolcache/go/1.19.3/x64/src/testing/testing.go:1446 +0x113
2022-11-15T08:05:39.3174263Z             testing.runTests(0xa0ae550, {0x940ffa0, 0x3b, 0x3b}, {0xc0d4f19d4181138a, 0x1a319ca35aa, 0x941d7a0})
2022-11-15T08:05:39.3174920Z             	/opt/hostedtoolcache/go/1.19.3/x64/src/testing/testing.go:1844 +0x3a6
2022-11-15T08:05:39.3175172Z             testing.(*M).Run(0x9ea0370)
2022-11-15T08:05:39.3175724Z             	/opt/hostedtoolcache/go/1.19.3/x64/src/testing/testing.go:1726 +0x680
2022-11-15T08:05:39.3176207Z             go.etcd.io/etcd/tests/v3/framework/e2e.e2eRunner.TestMain({}, 0x9ea0370)
2022-11-15T08:05:39.3177038Z             	/home/runner/work/etcd/etcd/tests/framework/e2e/e2e.go:38 +0x26
2022-11-15T08:05:39.3177373Z             go.etcd.io/etcd/tests/v3/common.TestMain(...)
2022-11-15T08:05:39.3177807Z             	/home/runner/work/etcd/etcd/tests/common/main_test.go:30
2022-11-15T08:05:39.3177967Z             main.main()
2022-11-15T08:05:39.3178619Z             	_testmain.go:165 +0x19a
2022-11-15T08:05:39.3178741Z             
2022-11-15T08:05:39.3179009Z             goroutine 616 [chan receive]:
2022-11-15T08:05:39.3179387Z             testing.(*T).Run(0xa0592c0, {0x8bd3761, 0xd}, 0x9e91138)
2022-11-15T08:05:39.3179946Z             	/opt/hostedtoolcache/go/1.19.3/x64/src/testing/testing.go:1494 +0x393
2022-11-15T08:05:39.3180364Z             go.etcd.io/etcd/tests/v3/common.TestKVDelete(0xa0592c0)
2022-11-15T08:05:39.3181116Z             	/home/runner/work/etcd/etcd/tests/common/kv_test.go:125 +0x11c
2022-11-15T08:05:39.3181437Z             testing.tRunner(0xa0592c0, 0x8c2d524)
2022-11-15T08:05:39.3182000Z             	/opt/hostedtoolcache/go/1.19.3/x64/src/testing/testing.go:1446 +0x113
2022-11-15T08:05:39.3182256Z             created by testing.(*T).Run
2022-11-15T08:05:39.3182804Z             	/opt/hostedtoolcache/go/1.19.3/x64/src/testing/testing.go:1493 +0x374
2022-11-15T08:05:39.3182909Z             
2022-11-15T08:05:39.3183152Z             goroutine 1057 [syscall]:
2022-11-15T08:05:39.3183490Z             syscall.Syscall(0x3, 0x9, 0x9fd9000, 0x1000)
2022-11-15T08:05:39.3184058Z             	/opt/hostedtoolcache/go/1.19.3/x64/src/syscall/syscall_linux.go:68 +0x8
2022-11-15T08:05:39.3184403Z             syscall.read(0x9, {0x9fd9000, 0x1000, 0x1000})
2022-11-15T08:05:39.3184997Z             	/opt/hostedtoolcache/go/1.19.3/x64/src/syscall/zsyscall_linux_386.go:696 +0x4d
2022-11-15T08:05:39.3185362Z             syscall.Read(...)
2022-11-15T08:05:39.3185832Z             	/opt/hostedtoolcache/go/1.19.3/x64/src/syscall/syscall_unix.go:183
2022-11-15T08:05:39.3186113Z             internal/poll.ignoringEINTRIO(...)
2022-11-15T08:05:39.3186711Z             	/opt/hostedtoolcache/go/1.19.3/x64/src/internal/poll/fd_unix.go:794
2022-11-15T08:05:39.3187121Z             internal/poll.(*FD).Read(0x9f25000, {0x9fd9000, 0x1000, 0x1000})
2022-11-15T08:05:39.3187842Z             	/opt/hostedtoolcache/go/1.19.3/x64/src/internal/poll/fd_unix.go:163 +0x213
2022-11-15T08:05:39.3188061Z             os.(*File).read(...)
2022-11-15T08:05:39.3188558Z             	/opt/hostedtoolcache/go/1.19.3/x64/src/os/file_posix.go:31
2022-11-15T08:05:39.3188940Z             os.(*File).Read(0x9e912b8, {0x9fd9000, 0x1000, 0x1000})
2022-11-15T08:05:39.3189431Z             	/opt/hostedtoolcache/go/1.19.3/x64/src/os/file.go:118 +0x62
2022-11-15T08:05:39.3189710Z             bufio.(*Reader).fill(0x9ec87b0)
2022-11-15T08:05:39.3190234Z             	/opt/hostedtoolcache/go/1.19.3/x64/src/bufio/bufio.go:106 +0xe9
2022-11-15T08:05:39.3190567Z             bufio.(*Reader).ReadSlice(0x9ec87b0, 0xa)
2022-11-15T08:05:39.3191091Z             	/opt/hostedtoolcache/go/1.19.3/x64/src/bufio/bufio.go:372 +0x32
2022-11-15T08:05:39.3191467Z             bufio.(*Reader).collectFragments(0x9ec87b0, 0xa)
2022-11-15T08:05:39.3191987Z             	/opt/hostedtoolcache/go/1.19.3/x64/src/bufio/bufio.go:447 +0x54
2022-11-15T08:05:39.3192324Z             bufio.(*Reader).ReadString(0x9ec87b0, 0xa)
2022-11-15T08:05:39.3192826Z             	/opt/hostedtoolcache/go/1.19.3/x64/src/bufio/bufio.go:495 +0x34
2022-11-15T08:05:39.3193388Z             go.etcd.io/etcd/pkg/v3/expect.(*ExpectProcess).tryReadNextLine(0x9c99ab0, 0x9ec87b0)
2022-11-15T08:05:39.3193989Z             	/home/runner/work/etcd/etcd/pkg/expect/expect.go:124 +0x69
2022-11-15T08:05:39.3194439Z             go.etcd.io/etcd/pkg/v3/expect.(*ExpectProcess).read(0x9c99ab0)
2022-11-15T08:05:39.3194937Z             	/home/runner/work/etcd/etcd/pkg/expect/expect.go:115 +0x157
2022-11-15T08:05:39.3195371Z             created by go.etcd.io/etcd/pkg/v3/expect.NewExpectWithEnv
2022-11-15T08:05:39.3195865Z             	/home/runner/work/etcd/etcd/pkg/expect/expect.go:79 +0x1b8
2022-11-15T08:05:39.3195986Z             
2022-11-15T08:05:39.3196214Z             goroutine 1133 [syscall]:
2022-11-15T08:05:39.3196809Z             syscall.Syscall6(0x11c, 0x1, 0x5c5b, 0x9c58698, 0x1000004, 0x0, 0x0)
2022-11-15T08:05:39.3197770Z             	/opt/hostedtoolcache/go/1.19.3/x64/src/syscall/syscall_linux.go:90 +0x8
2022-11-15T08:05:39.3198127Z             os.(*Process).blockUntilWaitable(0x9fa34a0)
2022-11-15T08:05:39.3198660Z             	/opt/hostedtoolcache/go/1.19.3/x64/src/os/wait_waitid.go:32 +0x73
2022-11-15T08:05:39.3198932Z             os.(*Process).wait(0x9fa34a0)
2022-11-15T08:05:39.3199450Z             	/opt/hostedtoolcache/go/1.19.3/x64/src/os/exec_unix.go:22 +0x2e
2022-11-15T08:05:39.3199687Z             os.(*Process).Wait(...)
2022-11-15T08:05:39.3200190Z             	/opt/hostedtoolcache/go/1.19.3/x64/src/os/exec.go:132
2022-11-15T08:05:39.3200687Z             go.etcd.io/etcd/pkg/v3/expect.(*ExpectProcess).waitProcess(0x9fb6e00)
2022-11-15T08:05:39.3201344Z             	/home/runner/work/etcd/etcd/pkg/expect/expect.go:271 +0x49
2022-11-15T08:05:39.3202026Z             go.etcd.io/etcd/pkg/v3/expect.(*ExpectProcess).waitSaveExitErr(0x9fb6e00)
2022-11-15T08:05:39.3202517Z             	/home/runner/work/etcd/etcd/pkg/expect/expect.go:143 +0x67
2022-11-15T08:05:39.3202948Z             created by go.etcd.io/etcd/pkg/v3/expect.NewExpectWithEnv
2022-11-15T08:05:39.3203435Z             	/home/runner/work/etcd/etcd/pkg/expect/expect.go:80 +0x1fd
2022-11-15T08:05:39.3203555Z             
2022-11-15T08:05:39.3203786Z             goroutine 1058 [syscall]:
2022-11-15T08:05:39.3204236Z             syscall.Syscall6(0x11c, 0x1, 0x5b51, 0x9d12e98, 0x1000004, 0x0, 0x0)
2022-11-15T08:05:39.3204802Z             	/opt/hostedtoolcache/go/1.19.3/x64/src/syscall/syscall_linux.go:90 +0x8
2022-11-15T08:05:39.3205157Z             os.(*Process).blockUntilWaitable(0x9d6ac60)
2022-11-15T08:05:39.3205690Z             	/opt/hostedtoolcache/go/1.19.3/x64/src/os/wait_waitid.go:32 +0x73
2022-11-15T08:05:39.3206044Z             os.(*Process).wait(0x9d6ac60)
2022-11-15T08:05:39.3206897Z             	/opt/hostedtoolcache/go/1.19.3/x64/src/os/exec_unix.go:22 +0x2e
2022-11-15T08:05:39.3207118Z             os.(*Process).Wait(...)
2022-11-15T08:05:39.3207544Z             	/opt/hostedtoolcache/go/1.19.3/x64/src/os/exec.go:132
2022-11-15T08:05:39.3208426Z             go.etcd.io/etcd/pkg/v3/expect.(*ExpectProcess).waitProcess(0x9c99ab0)
2022-11-15T08:05:39.3208918Z             	/home/runner/work/etcd/etcd/pkg/expect/expect.go:271 +0x49
2022-11-15T08:05:39.3209428Z             go.etcd.io/etcd/pkg/v3/expect.(*ExpectProcess).waitSaveExitErr(0x9c99ab0)
2022-11-15T08:05:39.3209919Z             	/home/runner/work/etcd/etcd/pkg/expect/expect.go:143 +0x67
2022-11-15T08:05:39.3210349Z             created by go.etcd.io/etcd/pkg/v3/expect.NewExpectWithEnv
2022-11-15T08:05:39.3210833Z             	/home/runner/work/etcd/etcd/pkg/expect/expect.go:80 +0x1fd
2022-11-15T08:05:39.3210952Z             
2022-11-15T08:05:39.3211184Z             goroutine 1132 [syscall]:
2022-11-15T08:05:39.3211525Z             syscall.Syscall(0x3, 0xa, 0xa0cf000, 0x1000)
2022-11-15T08:05:39.3212252Z             	/opt/hostedtoolcache/go/1.19.3/x64/src/syscall/syscall_linux.go:68 +0x8
2022-11-15T08:05:39.3212766Z             syscall.read(0xa, {0xa0cf000, 0x1000, 0x1000})
2022-11-15T08:05:39.3213365Z             	/opt/hostedtoolcache/go/1.19.3/x64/src/syscall/zsyscall_linux_386.go:696 +0x4d
2022-11-15T08:05:39.3213569Z             syscall.Read(...)
2022-11-15T08:05:39.3214106Z             	/opt/hostedtoolcache/go/1.19.3/x64/src/syscall/syscall_unix.go:183
2022-11-15T08:05:39.3214501Z             internal/poll.ignoringEINTRIO(...)
2022-11-15T08:05:39.3215059Z             	/opt/hostedtoolcache/go/1.19.3/x64/src/internal/poll/fd_unix.go:794
2022-11-15T08:05:39.3215491Z             internal/poll.(*FD).Read(0xa029b80, {0xa0cf000, 0x1000, 0x1000})
2022-11-15T08:05:39.3216078Z             	/opt/hostedtoolcache/go/1.19.3/x64/src/internal/poll/fd_unix.go:163 +0x213
2022-11-15T08:05:39.3216296Z             os.(*File).read(...)
2022-11-15T08:05:39.3216928Z             	/opt/hostedtoolcache/go/1.19.3/x64/src/os/file_posix.go:31
2022-11-15T08:05:39.3217286Z             os.(*File).Read(0x9e6d948, {0xa0cf000, 0x1000, 0x1000})
2022-11-15T08:05:39.3217936Z             	/opt/hostedtoolcache/go/1.19.3/x64/src/os/file.go:118 +0x62
2022-11-15T08:05:39.3218198Z             bufio.(*Reader).fill(0x9d0efb0)
2022-11-15T08:05:39.3218721Z             	/opt/hostedtoolcache/go/1.19.3/x64/src/bufio/bufio.go:106 +0xe9
2022-11-15T08:05:39.3219056Z             bufio.(*Reader).ReadSlice(0x9d0efb0, 0xa)
2022-11-15T08:05:39.3219580Z             	/opt/hostedtoolcache/go/1.19.3/x64/src/bufio/bufio.go:372 +0x32
2022-11-15T08:05:39.3219954Z             bufio.(*Reader).collectFragments(0x9d0efb0, 0xa)
2022-11-15T08:05:39.3220475Z             	/opt/hostedtoolcache/go/1.19.3/x64/src/bufio/bufio.go:447 +0x54
2022-11-15T08:05:39.3220951Z             bufio.(*Reader).ReadString(0x9d0efb0, 0xa)
2022-11-15T08:05:39.3221492Z             	/opt/hostedtoolcache/go/1.19.3/x64/src/bufio/bufio.go:495 +0x34
2022-11-15T08:05:39.3222176Z             go.etcd.io/etcd/pkg/v3/expect.(*ExpectProcess).tryReadNextLine(0x9fb6e00, 0x9d0efb0)
2022-11-15T08:05:39.3222848Z             	/home/runner/work/etcd/etcd/pkg/expect/expect.go:124 +0x69
2022-11-15T08:05:39.3223297Z             go.etcd.io/etcd/pkg/v3/expect.(*ExpectProcess).read(0x9fb6e00)
2022-11-15T08:05:39.3223794Z             	/home/runner/work/etcd/etcd/pkg/expect/expect.go:115 +0x157
2022-11-15T08:05:39.3224231Z             created by go.etcd.io/etcd/pkg/v3/expect.NewExpectWithEnv
2022-11-15T08:05:39.3224719Z             	/home/runner/work/etcd/etcd/pkg/expect/expect.go:79 +0x1b8
2022-11-15T08:05:39.3224841Z             
2022-11-15T08:05:39.3225090Z             goroutine 1059 [runnable]:
2022-11-15T08:05:39.3225720Z             go.etcd.io/etcd/pkg/v3/expect.(*ExpectProcess).ExpectFunc(0x9fb6e00, {0x8d5ff80, 0x9f24ec0}, 0x9d27cc8)
2022-11-15T08:05:39.3226475Z             	/home/runner/work/etcd/etcd/pkg/expect/expect.go:183 +0x123
2022-11-15T08:05:39.3227189Z             go.etcd.io/etcd/pkg/v3/expect.(*ExpectProcess).ExpectWithContext(0x9fb6e00, {0x8d5ff80, 0x9f24ec0}, {0x8bcc44f, 0x6})
2022-11-15T08:05:39.3227668Z             	/home/runner/work/etcd/etcd/pkg/expect/expect.go:206 +0x6b
2022-11-15T08:05:39.3228671Z             go.etcd.io/etcd/tests/v3/framework/e2e.(*EtcdctlV3).spawnJsonCmd(0x9de3960, {0x8d5ff80, 0x9f24ec0}, {0x8abc260, 0x9dc8360}, {0xa029b40, 0x7, 0x8})
2022-11-15T08:05:39.3229223Z             	/home/runner/work/etcd/etcd/tests/framework/e2e/etcdctl.go:659 +0x22f
2022-11-15T08:05:39.3229997Z             go.etcd.io/etcd/tests/v3/framework/e2e.(*EtcdctlV3).Get(0x9de3960, {0x8d5ff80, 0x9f24ec0}, {0x0, 0x0}, {0x0, {0x0, 0x0}, 0x0, 0x0, ...})
2022-11-15T08:05:39.3230547Z             	/home/runner/work/etcd/etcd/tests/framework/e2e/etcdctl.go:150 +0xd91
2022-11-15T08:05:39.3230968Z             go.etcd.io/etcd/tests/v3/common.TestKVDelete.func1.1()
2022-11-15T08:05:39.3231465Z             	/home/runner/work/etcd/etcd/tests/common/kv_test.go:190 +0x5c7
2022-11-15T08:05:39.3232104Z             go.etcd.io/etcd/tests/v3/framework/testutils.ExecuteUntil.func1()
2022-11-15T08:05:39.3232895Z             	/home/runner/work/etcd/etcd/tests/framework/testutils/execute.go:38 +0x5a
2022-11-15T08:05:39.3233382Z             created by go.etcd.io/etcd/tests/v3/framework/testutils.ExecuteUntil
2022-11-15T08:05:39.3233951Z             	/home/runner/work/etcd/etcd/tests/framework/testutils/execute.go:36 +0xfd
2022-11-15T08:05:39.3234172Z             
2022-11-15T08:05:39.3234637Z         testutil.go:58: test timed out after 14.443641403s, err: context deadline exceeded
2022-11-15T08:05:39.3235157Z         logger.go:130: 2022-11-15T08:05[1m[0;31mFAIL: (code:1):
```

### Github Action link

https://github.com/etcd-io/etcd/actions/runs/3468325214/jobs/5794029676
https://github.com/etcd-io/etcd/actions/runs/3471097367/jobs/5800143572

### Reason for failure (if possible)

related to #14672

### Anything else we need to know?

This one looks like it takes a little longer to execute all etcdctl invocations to put/delete than the 15s timeout defined in:
https://github.com/etcd-io/etcd/blob/main/tests/common/kv_test.go#L126

So it might already be enough to bump this by a couple of seconds.

**Comment by chaochn47** [comment]
It occurred pretty frequently in my recent PRs. 

https://github.com/etcd-io/etcd/actions/runs/4933445311/jobs/8817412851?pr=15867 is an example.

**Comment by fuweid** [comment]
Example: 

1. https://github.com/etcd-io/etcd/actions/runs/4962116415
