### ISSUE TITLE
Error from transaction

### ISSUE THREAD

**Issue by Koji-Study** [etcd-io/etcd#14845]
### What happened?

When using the transaction of etcd， get error as below:
/ # etcdctl txn -i
compares:
lease("/key1") = "2480221585875029147"
panic: bad value

### What did you expect to happen?

Need your help.

### How can we reproduce it (as minimally and precisely as possible)?

No idea, also need your help

### Etcd version (please run commands below)

/ # etcdctl version
etcdctl version: 3.3.8
API version: 3.3

/ # etcd --version
etcd Version: 3.3.8
Git SHA: 33245c6b5
Go Version: go1.9.7
Go OS/Arch: linux/amd64

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

### Relevant log output

```shell
/ # etcdctl txn -i
compares:
lease("/key1") = "2480221585875029147"
panic: bad value

goroutine 1 [running]:
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/clientv3.mustInt64(0xc6cc80, 0xc42023f568, 0x0)
        /tmp/etcd-release-3.3.8/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/clientv3/compare.go:130 +0x9a
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/clientv3.mustInt64orLeaseID(0xc6cc80, 0xc42023f568, 0xdf8a95)
        /tmp/etcd-release-3.3.8/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/clientv3/compare.go:139 +0x55
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/clientv3.Compare(0x400000000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc420133557, ...)
        /tmp/etcd-release-3.3.8/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/clientv3/compare.go:64 +0x2b0
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdctl/ctlv3/command.parseCompare(0xc420180a80, 0x26, 0xc420180a80, 0x26, 0x0)
        /tmp/etcd-release-3.3.8/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdctl/ctlv3/command/txn_command.go:199 +0x106d
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdctl/ctlv3/command.readCompares(0xc42023fc50, 0x9, 0xc420014048, 0x12faf00)
        /tmp/etcd-release-3.3.8/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdctl/ctlv3/command/txn_command.go:89 +0xb2
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdctl/ctlv3/command.txnCommandFunc(0xc420260600, 0xc42025c6b0, 0x0, 0x1)
        /tmp/etcd-release-3.3.8/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdctl/ctlv3/command/txn_command.go:56 +0x1be
github.com/coreos/etcd/cmd/vendor/github.com/spf13/cobra.(*Command).execute(0xc420260600, 0xc42025c680, 0x1, 0x1, 0xc420260600, 0xc42025c680)
        /tmp/etcd-release-3.3.8/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/spf13/cobra/command.go:572 +0x216
github.com/coreos/etcd/cmd/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1340e00, 0xc4200827f8, 0xc42023fe01, 0xc42023fee0)
        /tmp/etcd-release-3.3.8/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/spf13/cobra/command.go:662 +0x357
github.com/coreos/etcd/cmd/vendor/github.com/spf13/cobra.(*Command).Execute(0x1340e00, 0x0, 0x0)
        /tmp/etcd-release-3.3.8/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/spf13/cobra/command.go:618 +0x2b
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdctl/ctlv3.Start()
        /tmp/etcd-release-3.3.8/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdctl/ctlv3/ctl_nocov.go:25 +0x8e
main.main()
        /tmp/etcd-release-3.3.8/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/etcdctl/main.go:40 +0x192
```

**Comment by serathius** [comment]
Etcd v3.3 is no longer supported. Please reproduce on newer versions.

**Comment by Koji-Study** [comment]
But it does not  work in Etcd v3.5

**Comment by serathius** [comment]
Please file a separate report for v3.5.
