### ISSUE TITLE
`TestCtlV3AuthGracefulDisable` always fails in Coverage workflow

### ISSUE THREAD

**Issue by ahrtr** [etcd-io/etcd#14926]
### Which github workflows are flaking?

`Coverage`

### Which tests are flaking?

`TestCtlV3AuthGracefulDisable`

### Github Action link

https://github.com/etcd-io/etcd/actions/runs/3666035308/jobs/6197499132

### Reason for failure (if possible)

```
   ctl_v3_auth_test.go:170: match not found.  Set EXPECT_DEBUG for more info Errs: [unexpected exit code [1] after running [/home/runner/work/etcd/etcd/bin/etcd_test grpc-proxy start --listen-addr localhost:20003 --endpoints http://localhost:20000 --advertise-client-url  --data-dir /tmp/TestCtlV3AuthGracefulDisable2565698461/002 --cert /home/runner/work/etcd/etcd/tests/fixtures/client-nocn.crt --key /home/runner/work/etcd/etcd/tests/fixtures/client-nocn.key.insecure --cacert /home/runner/work/etcd/etcd/tests/fixtures/ca.crt --client-crl-file /home/runner/work/etcd/etcd/tests/fixtures/revoke.crl -test.coverprofile=e2e.1670591664227553953.coverprofile -test.outputdir=/home/runner/work/etcd/etcd/covdir/e2e_proxy]], last lines:
        listen tcp 127.0.0.1:20003: bind: address already in use
        
    testutil.go:56: ---> Test failed: test timed out after 15s
    testutil.go:57: goroutine 558 [running]:
        go.etcd.io/etcd/client/pkg/v3/testutil.FatalStack(0xc0000164e0, {0xc000042738, 0x18})
        	/home/runner/work/etcd/etcd/client/pkg/testutil/testutil.go:55 +0x52
        go.etcd.io/etcd/tests/v3/e2e.runCtlTest(_, _, _, {0xc0000164e0, {0x0, 0x0}, {0x0, {0x0, 0x0}, {0x0, ...}, ...}, ...})
        	/home/runner/work/etcd/etcd/tests/e2e/ctl_v3_test.go:268 +0x29c
        go.etcd.io/etcd/tests/v3/e2e.testCtlWithOffline(0xc0000164e0, 0xec42d8?, 0x0, {0x0, 0x0, 0x0?})
        	/home/runner/work/etcd/etcd/tests/e2e/ctl_v3_test.go:240 +0x45b
        go.etcd.io/etcd/tests/v3/e2e.testCtl(...)
        	/home/runner/work/etcd/etcd/tests/e2e/ctl_v3_test.go:205
        go.etcd.io/etcd/tests/v3/e2e.TestCtlV3AuthGracefulDisable(0xc000064f60?)
        	/home/runner/work/etcd/etcd/tests/e2e/ctl_v3_auth_test.go:33 +0x29
        testing.tRunner(0xc0000164e0, 0xec3e60)
        	/opt/hostedtoolcache/go/1.19.4/x64/src/testing/testing.go:1446 +0x10b
        created by testing.(*T).Run
        	/opt/hostedtoolcache/go/1.19.4/x64/src/testing/testing.go:1493 +0x35f
```

**Comment by ahrtr** [comment]
cc @tjungblu

**Comment by tjungblu** [comment]
thanks @ahrtr, seems it's having trouble with already running processes taking that port?

>  last lines:
>       listen tcp 127.0.0.1:20003: bind: address already in use

**Comment by ahrtr** [comment]
> seems it's having trouble with already running processes taking that port?

Yes, could you or anyone take a deep dive into the issue?

**Comment by tjungblu** [comment]
sure, I can take a look if no one else wants to volunteer :)

**Comment by fuweid** [comment]
@ahrtr please assign it to me. I would like to handle this. Thanks!
