### ISSUE TITLE
Flaky test 

### ISSUE THREAD

**Issue by chaochn47** [etcd-io/etcd#15581]
### Which github workflows are flaking?

grpc-proxy e2e and e2e

### Which tests are flaking?

Both failed workflows are caused by `TestEtcdExampleConfig`. It does not make sense to 

```
2023-03-27T19:21:29.9968478Z --- FAIL: TestEtcdExampleConfig (0.03s)
2023-03-27T19:21:29.9969303Z     etcd_config_test.go:45: match not found.  Set EXPECT_DEBUG for more info Errs: [unexpected exit code [2] after running [/home/runner/work/etcd/etcd/bin/etcd --config-file ../../etcd.conf.yml.sample]], last lines:
2023-03-27T19:21:29.9969541Z         panic: failed to open database [recovered]
2023-03-27T19:21:29.9969746Z         	panic: failed to open database
```

### Github Action link

https://github.com/etcd-io/etcd/actions/runs/4535681729/jobs/7991430057?pr=15576

### Reason for failure (if possible)

Verification in embed server close function assumes db file in data directory exists. However, in this test, it may not be in some cases..

**Comment by fuweid** [comment]
It looks weird. The log shows `"dir-type":"empty"`.

```
2023-03-27T19:21:29.9933990Z /home/runner/work/etcd/etcd/bin/etcd (/home/runner/work/etcd/etcd/bin/etcd_--config-file_../../etcd.conf.yml.sample) (18712): 
{"level":"info","ts":"2023-03-27T19:18:46.893113Z","caller":"etcdmain/etcd.go:124","msg":"Initialize and start etcd server","data-dir":"default.etcd","dir-type":"empty"}
```

The **bootstrapBackend** checks it exists at first.

https://github.com/etcd-io/etcd/blob/e11a32366e05cc60e95a4e818f6745aa3113aaaf/server/etcdserver/bootstrap.go#L202

and bbolt uses O_CREAT to create if there is no db file.
What happened during creating?

**Comment by chaochn47** [comment]
From the stacktrace and the etcd server log after 

The failing starting point is `go.etcd.io/etcd/server/v3/embed/etcd.go:126`. 

Which is 
```
	if e.Peers, err = configurePeerListeners(cfg); err != nil {
		return e, err
	}
```
after `gh pr checkout 15576`

So even if with the PR https://github.com/etcd-io/etcd/pull/15582, it's likely the test still failed anyway. 

```
(18712): {"level":"info","ts":"2023-03-27T19:18:46.893175Z","caller":"embed/etcd.go:121","msg":"configuring peer listeners","listen-peer-urls":["http://localhost:2380"]}
(18712): {"level":"info","ts":"2023-03-27T19:18:46.893249Z","caller":"embed/etcd.go:392","msg":"closing etcd server","name":"default","data-dir":"default.etcd","advertise-peer-urls":["http://localhost:2380"],"advertise-client-urls":["http://localhost:2379"]}
```

```
(18712): panic: failed to open database [recovered]
(18712): 	panic: failed to open database
(18712): 
(18712): goroutine 1 [running]:
(18712): go.etcd.io/etcd/server/v3/verify.Verify.func1()
(18712): 	go.etcd.io/etcd/server/v3/verify/verify.go:66 +0x33d
(18712): panic({0x8aac1c0, 0x9813ce8})
(18712): 	runtime/panic.go:884 +0x1c3
(18712): go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x2, 0x9b72d20, {0x9c54c30, 0x2, 0x2})
(18712): 	go.uber.org/zap@v1.24.0/zapcore/entry.go:198 +0x71
(18712): go.uber.org/zap/zapcore.(*CheckedEntry).Write(0x9b72d20, {0x9c54c30, 0x2, 0x2})
(18712): 	go.uber.org/zap@v1.24.0/zapcore/entry.go:264 +0x37b
(18712): go.uber.org/zap.(*Logger).Panic(0x9890e00, {0x8bef2cc, 0x17}, {0x9c54c30, 0x2, 0x2})
(18712): 	go.uber.org/zap@v1.24.0/logger.go:258 +0x5e
(18712): go.etcd.io/etcd/server/v3/storage/backend.newBackend({{0x9c2d960, 0x1b}, 0x5f5e100, 0x2710, {0x0, 0x0}, 0x280000000, 0x9890e00, 0x0, 0x0, ...})
(18712): 	go.etcd.io/etcd/server/v3/storage/backend/backend.go:186 +0x24e
(18712): go.etcd.io/etcd/server/v3/storage/backend.NewDefaultBackend(0x9890e00, {0x9c2d960, 0x1b})
(18712): 	go.etcd.io/etcd/server/v3/storage/backend/backend.go:170 +0x9c
(18712): go.etcd.io/etcd/server/v3/verify.Verify({{0x983f540, 0xc}, 0x0, 0x9890e00})
(18712): 	go.etcd.io/etcd/server/v3/verify/verify.go:72 +0x2c1
(18712): go.etcd.io/etcd/server/v3/verify.VerifyIfEnabled({{0x983f540, 0xc}, 0x0, 0x9890e00})
(18712): 	go.etcd.io/etcd/server/v3/verify/verify.go:90 +0x59
(18712): go.etcd.io/etcd/server/v3/verify.MustVerifyIfEnabled({{0x983f540, 0xc}, 0x0, 0x9890e00})
(18712): 	go.etcd.io/etcd/server/v3/verify/verify.go:99 +0x51
(18712): go.etcd.io/etcd/server/v3/embed.(*Etcd).Close.func1()
(18712): 	go.etcd.io/etcd/server/v3/embed/etcd.go:395 +0x75
(18712): go.etcd.io/etcd/server/v3/embed.(*Etcd).Close(0x9a15000)
(18712): 	go.etcd.io/etcd/server/v3/embed/etcd.go:455 +0x658
(18712): go.etcd.io/etcd/server/v3/embed.StartEtcd.func1()
(18712): 	go.etcd.io/etcd/server/v3/embed/etcd.go:110 +0x79
(18712): go.etcd.io/etcd/server/v3/embed.StartEtcd(0x9c2ee00)
(18712): 	go.etcd.io/etcd/server/v3/embed/etcd.go:126 +0x6b7
(18712): go.etcd.io/etcd/server/v3/etcdmain.startEtcd(0x9c2ee00)
(18712): 	go.etcd.io/etcd/server/v3/etcdmain/etcd.go:206 +0x25
(18712): go.etcd.io/etcd/server/v3/etcdmain.startEtcdOrProxyV2({0x9894000, 0x3, 0x3})
(18712): 	go.etcd.io/etcd/server/v3/etcdmain/etcd.go:129 +0xf8f
(18712): go.etcd.io/etcd/server/v3/etcdmain.Main({0x9894000, 0x3, 0x3})
(18712): 	go.etcd.io/etcd/server/v3/etcdmain/main.go:40 +0x122
(18712): main.main()
(18712): 	go.etcd.io/etcd/server/v3/main.go:31 +0x37
```

**Comment by chaochn47** [comment]
<img width="957" alt="image" src="https://user-images.githubusercontent.com/54131596/229967705-0e9bb5e5-bc45-4f8c-ad7d-57002782b40b.png">

Aha, it is caused by pr https://github.com/etcd-io/etcd/pull/15576 introduced an unsupported cipher suites in commit https://github.com/etcd-io/etcd/commit/ce3273bcf900a4b7c228efea972f254b6b31055f

However, the `failed to open database` panic error message masked the original error. 

```
dev-dsk-chaochn-2c-a26acd76 % EXPECT_DEBUG=true go test -v -run TestEtcdExampleConfig
=== RUN   TestEtcdExampleConfig
/home/chaochn/workplace/EKS-etcd/src/EKS-etcd/bin/etcd (/home/chaochn/workplace/EKS-etcd/src/EKS-etcd/bin/etcd_--config-file_../../etcd.conf.yml.sample) (1583247): {"level":"warn","ts":"2023-04-05T02:42:07.142243Z","caller":"embed/config.go:790","msg":"it isn't recommended to use default name, please set a value for --name. Note that etcd might run into issue when multiple members have the same default name","name":"default"}
/home/chaochn/workplace/EKS-etcd/src/EKS-etcd/bin/etcd (/home/chaochn/workplace/EKS-etcd/src/EKS-etcd/bin/etcd_--config-file_../../etcd.conf.yml.sample) (1583247): {"level":"info","ts":"2023-04-05T02:42:07.142392Z","caller":"etcdmain/config.go:332","msg":"loaded server configuration, other configuration command line flags and environment variables will be ignored if provided","path":"../../etcd.conf.yml.sample"}
/home/chaochn/workplace/EKS-etcd/src/EKS-etcd/bin/etcd (/home/chaochn/workplace/EKS-etcd/src/EKS-etcd/bin/etcd_--config-file_../../etcd.conf.yml.sample) (1583247): {"level":"info","ts":"2023-04-05T02:42:07.142461Z","caller":"etcdmain/etcd.go:64","msg":"Running: ","args":["/home/chaochn/workplace/EKS-etcd/src/EKS-etcd/bin/etcd","--config-file","../../etcd.conf.yml.sample"]}
/home/chaochn/workplace/EKS-etcd/src/EKS-etcd/bin/etcd (/home/chaochn/workplace/EKS-etcd/src/EKS-etcd/bin/etcd_--config-file_../../etcd.conf.yml.sample) (1583247): {"level":"warn","ts":"2023-04-05T02:42:07.142569Z","caller":"etcdmain/etcd.go:96","msg":"'data-dir' was empty; using default","data-dir":"default.etcd"}
/home/chaochn/workplace/EKS-etcd/src/EKS-etcd/bin/etcd (/home/chaochn/workplace/EKS-etcd/src/EKS-etcd/bin/etcd_--config-file_../../etcd.conf.yml.sample) (1583247): {"level":"info","ts":"2023-04-05T02:42:07.142621Z","caller":"etcdmain/etcd.go:124","msg":"Initialize and start etcd server","data-dir":"default.etcd","dir-type":"empty"}
/home/chaochn/workplace/EKS-etcd/src/EKS-etcd/bin/etcd (/home/chaochn/workplace/EKS-etcd/src/EKS-etcd/bin/etcd_--config-file_../../etcd.conf.yml.sample) (1583247): {"level":"warn","ts":"2023-04-05T02:42:07.142678Z","caller":"embed/config.go:790","msg":"it isn't recommended to use default name, please set a value for --name. Note that etcd might run into issue when multiple members have the same default name","name":"default"}
/home/chaochn/workplace/EKS-etcd/src/EKS-etcd/bin/etcd (/home/chaochn/workplace/EKS-etcd/src/EKS-etcd/bin/etcd_--config-file_../../etcd.conf.yml.sample) (1583247): {"level":"info","ts":"2023-04-05T02:42:07.14274Z","caller":"embed/etcd.go:121","msg":"configuring peer listeners","listen-peer-urls":["http://localhost:2380"]}
/home/chaochn/workplace/EKS-etcd/src/EKS-etcd/bin/etcd (/home/chaochn/workplace/EKS-etcd/src/EKS-etcd/bin/etcd_--config-file_../../etcd.conf.yml.sample) (1583247): {"level":"info","ts":"2023-04-05T02:42:07.142825Z","caller":"embed/etcd.go:392","msg":"closing etcd server","name":"default","data-dir":"default.etcd","advertise-peer-urls":["http://localhost:2380"],"advertise-client-urls":["http://localhost:2379"]}
/home/chaochn/workplace/EKS-etcd/src/EKS-etcd/bin/etcd (/home/chaochn/workplace/EKS-etcd/src/EKS-etcd/bin/etcd_--config-file_../../etcd.conf.yml.sample) (1583247): {"level":"info","ts":"2023-04-05T02:42:07.142875Z","caller":"embed/etcd.go:394","msg":"closed etcd server","name":"default","data-dir":"default.etcd","advertise-peer-urls":["http://localhost:2380"],"advertise-client-urls":["http://localhost:2379"]}
/home/chaochn/workplace/EKS-etcd/src/EKS-etcd/bin/etcd (/home/chaochn/workplace/EKS-etcd/src/EKS-etcd/bin/etcd_--config-file_../../etcd.conf.yml.sample) (1583247): {"level":"fatal","ts":"2023-04-05T02:42:07.142931Z","caller":"etcdmain/etcd.go:182","msg":"discovery failed","error":"unexpected TLS cipher suite \"TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384\"","stacktrace":"go.etcd.io/etcd/server/v3/etcdmain.startEtcdOrProxyV2\n\t/home/chaochn/workplace/EKS-etcd/src/EKS-etcd/server/etcdmain/etcd.go:182\ngo.etcd.io/etcd/server/v3/etcdmain.Main\n\t/home/chaochn/workplace/EKS-etcd/src/EKS-etcd/server/etcdmain/main.go:40\nmain.main\n\t/home/chaochn/workplace/EKS-etcd/src/EKS-etcd/server/main.go:31\nruntime.main\n\t/home/chaochn/.gvm/gos/go1.19.7/src/runtime/proc.go:250"}
    etcd_config_test.go:45: match not found.  Set EXPECT_DEBUG for more info Errs: [unexpected exit code [1] after running [/home/chaochn/workplace/EKS-etcd/src/EKS-etcd/bin/etcd --config-file ../../etcd.conf.yml.sample]], last lines:
        {"level":"warn","ts":"2023-04-05T02:42:07.142243Z","caller":"embed/config.go:790","msg":"it isn't recommended to use default name, please set a value for --name. Note that etcd might run into issue when multiple members have the same default name","name":"default"}
        {"level":"info","ts":"2023-04-05T02:42:07.142392Z","caller":"etcdmain/config.go:332","msg":"loaded server configuration, other configuration command line flags and environment variables will be ignored if provided","path":"../../etcd.conf.yml.sample"}
        {"level":"info","ts":"2023-04-05T02:42:07.142461Z","caller":"etcdmain/etcd.go:64","msg":"Running: ","args":["/home/chaochn/workplace/EKS-etcd/src/EKS-etcd/bin/etcd","--config-file","../../etcd.conf.yml.sample"]}
        {"level":"warn","ts":"2023-04-05T02:42:07.142569Z","caller":"etcdmain/etcd.go:96","msg":"'data-dir' was empty; using default","data-dir":"default.etcd"}
        {"level":"info","ts":"2023-04-05T02:42:07.142621Z","caller":"etcdmain/etcd.go:124","msg":"Initialize and start etcd server","data-dir":"default.etcd","dir-type":"empty"}
        {"level":"warn","ts":"2023-04-05T02:42:07.142678Z","caller":"embed/config.go:790","msg":"it isn't recommended to use default name, please set a value for --name. Note that etcd might run into issue when multiple members have the same default name","name":"default"}
        {"level":"info","ts":"2023-04-05T02:42:07.14274Z","caller":"embed/etcd.go:121","msg":"configuring peer listeners","listen-peer-urls":["http://localhost:2380"]}
        {"level":"info","ts":"2023-04-05T02:42:07.142825Z","caller":"embed/etcd.go:392","msg":"closing etcd server","name":"default","data-dir":"default.etcd","advertise-peer-urls":["http://localhost:2380"],"advertise-client-urls":["http://localhost:2379"]}
        {"level":"info","ts":"2023-04-05T02:42:07.142875Z","caller":"embed/etcd.go:394","msg":"closed etcd server","name":"default","data-dir":"default.etcd","advertise-peer-urls":["http://localhost:2380"],"advertise-client-urls":["http://localhost:2379"]}
        {"level":"fatal","ts":"2023-04-05T02:42:07.142931Z","caller":"etcdmain/etcd.go:182","msg":"discovery failed","error":"unexpected TLS cipher suite \"TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384\"","stacktrace":"go.etcd.io/etcd/server/v3/etcdmain.startEtcdOrProxyV2\n\t/home/chaochn/workplace/EKS-etcd/src/EKS-etcd/server/etcdmain/etcd.go:182\ngo.etcd.io/etcd/server/v3/etcdmain.Main\n\t/home/chaochn/workplace/EKS-etcd/src/EKS-etcd/server/etcdmain/main.go:40\nmain.main\n\t/home/chaochn/workplace/EKS-etcd/src/EKS-etcd/server/main.go:31\nruntime.main\n\t/home/chaochn/.gvm/gos/go1.19.7/src/runtime/proc.go:250"}

--- FAIL: TestEtcdExampleConfig (0.06s)
FAIL
exit status 1
FAIL	go.etcd.io/etcd/tests/v3/e2e	0.079s
```

PTAL if it makes sense to you @fuweid /cc @jmhbnz

**Comment by ahrtr** [comment]
Thanks @chaochn47 . Why the PR https://github.com/etcd-io/etcd/pull/15576 passed all test?

**Comment by chaochn47** [comment]
The unsupported cipher suite is removed in the next commit~

**Comment by jmhbnz** [comment]
Wow good find @chaochn47.  I was pretty confused by the database panic error in the logs and had just guessed that maybe I didn't have the ciphers quite right. I wasn't 100% sure if the problems were related but I think this confirms the hunch!

**Comment by fuweid** [comment]
@chaochn47 Thanks for the hint! I misread the strace. It makes sense.

> "msg":"discovery failed","error":"unexpected TLS cipher suite \"TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384\""

```
$  git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 upstream +fa8720ebbba0c68676567eb02b7d247ef7e0af90:refs/remotes/pull/15576/merge
$ git checkout --progress --force refs/remotes/pull/15576/merge
$ ETCD_VERIFY=all EXPECT_DEBUG=true go test -v -run TestEtcdExampleConfig

...

/home/fuwei/go/src/go.etcd.io/etcd/bin/etcd (/home/fuwei/go/src/go.etcd.io/etcd/bin/etcd_--config-file_../../etcd.conf.yml.sample) (587264):    go.etcd.io/etcd/server/v3/main.go:31 +0x2e
    etcd_config_test.go:45: match not found.  Set EXPECT_DEBUG for more info Errs: [unexpected exit code [2] after running [/home/fuwei/go/src/go.etcd.io/etcd/bin/etcd --config-file ../../etcd.conf.yml.sample]], last lines:
        panic: failed to open database [recovered]
                panic: failed to open database

        goroutine 1 [running]:
        go.etcd.io/etcd/server/v3/verify.Verify.func1()
                go.etcd.io/etcd/server/v3/verify/verify.go:66 +0x44d
        panic({0xeb8fe0, 0xc000502630})
                runtime/panic.go:884 +0x212
        go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x2?, 0x180?, {0x0?, 0x0?, 0xc000536a20?})
                go.uber.org/zap@v1.24.0/zapcore/entry.go:198 +0x65
        go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0004909c0, {0xc000022080, 0x2, 0x2})
                go.uber.org/zap@v1.24.0/zapcore/entry.go:264 +0x3ec
        go.uber.org/zap.(*Logger).Panic(0xc00051c3a0?, {0x1072d8a?, 0xc000512198?}, {0xc000022080, 0x2, 0x2})
                go.uber.org/zap@v1.24.0/logger.go:258 +0x59
        go.etcd.io/etcd/server/v3/storage/backend.newBackend({{0xc00051c3a0, 0x1b}, 0x5f5e100, 0x2710, {0x0, 0x0}, 0x280000000, 0xc00056f0a0, 0x0, 0x0, ...})
                go.etcd.io/etcd/server/v3/storage/backend/backend.go:186 +0x2ff
        go.etcd.io/etcd/server/v3/storage/backend.NewDefaultBackend(0xc000228b40?, {0xc00051c3a0?, 0xc0002ea5e0?})
                go.etcd.io/etcd/server/v3/storage/backend/backend.go:170 +0xc5
        go.etcd.io/etcd/server/v3/verify.Verify({{0xc000228b40?, 0xc000012018?}, 0xf0?, 0xc00056f0a0?})
                go.etcd.io/etcd/server/v3/verify/verify.go:72 +0x325
        go.etcd.io/etcd/server/v3/verify.VerifyIfEnabled({{0xc000228b40?, 0x0?}, 0x0?, 0xc00056f0a0?})
                go.etcd.io/etcd/server/v3/verify/verify.go:91 +0xa5
        go.etcd.io/etcd/server/v3/verify.MustVerifyIfEnabled({{0xc000228b40?, 0x106c945?}, 0x20?, 0xc00056f0a0?})
                go.etcd.io/etcd/server/v3/verify/verify.go:100 +0x4d
        go.etcd.io/etcd/server/v3/embed.(*Etcd).Close.func1()
                go.etcd.io/etcd/server/v3/embed/etcd.go:395 +0x5e
        go.etcd.io/etcd/server/v3/embed.(*Etcd).Close(0xc00045e700)
                go.etcd.io/etcd/server/v3/embed/etcd.go:455 +0x7fc
        go.etcd.io/etcd/server/v3/embed.StartEtcd.func1()
                go.etcd.io/etcd/server/v3/embed/etcd.go:110 +0x9f
        go.etcd.io/etcd/server/v3/embed.StartEtcd(0xc0000a8a00)
                go.etcd.io/etcd/server/v3/embed/etcd.go:126 +0x73f
        go.etcd.io/etcd/server/v3/etcdmain.startEtcd(0xc0000a8a00)
                go.etcd.io/etcd/server/v3/etcdmain/etcd.go:206 +0x33
        go.etcd.io/etcd/server/v3/etcdmain.startEtcdOrProxyV2({0xc00003e090, 0x3, 0x3})
                go.etcd.io/etcd/server/v3/etcdmain/etcd.go:129 +0x115b
        go.etcd.io/etcd/server/v3/etcdmain.Main({0xc00003e090?, 0x3, 0x3})
                go.etcd.io/etcd/server/v3/etcdmain/main.go:40 +0x10c
        main.main()
                go.etcd.io/etcd/server/v3/main.go:31 +0x2e

--- FAIL: TestEtcdExampleConfig (0.02s)
FAIL
exit status 1
FAIL    go.etcd.io/etcd/tests/v3/e2e    0.032s
```
