### ISSUE TITLE
GODEBUG=gcstoptheworld=2 causing fatal error when trying to run etcd/contrib/lock demo

### ISSUE THREAD

**Issue by STX5** [etcd-io/etcd#15613]
### What happened?

I try to run the demo code provided at `etcd/contrib/lock` to learn about the distributed lock design of ETCD. 
I follow the instruction to run `client 1`  with commad:
```sh
$ GODEBUG=gcstoptheworld=2 ./client 1
```
which will make the process to cause `stop the world GC` pause for making lease expiration intentionally.
How ever, I get outputs like this :
```sh 
client 1 starts
creted etcd client
fatal error: failed to set sweep barrier

goroutine 71 [running]:
runtime.throw({0xb0e27a?, 0x4d3d7549247a?})
        /usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0xc00041c518 sp=0xc00041c4e8 pc=0x436c1d
runtime.gcMarkTermination()
        /usr/local/go/src/runtime/mgc.go:1087 +0xd45 fp=0xc00041c6f0 sp=0xc00041c518 pc=0x41c805
runtime.gcMarkDone()
        /usr/local/go/src/runtime/mgc.go:918 +0x2d3 fp=0xc00041c750 sp=0xc00041c6f0 pc=0x41b9b3
runtime.gcBgMarkWorker()
        /usr/local/go/src/runtime/mgc.go:1407 +0x345 fp=0xc00041c7e0 sp=0xc00041c750 pc=0x41cc45
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00041c7e8 sp=0xc00041c7e0 pc=0x4685c1
created by runtime.gcBgMarkStartWorkers
        /usr/local/go/src/runtime/mgc.go:1199 +0x25
...
...
...
goroutine 50 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x20?, 0x36?, 0xc00007af50?)
        /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc00007af50 sp=0xc00007af30 pc=0x439936
runtime.gcBgMarkWorker()
        /usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc00007afe0 sp=0xc00007af50 pc=0x41c9f1
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00007afe8 sp=0xc00007afe0 pc=0x4685c1
created by runtime.gcBgMarkStartWorkers
        /usr/local/go/src/runtime/mgc.go:1199 +0x25
...
...
...
goroutine 71 [GC worker (idle)]:
runtime.gopark(0x1044f20?, 0x1?, 0x1e?, 0xb3?, 0x0?)
        /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc0004b1f50 sp=0xc0004b1f30 pc=0x439936
runtime.gcBgMarkWorker()
        /usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0004b1fe0 sp=0xc0004b1f50 pc=0x41c9f1
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0004b1fe8 sp=0xc0004b1fe0 pc=0x4685c1
created by runtime.gcBgMarkStartWorkers
        /usr/local/go/src/runtime/mgc.go:1199 +0x25
s
```
since the full error message is too long(over 1600line), I can not paste the full error message here.

### What did you expect to happen?

I expect no fatal error.

### How can we reproduce it (as minimally and precisely as possible)?

run the `/etcd/contrib/lock/client` demo 

### Anything else we need to know?

I'm using go1.20, My GO ENV:
```sh
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/stx5/.cache/go-build"
GOENV="/home/stx5/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/stx5/Applications/Go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/stx5/Applications/Go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/stx5/etcd/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build144938580=/tmp/go-build -gno-record-gcc-switches"
```

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
etcd Version: 3.5.0
Git SHA: 946a5a6f2
Go Version: go1.19.2
Go OS/Arch: linux/amd64
$ etcdctl version
etcdctl version: 3.5.0
API version: 3.5
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by mitake** [comment]
@STX5  Could you check that it's possible to reproduce the issue without `GODEBUG=gcstoptheworld=2` or different versions of go?

**Comment by STX5** [comment]
> @STX5 Could you check that it's possible to reproduce the issue without `GODEBUG=gcstoptheworld=2` or different versions of go?

I can run the demo without `GODEBUG=gcstoptheworld=2`, but the program won't act as expected.
Actually client 1 will success, and client 2 will fail
client1:
```sh
resuming client 1
successfully write a key to storage
```
client2:
```sh
client 2 starts
creted etcd client
acquired lock, version: 4703595595336117001
this is client 2, continuing
failed to write to storage: error: given version (4703595595336117001) is different from the existing version (1029221249355213574)
```

**Comment by mitake** [comment]
I had been unaware but the example was changed for not relying on go's gc: https://github.com/etcd-io/etcd/tree/main/contrib/lock
For trying it, we should revoke the target lease manually.
Also let me drop the `type/bug` label, it's not a bug of etcd itself.
