### ISSUE TITLE
Improve "Not a File" error message

### ISSUE THREAD

**Issue by robszumski** [etcd-io/etcd#169]
When you try to write a value to an existing directory, you receive a "Not a File" message. Ideally this should say something more descriptive about the error, like "Value already exists as directory".

**Comment by bearrito** [comment]
Still seems to be an issue.

```
Traceback (most recent call last):
  File "/home/barrett/Installers/pycharm-4.5.4/helpers/pydev/pydevd.py", line 2358, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/barrett/Installers/pycharm-4.5.4/helpers/pydev/pydevd.py", line 1778, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/barrett/Git/Analytics/src/bnr_planogram_generation/src/bnr_planogram_generation/service_registration.py", line 67, in <module>
    client.write('/robot/metrics', None, dir=True)
  File "/home/barrett/.virtualenvs/ipc/local/lib/python2.7/site-packages/python_etcd-0.4.3-py2.7.egg/etcd/client.py", line 461, in write
    response = self.api_execute(path, method, params=params)
  File "/home/barrett/.virtualenvs/ipc/local/lib/python2.7/site-packages/python_etcd-0.4.3-py2.7.egg/etcd/client.py", line 848, in wrapper
    return self._handle_server_response(response)
  File "/home/barrett/.virtualenvs/ipc/local/lib/python2.7/site-packages/python_etcd-0.4.3-py2.7.egg/etcd/client.py", line 928, in _handle_server_response
    etcd.EtcdError.handle(r)
  File "/home/barrett/.virtualenvs/ipc/local/lib/python2.7/site-packages/python_etcd-0.4.3-py2.7.egg/etcd/__init__.py", line 304, in handle
    raise exc(msg, payload)
etcd.EtcdNotFile: Not a file : /robot/metrics```

The `/robot/metrics` directory already exists.

Server is version 2.2.2
Client is latest from https://github.com/jplana/python-etcd

**Comment by baerree** [comment]
Yep Still an issue with version: `{"etcdserver":"3.3.8","etcdcluster":"3.3.0"}`

```
λ docker container run --name etcdconfigwriter etcdconfigwriter:008
2019/02/18 16:26:35 Current Service {"itemservice" map["service-ID":"ItSe8923578923" "operationMode":"QA" "version":"3.0.0" "label":"C3PO"]}
2019/02/18 16:26:35 Error: "102: Not a file (/itemservice) [22]"
```

This happens if itemservice directory already exists.

Cheers
