### ISSUE TITLE
etcd3 and livekit compatibility issues

### ISSUE THREAD

**Issue by zhushixia** [etcd-io/etcd#19106]
### Bug report criteria

- [ ] This bug report is not security related, security issues should be disclosed privately via [etcd maintainers](mailto:etcd-maintainers@googlegroups.com).
- [ ] This is not a support request or question, support requests or questions should be raised in the etcd [discussion forums](https://github.com/etcd-io/etcd/discussions).
- [ ] You have read the etcd [bug reporting guidelines](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/reporting_bugs.md).
- [ ] Existing open issues along with etcd [frequently asked questions](https://etcd.io/docs/latest/faq) have been checked and this is not a duplicate.

### What happened?

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/zhushixia/project/odd-agent/public/utils.py", line 18, in <module>
    from public.common.etcd_tool import EtcdConnectionPool
  File "/home/zhushixia/project/odd-agent/public/common/etcd_tool.py", line 1, in <module>
    import etcd3
  File "/home/zhushixia/env/anaconda3/envs/odd/lib/python3.10/site-packages/etcd3/__init__.py", line 3, in <module>
    import etcd3.etcdrpc as etcdrpc
  File "/home/zhushixia/env/anaconda3/envs/odd/lib/python3.10/site-packages/etcd3/etcdrpc/__init__.py", line 1, in <module>
    from .rpc_pb2 import *
  File "/home/zhushixia/env/anaconda3/envs/odd/lib/python3.10/site-packages/etcd3/etcdrpc/rpc_pb2.py", line 20, in <module>
    DESCRIPTOR = _descriptor.FileDescriptor(
  File "/home/zhushixia/env/anaconda3/envs/odd/lib/python3.10/site-packages/google/protobuf/descriptor.py", line 1024, in __new__
    return _message.default_pool.AddSerializedFile(serialized_pb)
TypeError: Couldn't build proto file into descriptor pool!
Invalid proto descriptor for file "rpc.proto":
  rpc.proto: A file with this name is already in the pool.

### What did you expect to happen?

etcd3 and livekit compatibility

### How can we reproduce it (as minimally and precisely as possible)?

python with livekit==0.18.3 and etcd3==0.12.0

### Etcd version (please run commands below)

etcd3==0.12.0

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by kevburnsjr** [comment]
This sounds like an issue with the python client.
I don't think any commit made to this repository will resolve your issue. 

Recommend filing an issue there:
https://github.com/kragniz/python-etcd3/issues

**Comment by jmhbnz** [comment]
Closing - We do not provide support here for the python etcd client. Please raise an issue against https://github.com/kragniz/python-etcd3 as mentioned above.
