### ISSUE TITLE
Joining a cluster crashes leader with leader.elected.at.same.term.0

### ISSUE THREAD

**Issue by aphyr** [etcd-io/etcd#715]
From git master, on Debian Jessie, launching a fresh instance of etcd on one node (n1), and then starting a fresh node (n2) with n1 as its peer crashes n1, the leader, with `panic: assertion failed: leader.elected.at.same.term.0`.

Running a single node works fine, but the crash on join is reliably reproducible. I've verified there are no other etcd instances running in the cluster. The only hit in Google for that message is from the etcd source, and so far all the other getting-started steps have worked fine. Thoughts?

```
ubuntu@n1:/opt/etcd$ sudo rm -rf /var/lib/etcd/
ubuntu@n1:/opt/etcd$ sudo bin/etcd -peer-addr 0.0.0.0:7001 -addr 0.0.0.0:4001 -data-dir /var/lib/etcd -name n1
[etcd] Apr 13 17:56:48.860 INFO      | etcd server [name n1, listen on :4001, advertised url http://0.0.0.0:4001]
[etcd] Apr 13 17:56:48.862 INFO      | URLs: /_etcd/machines:  / n1 ()
[etcd] Apr 13 17:56:48.862 INFO      | This peer is starting a brand new cluster now.
[etcd] Apr 13 17:56:48.862 INFO      | n1: state changed from 'initialized' to 'follower'.
[etcd] Apr 13 17:56:48.862 INFO      | n1: state changed from 'follower' to 'leader'.
[etcd] Apr 13 17:56:48.862 INFO      | n1: leader changed from '' to 'n1'.
[etcd] Apr 13 17:56:48.893 INFO      | peer server [name n1, listen on :7001, advertised url http://0.0.0.0:7001]
```

```
ubuntu@n2:/opt/etcd$ sudo rm -rf /var/lib/etcd/
ubuntu@n2:/opt/etcd$ sudo bin/etcd -peer-addr 0.0.0.0:7001 -addr 0.0.0.0:4001 -data-dir /var/lib/etcd -name n2 -peers n1:7001
[etcd] Apr 13 17:58:33.005 INFO      | etcd server [name n2, listen on :4001, advertised url http://0.0.0.0:4001]
[etcd] Apr 13 17:58:33.008 INFO      | URLs: /_etcd/machines:  / n2 ()
[etcd] Apr 13 17:58:33.011 INFO      | Send Join Request to http://n1:7001/v2/admin/machines/n2
[etcd] Apr 13 17:58:33.073 INFO      | »»»» 200
[etcd] Apr 13 17:58:33.073 INFO      | n2: state changed from 'initialized' to 'follower'.
[etcd] Apr 13 17:58:33.074 INFO      | peer server [name n2, listen on :7001, advertised url http://0.0.0.0:7001
```

```
[etcd] Apr 13 17:56:57.356 INFO      | n1: peer added: 'n2'
panic: assertion failed: leader.elected.at.same.term.0


goroutine 6 [running]:
runtime.panic(0x730820, 0xc2100e1910)
        /usr/lib/go/src/pkg/runtime/panic.c:266 +0xb6
github.com/coreos/etcd/third_party/github.com/goraft/raft._assert(0x869d00, 0x8d6e10, 0x1f, 0x7f8199ae3cc8, 0x1, ...)
        /opt/etcd/src/github.com/coreos/etcd/third_party/github.com/goraft/raft/util.go:60 +0xcb
github.com/coreos/etcd/third_party/github.com/goraft/raft.(*server).processAppendEntriesRequest(0xc210052ea0, 0xc2100a7e10, 0xc2100a7e10, 0xc2100a7e10)
        /opt/etcd/src/github.com/coreos/etcd/third_party/github.com/goraft/raft/server.go:936 +0x355
github.com/coreos/etcd/third_party/github.com/goraft/raft.(*server).leaderLoop(0xc210052ea0)
        /opt/etcd/src/github.com/coreos/etcd/third_party/github.com/goraft/raft/server.go:837 +0x5c1
github.com/coreos/etcd/third_party/github.com/goraft/raft.(*server).loop(0xc210052ea0)
        /opt/etcd/src/github.com/coreos/etcd/third_party/github.com/goraft/raft/server.go:605 +0x3a0
github.com/coreos/etcd/third_party/github.com/goraft/raft.func·007()
        /opt/etcd/src/github.com/coreos/etcd/third_party/github.com/goraft/raft/server.go:468 +0x5c
created by github.com/coreos/etcd/third_party/github.com/goraft/raft.(*server).Start
        /opt/etcd/src/github.com/coreos/etcd/third_party/github.com/goraft/raft/server.go:469 +0x3c0

goroutine 1 [IO wait]:
net.runtime_pollWait(0x7f8199c68300, 0x72, 0x0)
        /usr/lib/go/src/pkg/runtime/netpoll.goc:116 +0x6a
net.(*pollDesc).Wait(0xc21004a840, 0x72, 0x7f8199c670e8, 0xb)
        /usr/lib/go/src/pkg/net/fd_poll_runtime.go:81 +0x34
net.(*pollDesc).WaitRead(0xc21004a840, 0xb, 0x7f8199c670e8)
        /usr/lib/go/src/pkg/net/fd_poll_runtime.go:86 +0x30
net.(*netFD).accept(0xc21004a7e0, 0x942708, 0x0, 0x7f8199c670e8, 0xb)
        /usr/lib/go/src/pkg/net/fd_unix.go:382 +0x2c2
net.(*TCPListener).AcceptTCP(0xc210000478, 0x18, 0xc21003a010, 0x5138d3)
        /usr/lib/go/src/pkg/net/tcpsock_posix.go:233 +0x47
net.(*TCPListener).Accept(0xc210000478, 0x50, 0xe2bb00, 0x18, 0x0)
        /usr/lib/go/src/pkg/net/tcpsock_posix.go:243 +0x27
net/http.(*Server).Serve(0xc2100c7550, 0x7f8199c691d0, 0xc210000478, 0x0, 0x0)
        /usr/lib/go/src/pkg/net/http/server.go:1622 +0x91
net/http.Serve(0x7f8199c691d0, 0xc210000478, 0x7f8199c693a0, 0xc2100bdec0, 0x0, ...)
        /usr/lib/go/src/pkg/net/http/server.go:1561 +0x70
github.com/coreos/etcd/etcd.(*Etcd).Run(0xc210050540)
        /opt/etcd/src/github.com/coreos/etcd/etcd/etcd.go:213 +0x1d8f
main.main()
        /opt/etcd/src/github.com/coreos/etcd/main.go:43 +0x2b2

goroutine 4 [syscall]:
os/signal.loop()
        /usr/lib/go/src/pkg/os/signal/signal_unix.go:21 +0x1e
created by os/signal.init·1
        /usr/lib/go/src/pkg/os/signal/signal_unix.go:27 +0x31

goroutine 5 [IO wait]:
net.runtime_pollWait(0x7f8199c68258, 0x72, 0x0)
        /usr/lib/go/src/pkg/runtime/netpoll.goc:116 +0x6a
net.(*pollDesc).Wait(0xc2100cd4c0, 0x72, 0x7f8199c670e8, 0xb)
        /usr/lib/go/src/pkg/net/fd_poll_runtime.go:81 +0x34
net.(*pollDesc).WaitRead(0xc2100cd4c0, 0xb, 0x7f8199c670e8)
        /usr/lib/go/src/pkg/net/fd_poll_runtime.go:86 +0x30
net.(*netFD).accept(0xc2100cd460, 0x942708, 0x0, 0x7f8199c670e8, 0xb)
        /usr/lib/go/src/pkg/net/fd_unix.go:382 +0x2c2
net.(*TCPListener).AcceptTCP(0xc2100002f0, 0x513afb, 0x7f8199adfde0, 0x513afb)
        /usr/lib/go/src/pkg/net/tcpsock_posix.go:233 +0x47
net.(*TCPListener).Accept(0xc2100002f0, 0x7f8199c698d0, 0xc2100dd490, 0xc210058280, 0x0)
        /usr/lib/go/src/pkg/net/tcpsock_posix.go:243 +0x27
net/http.(*Server).Serve(0xc2100c72d0, 0x7f8199c691d0, 0xc2100002f0, 0x0, 0x0)
        /usr/lib/go/src/pkg/net/http/server.go:1622 +0x91
net/http.Serve(0x7f8199c691d0, 0xc2100002f0, 0x7f8199c693a0, 0xc210064800, 0x0, ...)
        /usr/lib/go/src/pkg/net/http/server.go:1561 +0x70
github.com/coreos/etcd/etcd.func·001()
        /opt/etcd/src/github.com/coreos/etcd/etcd/etcd.go:204 +0x345
created by github.com/coreos/etcd/etcd.(*Etcd).Run
        /opt/etcd/src/github.com/coreos/etcd/etcd/etcd.go:210 +0x1c8e

goroutine 8 [select]:
github.com/coreos/etcd/third_party/github.com/goraft/raft.(*server).send(0xc210052ea0, 0x7e0fc0, 0xc2100e3ea0, 0xc2100e3ea0, 0xecadcc6e9, ...)
        /opt/etcd/src/github.com/coreos/etcd/third_party/github.com/goraft/raft/server.go:622 +0x1bc
github.com/coreos/etcd/third_party/github.com/goraft/raft.(*server).Do(0xc210052ea0, 0x7f8199c68640, 0xc2100e3ea0, 0xe20b80, 0x7f8199c68640, ...)
        /opt/etcd/src/github.com/coreos/etcd/third_party/github.com/goraft/raft/server.go:885 +0x58
github.com/coreos/etcd/server.(*PeerServer).monitorSync(0xc2100a1000)
        /opt/etcd/src/github.com/coreos/etcd/server/peer_server.go:640 +0x15e
created by github.com/coreos/etcd/server.(*PeerServer).Start
        /opt/etcd/src/github.com/coreos/etcd/server/peer_server.go:298 +0x1aa

goroutine 9 [select]:
github.com/coreos/etcd/server.(*PeerServer).monitorTimeoutThreshold(0xc2100a1000, 0xc2100c3d20)
        /opt/etcd/src/github.com/coreos/etcd/server/peer_server.go:650 +0x1a8
created by github.com/coreos/etcd/server.(*PeerServer).Start
        /opt/etcd/src/github.com/coreos/etcd/server/peer_server.go:299 +0x1d0

goroutine 10 [select]:
github.com/coreos/etcd/server.(*PeerServer).monitorActiveSize(0xc2100a1000, 0xc2100c3d20)
        /opt/etcd/src/github.com/coreos/etcd/server/peer_server.go:665 +0xeb4
created by github.com/coreos/etcd/server.(*PeerServer).Start
        /opt/etcd/src/github.com/coreos/etcd/server/peer_server.go:300 +0x1f6

goroutine 11 [select]:
github.com/coreos/etcd/server.(*PeerServer).monitorPeerActivity(0xc2100a1000, 0xc2100c3d20)
        /opt/etcd/src/github.com/coreos/etcd/server/peer_server.go:727 +0x632
created by github.com/coreos/etcd/server.(*PeerServer).Start
        /opt/etcd/src/github.com/coreos/etcd/server/peer_server.go:301 +0x21c

goroutine 12 [sleep]:
time.Sleep(0xb2d05e00)
        /usr/lib/go/src/pkg/runtime/time.goc:31 +0x31
github.com/coreos/etcd/server.(*PeerServer).monitorSnapshot(0xc2100a1000)
        /opt/etcd/src/github.com/coreos/etcd/server/peer_server.go:623 +0x31
created by github.com/coreos/etcd/server.(*PeerServer).Start
        /opt/etcd/src/github.com/coreos/etcd/server/peer_server.go:305 +0x23d

goroutine 19 [select]:
github.com/coreos/etcd/third_party/github.com/goraft/raft.(*server).send(0xc210052ea0, 0x7e1500, 0xc2100a7e10, 0x52b, 0xecadcc6e9, ...)
        /opt/etcd/src/github.com/coreos/etcd/third_party/github.com/goraft/raft/server.go:622 +0x1bc
github.com/coreos/etcd/third_party/github.com/goraft/raft.(*server).AppendEntries(0xc210052ea0, 0xc2100a7e10, 0x2)
        /opt/etcd/src/github.com/coreos/etcd/third_party/github.com/goraft/raft/server.go:921 +0x3b
github.com/coreos/etcd/server.(*PeerServer).AppendEntriesHttpHandler(0xc2100a1000, 0x7f8199c69a28, 0xc2100ea140, 0xc2100dadd0)
        /opt/etcd/src/github.com/coreos/etcd/server/peer_server_handlers.go:69 +0x3af
github.com/coreos/etcd/server.*PeerServer.AppendEntriesHttpHandler·fm(0x7f8199c69a28, 0xc2100ea140, 0xc2100dadd0)
        /opt/etcd/src/github.com/coreos/etcd/server/peer_server.go:332 +0x44
net/http.HandlerFunc.ServeHTTP(0xc2100a63c0, 0x7f8199c69a28, 0xc2100ea140, 0xc2100dadd0)
        /usr/lib/go/src/pkg/net/http/server.go:1220 +0x40
github.com/coreos/etcd/third_party/github.com/gorilla/mux.(*Router).ServeHTTP(0xc2100c78c0, 0x7f8199c69a28, 0xc2100ea140, 0xc2100dadd0)
        /opt/etcd/src/github.com/coreos/etcd/third_party/github.com/gorilla/mux/mux.go:98 +0x217
github.com/coreos/etcd/http.(*CORSHandler).ServeHTTP(0xc210064800, 0x7f8199c69a28, 0xc2100ea140, 0xc2100dadd0)
        /opt/etcd/src/github.com/coreos/etcd/http/cors.go:74 +0x1a0
net/http.serverHandler.ServeHTTP(0xc2100c72d0, 0x7f8199c69a28, 0xc2100ea140, 0xc2100dadd0)
        /usr/lib/go/src/pkg/net/http/server.go:1597 +0x16e
net/http.(*conn).serve(0xc210058280)
        /usr/lib/go/src/pkg/net/http/server.go:1167 +0x7b7
created by net/http.(*Server).Serve
        /usr/lib/go/src/pkg/net/http/server.go:1644 +0x28b

goroutine 15 [select]:
net/http.(*persistConn).roundTrip(0xc210058700, 0xc2100e1560, 0xc210058700, 0x0, 0x0)
        /usr/lib/go/src/pkg/net/http/transport.go:879 +0x6d6
net/http.(*Transport).RoundTrip(0xc210058500, 0xc2100dac30, 0xc2100de700, 0x0, 0x0)
        /usr/lib/go/src/pkg/net/http/transport.go:187 +0x391
github.com/coreos/etcd/third_party/github.com/mreiferson/go-httpclient.(*Transport).RoundTrip(0xc210050660, 0xc2100dac30, 0x1, 0x0, 0x0)
        /opt/etcd/src/github.com/coreos/etcd/third_party/github.com/mreiferson/go-httpclient/httpclient.go:167 +0x13b
net/http.send(0xc2100dac30, 0x7f8199c68f10, 0xc210050660, 0x0, 0x0, ...)
        /usr/lib/go/src/pkg/net/http/client.go:168 +0x37f
net/http.(*Client).send(0xc21009b7b0, 0xc2100dac30, 0x1e, 0xc2100e7420, 0xc2100e1540)
        /usr/lib/go/src/pkg/net/http/client.go:100 +0xd9
net/http.(*Client).doFollowingRedirects(0xc21009b7b0, 0xc2100dac30, 0x9436d0, 0x0, 0x0, ...)
        /usr/lib/go/src/pkg/net/http/client.go:294 +0x671
net/http.(*Client).Do(0xc21009b7b0, 0xc2100dac30, 0xc2100e3f40, 0x0, 0x0)
        /usr/lib/go/src/pkg/net/http/client.go:132 +0x157
github.com/coreos/etcd/server.(*transporter).Post(0xc21009d100, 0xc2100e3f40, 0x1e, 0x7f8199c69d30, 0xc2100af700, ...)
        /opt/etcd/src/github.com/coreos/etcd/server/transporter.go:239 +0x82
github.com/coreos/etcd/server.(*transporter).SendAppendEntriesRequest(0xc21009d100, 0x7f8199c68fa8, 0xc210052ea0, 0xc2100af460, 0xc2100a7dc0, ...)
        /opt/etcd/src/github.com/coreos/etcd/server/transporter.go:112 +0x532
github.com/coreos/etcd/third_party/github.com/goraft/raft.(*Peer).sendAppendEntriesRequest(0xc2100af460, 0xc2100a7dc0)
        /opt/etcd/src/github.com/coreos/etcd/third_party/github.com/goraft/raft/peer.go:189 +0x209
github.com/coreos/etcd/third_party/github.com/goraft/raft.(*Peer).flush(0xc2100af460)
        /opt/etcd/src/github.com/coreos/etcd/third_party/github.com/goraft/raft/peer.go:174 +0x250
github.com/coreos/etcd/third_party/github.com/goraft/raft.(*Peer).heartbeat(0xc2100af460, 0xc2100d9960)
        /opt/etcd/src/github.com/coreos/etcd/third_party/github.com/goraft/raft/peer.go:159 +0x480
github.com/coreos/etcd/third_party/github.com/goraft/raft.func·005()
        /opt/etcd/src/github.com/coreos/etcd/third_party/github.com/goraft/raft/peer.go:95 +0x75
created by github.com/coreos/etcd/third_party/github.com/goraft/raft.(*Peer).startHeartbeat
        /opt/etcd/src/github.com/coreos/etcd/third_party/github.com/goraft/raft/peer.go:96 +0xfb

goroutine 17 [IO wait]:
net.runtime_pollWait(0x7f8199c681b0, 0x72, 0x0)
        /usr/lib/go/src/pkg/runtime/netpoll.goc:116 +0x6a
net.(*pollDesc).Wait(0xc2100af8b0, 0x72, 0x7f8199c670e8, 0xb)
        /usr/lib/go/src/pkg/net/fd_poll_runtime.go:81 +0x34
net.(*pollDesc).WaitRead(0xc2100af8b0, 0xb, 0x7f8199c670e8)
        /usr/lib/go/src/pkg/net/fd_poll_runtime.go:86 +0x30
net.(*netFD).Read(0xc2100af850, 0xc2100f7000, 0x1000, 0x1000, 0x0, ...)
        /usr/lib/go/src/pkg/net/fd_unix.go:204 +0x2a0
net.(*conn).Read(0xc2100dd470, 0xc2100f7000, 0x1000, 0x1000, 0x0, ...)
        /usr/lib/go/src/pkg/net/net.go:122 +0xc5
github.com/coreos/etcd/third_party/github.com/mreiferson/go-httpclient.(*rwTimeoutConn).Read(0xc2100e1580, 0xc2100f7000, 0x1000, 0x1000, 0x0, ...)
        /opt/etcd/src/github.com/coreos/etcd/third_party/github.com/mreiferson/go-httpclient/httpclient.go:201 +0xea
bufio.(*Reader).fill(0xc2100d9ba0)
        /usr/lib/go/src/pkg/bufio/bufio.go:91 +0x110
bufio.(*Reader).Peek(0xc2100d9ba0, 0x1, 0x0, 0x0, 0x0, ...)
        /usr/lib/go/src/pkg/bufio/bufio.go:119 +0xcb
net/http.(*persistConn).readLoop(0xc210058700)
        /usr/lib/go/src/pkg/net/http/transport.go:687 +0xb7
created by net/http.(*Transport).dialConn
        /usr/lib/go/src/pkg/net/http/transport.go:528 +0x607

goroutine 18 [select]:
net/http.(*persistConn).writeLoop(0xc210058700)
        /usr/lib/go/src/pkg/net/http/transport.go:791 +0x271
created by net/http.(*Transport).dialConn
        /usr/lib/go/src/pkg/net/http/transport.go:529 +0x61e
ubuntu@n1:/opt/etcd$
```

**Comment by tchoulihan** [comment]
I'm having this issue too while trying to rejoin a leader. Using goraft.

**Comment by yichengq** [comment]
@tchoulihan goraft is unmaintained now. We are using https://github.com/coreos/etcd/tree/master/raft . Feel free to give it a try.

**Comment by tchoulihan** [comment]
@yichengq Thanks, I'll try it out.
