### ISSUE TITLE
TestMutexSingleNode: hanging on HardStop

### ISSUE THREAD

**Issue by heyitsanthony** [etcd-io/etcd#7996]
via jenkins: https://jenkins-etcd-public.prod.coreos.systems/job/etcd-proxy/1707/consoleFull

Hangs for about four minutes. Possibly relevant bits from stack trace:
```
goroutine 207170 [chan receive]:
github.com/coreos/etcd/etcdserver.(*EtcdServer).HardStop(0xc426ef2840)
	/home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/etcd/etcdserver/server.go:987 +0x187
github.com/coreos/etcd/integration.(*member).Close(0xc427465d40)
	/home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/etcd/integration/cluster.go:748 +0xe0
github.com/coreos/etcd/integration.(*member).Terminate(0xc427465d40, 0xc4207b4680)
	/home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/etcd/integration/cluster.go:805 +0x1a0
github.com/coreos/etcd/integration.(*cluster).Terminate.func1(0xc42440c900, 0xc4207b4680, 0xc427465d40)
	/home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/etcd/integration/cluster.go:335 +0x6d
created by github.com/coreos/etcd/integration.(*cluster).Terminate
	/home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/etcd/integration/cluster.go:336 +0x11e

goroutine 206548 [chan receive]:
github.com/coreos/etcd/etcdserver.(*EtcdServer).run.func5(0xc426ef2840, 0x18ceb60, 0xc423c137a0)
	/home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/etcd/etcdserver/server.go:707 +0x198
github.com/coreos/etcd/etcdserver.(*EtcdServer).run(0xc426ef2840)
	/home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/etcd/etcdserver/server.go:765 +0xde6
created by github.com/coreos/etcd/etcdserver.(*EtcdServer).start
	/home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/etcd/etcdserver/server.go:556 +0x7e3
```

**Comment by heyitsanthony** [comment]
potentially related lock breakage:
```
=== RUN   TestCtlV3Lock
../bin/etcd-3353: 2017-05-30 14:31:36.171834 W | pkg/flags: unrecognized environment variable ETCD_UNSUPPORTED_ARCH=ppc64le
../bin/etcd-3353: 2017-05-30 14:31:36.171914 I | etcdmain: etcd Version: 3.2.0-rc.1+git
../bin/etcd-3353: 2017-05-30 14:31:36.171945 I | etcdmain: Git SHA: c2893b1
../bin/etcd-3353: 2017-05-30 14:31:36.171960 I | etcdmain: Go Version: go1.8.1
../bin/etcd-3353: 2017-05-30 14:31:36.171999 I | etcdmain: Go OS/Arch: linux/ppc64le
../bin/etcd-3353: 2017-05-30 14:31:36.172019 I | etcdmain: setting maximum number of CPUs to 4, total number of available CPUs is 4
../bin/etcd-3353: 2017-05-30 14:31:36.215075 I | embed: peerTLS: cert = /tmp/testname0.etcd819535051/fixtures/peer/cert.pem, key = /tmp/testname0.etcd819535051/fixtures/peer/key.pem, ca = , trusted-ca = , client-cert-auth = false
../bin/etcd-3353: 2017-05-30 14:31:36.233877 I | embed: listening for peers on https://localhost:20001
../bin/etcd-3353: 2017-05-30 14:31:36.234176 I | embed: listening for client requests on localhost:20000
../bin/etcd-3353: 2017-05-30 14:31:36.260378 I | etcdserver: name = testname0
../bin/etcd-3353: 2017-05-30 14:31:36.260405 I | etcdserver: data dir = /tmp/testname0.etcd819535051
../bin/etcd-3353: 2017-05-30 14:31:36.260427 I | etcdserver: member dir = /tmp/testname0.etcd819535051/member
../bin/etcd-3353: 2017-05-30 14:31:36.260437 I | etcdserver: heartbeat = 100ms
../bin/etcd-3353: 2017-05-30 14:31:36.260456 I | etcdserver: election = 1000ms
../bin/etcd-3353: 2017-05-30 14:31:36.260467 I | etcdserver: snapshot count = 100000
../bin/etcd-3353: 2017-05-30 14:31:36.260483 I | etcdserver: advertise client URLs = http://localhost:20000
../bin/etcd-3353: 2017-05-30 14:31:36.260530 I | etcdserver: initial advertise peer URLs = https://localhost:20001
../bin/etcd-3353: 2017-05-30 14:31:36.260553 I | etcdserver: initial cluster = testname0=https://localhost:20001
../bin/etcd-3353: 2017-05-30 14:31:36.262677 I | etcdserver: starting member a8f3458387986d in cluster 34c21a2d427db393
../bin/etcd-3353: 2017-05-30 14:31:36.262723 I | raft: a8f3458387986d became follower at term 0
../bin/etcd-3353: 2017-05-30 14:31:36.262749 I | raft: newRaft a8f3458387986d [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
../bin/etcd-3353: 2017-05-30 14:31:36.262769 I | raft: a8f3458387986d became follower at term 1
../bin/etcd-3353: 2017-05-30 14:31:36.266792 W | auth: simple token is not cryptographically signed
../bin/etcd-3353: 2017-05-30 14:31:36.308254 I | etcdserver: starting server... [version: 3.2.0-rc.1+git, cluster version: to_be_decided]
../bin/etcd-3353: 2017-05-30 14:31:36.308973 I | etcdserver/membership: added member a8f3458387986d [https://localhost:20001] to cluster 34c21a2d427db393
../bin/etcd-3353: 2017-05-30 14:31:36.463018 I | raft: a8f3458387986d is starting a new election at term 1
../bin/etcd-3353: 2017-05-30 14:31:36.463052 I | raft: a8f3458387986d became candidate at term 2
../bin/etcd-3353: 2017-05-30 14:31:36.463084 I | raft: a8f3458387986d received MsgVoteResp from a8f3458387986d at term 2
../bin/etcd-3353: 2017-05-30 14:31:36.463110 I | raft: a8f3458387986d became leader at term 2
../bin/etcd-3353: 2017-05-30 14:31:36.463130 I | raft: raft.node: a8f3458387986d elected leader a8f3458387986d at term 2
../bin/etcd-3353: 2017-05-30 14:31:36.463486 I | etcdserver: published {Name:testname0 ClientURLs:[http://localhost:20000]} to cluster 34c21a2d427db393
../bin/etcd-3353: 2017-05-30 14:31:36.463604 E | etcdmain: forgot to set Type=notify in systemd service file?
../bin/etcd-3353: 2017-05-30 14:31:36.463658 I | embed: ready to serve client requests
../bin/etcd-3353: 2017-05-30 14:31:36.463739 I | etcdserver: setting up the initial cluster version to 3.2
../bin/etcd-3353: 2017-05-30 14:31:36.463975 N | etcdserver/membership: set the initial cluster version to 3.2
../bin/etcd-3353: 2017-05-30 14:31:36.464064 I | etcdserver/api: enabled capabilities for version 3.2
../bin/etcd-3353: 2017-05-30 14:31:36.465137 N | embed: serving insecure client requests on 127.0.0.1:20000, this is strongly discouraged!
../bin/etcdctl-3363: a/186d5c5aa0a44604
../bin/etcdctl-3363: 
../bin/etcdctl-3373: Error:  context canceled
../bin/etcd-3353: 2017-05-30 14:31:36.684606 I | etcdserver/api/v3rpc: grpc: Server.processUnaryRPC failed to write status: stream error: code = Canceled desc = "context canceled"
--- FAIL: TestCtlV3Lock (1.61s)
	ctl_v3_lock_test.go:121: timed out from waiting to holding
	ctl_v3_lock_test.go:142: expect failed (read /dev/ptmx: input/output error)
```
