### ISSUE TITLE
etcd fails to start possibly due to a bad log

### ISSUE THREAD

**Issue by ibuildthecloud** [etcd-io/etcd#945]
I had a three node etcd cluster and all three nodes filled up on disk space and etcd pretty much hung (as would be expected).  After freeing up disk space and then restarting the three nodes, two of the three failed to start with the below panic.  The full logs and etcd data files are available at https://gist.github.com/ibuildthecloud/8ee312f50b9b6d6816c8.  All three nodes are running CoreOS 410.0.0.

```
panic: runtime error: index out of range
Aug 20 00:59:48 ip-172-31-19-4.us-west-1.compute.internal etcd[4800]: goroutine 21 [running]:
Aug 20 00:59:48 ip-172-31-19-4.us-west-1.compute.internal etcd[4800]: runtime.panic(0x7ebf60, 0xefb097)
Aug 20 00:59:48 ip-172-31-19-4.us-west-1.compute.internal etcd[4800]: /usr/lib/go/src/pkg/runtime/panic.c:266 +0xb6
Aug 20 00:59:48 ip-172-31-19-4.us-west-1.compute.internal etcd[4800]: github.com/coreos/etcd/third_party/github.com/goraft/raft.(*Log).commitInfo(0xc210053850, 0x0, 0x0)
Aug 20 00:59:48 ip-172-31-19-4.us-west-1.compute.internal etcd[4800]: /build/amd64-usr/var/tmp/portage/dev-db/etcd-0.4.6/work/etcd-0.4.6/gopath/src/github.com/coreos/etcd/third_party/github.com/goraft/raft/log.go:301 +0x2ac
Aug 20 00:59:48 ip-172-31-19-4.us-west-1.compute.internal etcd[4800]: github.com/coreos/etcd/third_party/github.com/goraft/raft.(*server).TakeSnapshot(0xc2100586c0, 0x5d0ffd, 0x0)
Aug 20 00:59:48 ip-172-31-19-4.us-west-1.compute.internal etcd[4800]: /build/amd64-usr/var/tmp/portage/dev-db/etcd-0.4.6/work/etcd-0.4.6/gopath/src/github.com/coreos/etcd/third_party/github.com/goraft/raft/server.go:1203 +0x253
Aug 20 00:59:48 ip-172-31-19-4.us-west-1.compute.internal etcd[4800]: github.com/coreos/etcd/server.(*PeerServer).monitorSnapshot(0xc2100a9000)
Aug 20 00:59:48 ip-172-31-19-4.us-west-1.compute.internal etcd[4800]: /build/amd64-usr/var/tmp/portage/dev-db/etcd-0.4.6/work/etcd-0.4.6/gopath/src/github.com/coreos/etcd/server/peer_server.go:785 +0x128
Aug 20 00:59:48 ip-172-31-19-4.us-west-1.compute.internal etcd[4800]: github.com/coreos/etcd/server.*PeerServer.(github.com/coreos/etcd/server.monitorSnapshot)·fm()
Aug 20 00:59:48 ip-172-31-19-4.us-west-1.compute.internal etcd[4800]: /build/amd64-usr/var/tmp/portage/dev-db/etcd-0.4.6/work/etcd-0.4.6/gopath/src/github.com/coreos/etcd/server/peer_server.go:298 +0x26
Aug 20 00:59:48 ip-172-31-19-4.us-west-1.compute.internal etcd[4800]: github.com/coreos/etcd/server.func·002()
Aug 20 00:59:48 ip-172-31-19-4.us-west-1.compute.internal etcd[4800]: /build/amd64-usr/var/tmp/portage/dev-db/etcd-0.4.6/work/etcd-0.4.6/gopath/src/github.com/coreos/etcd/server/peer_server.go:768 +0x5c
Aug 20 00:59:48 ip-172-31-19-4.us-west-1.compute.internal etcd[4800]: created by github.com/coreos/etcd/server.(*PeerServer).startRoutine
Aug 20 00:59:48 ip-172-31-19-4.us-west-1.compute.internal etcd[4800]: /build/amd64-usr/var/tmp/portage/dev-db/etcd-0.4.6/work/etcd-0.4.6/gopath/src/github.com/coreos/etcd/server/peer_server.go:769 +0xb4
```

**Comment by Vish0007** [comment]
Is v0.5 included in some CoreOS version?
How do i recover from this etcd panic state? any workaround (incase I am not able to update to etcd v0.5) ?

**Comment by yichengq** [comment]
@Vish0007 It is not included in CoreOS image now.
As a totally hack way, you can try to edit the log file in data directory, and delete the broken last line.

**Comment by mikap83** [comment]
hello @yichengq ,
I had a similar problem (etcd 0.4.6) and I confirm I could solve it the way you said. 
Thanks a lot!

**Comment by danperetz** [comment]
hello @yichengq ,
Where can I find the log file?

Thanks,
Dan

**Comment by yichengq** [comment]
@danperetz You could check the command line to start etcd to find the log. I recommend that you move to etcd v2.x to avoid further problems.

**Comment by danperetz** [comment]
Thanks for the response.
I had some problems with that solution. Eventually I solved it by running "etcd -f" command, and replacing the old directory with the one that was created (After changing the folder group to etcd:etcd)

Dan
