### ISSUE TITLE
contrib/raftexample: compact error if defaultSnapCount is much less than snapshotCatchUpEntriesN

### ISSUE THREAD

**Issue by yaojingguo** [etcd-io/etcd#9685]
After I set `defaultSnapCount` to `10` and set `snapshotCatchUpEntriesN` to `100`, I used `raftexample --id 1 --cluster http://127.0.0.1:12379 --port 12380` to start a one-node cluster. Then I used the following script to load data to the cluster.

```bash
#!/usr/bin/env bash
for i in `seq 40`; do
  echo $i
  curl -L "http://127.0.0.1:12380/key-$i" -XPUT -d "val-$i"
done
```

Then the terminal for the `raftexample` node reported the following error:

```
2018-05-02 22:39:31.115472 I | replaying WAL of member 1
2018-05-02 22:39:31.240269 I | loading WAL at term 0 and index 0
raft2018/05/02 22:39:31 INFO: 1 became follower at term 0
raft2018/05/02 22:39:31 INFO: newRaft 1 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
raft2018/05/02 22:39:31 INFO: 1 became follower at term 1
raft2018/05/02 22:39:32 INFO: 1 is starting a new election at term 1
raft2018/05/02 22:39:32 INFO: 1 became candidate at term 2
raft2018/05/02 22:39:32 INFO: 1 received MsgVoteResp from 1 at term 2
raft2018/05/02 22:39:32 INFO: 1 became leader at term 2
raft2018/05/02 22:39:32 INFO: raft.node: 1 elected leader 1 at term 2
2018-05-02 22:39:38.273425 I | start snapshot [applied index: 11 | last snapshot index: 0]
2018-05-02 22:39:38.280261 I | compacted log at index 1
2018-05-02 22:39:38.465605 I | start snapshot [applied index: 22 | last snapshot index: 11]
panic: requested index is unavailable due to compaction

goroutine 25 [running]:
main.(*raftNode).maybeTriggerSnapshot(0xc4200c0b40)
	/Users/jing/go/src/github.com/coreos/etcd/contrib/raftexample/raft.go:373 +0x405
main.(*raftNode).serveChannels(0xc4200c0b40)
	/Users/jing/go/src/github.com/coreos/etcd/contrib/raftexample/raft.go:442 +0x548
created by main.(*raftNode).startRaft
	/Users/jing/go/src/github.com/coreos/etcd/contrib/raftexample/raft.go:313 +0x5d3
```
And the script to load data reported the following error:

```
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
curl: (7) Failed to connect to 127.0.0.1 port 12380: Connection refused
23
curl: (7) Failed to connect to 127.0.0.1 port 12380: Connection refused
24
curl: (7) Failed to connect to 127.0.0.1 port 12380: Connection refused
25
curl: (7) Failed to connect to 127.0.0.1 port 12380: Connection refused
26
curl: (7) Failed to connect to 127.0.0.1 port 12380: Connection refused
27
curl: (7) Failed to connect to 127.0.0.1 port 12380: Connection refused
28
curl: (7) Failed to connect to 127.0.0.1 port 12380: Connection refused
29
curl: (7) Failed to connect to 127.0.0.1 port 12380: Connection refused
30
curl: (7) Failed to connect to 127.0.0.1 port 12380: Connection refused
31
curl: (7) Failed to connect to 127.0.0.1 port 12380: Connection refused
32
curl: (7) Failed to connect to 127.0.0.1 port 12380: Connection refused
33
curl: (7) Failed to connect to 127.0.0.1 port 12380: Connection refused
34
curl: (7) Failed to connect to 127.0.0.1 port 12380: Connection refused
35
curl: (7) Failed to connect to 127.0.0.1 port 12380: Connection refused
36
curl: (7) Failed to connect to 127.0.0.1 port 12380: Connection refused
37
curl: (7) Failed to connect to 127.0.0.1 port 12380: Connection refused
38
curl: (7) Failed to connect to 127.0.0.1 port 12380: Connection refused
39
curl: (7) Failed to connect to 127.0.0.1 port 12380: Connection refused
40
curl: (7) Failed to connect to 127.0.0.1 port 12380: Connection refused
```

**Comment by rohansuri** [comment]
Hi @yaojingguo, is this the same issue as #8091 ?

**Comment by yaojingguo** [comment]
No, this is a different from #8091.

**Comment by keekun** [comment]
I tested #8091 in the same way with @yaojingguo 's, with a same small defaultSnapCount and snapshotCatchUpEntriesN at the same time. But there are differences.

The bug in #8091 makes the example get stuck when restarted, but not be panic. I notice the code of raft example has changed a lot recently, so I'm not sure if these bugs related.
