### ISSUE TITLE
distributed dead lock 

### ISSUE THREAD

**Issue by liudechi7** [etcd-io/etcd#9825]
Using a distributed lock, two programs compete to acquire locks, each maintaining the lock's associated lease id's expiration time (keepAliveOnce). When the lock program is terminated, theoretically the expiration time is reached, the lock should be released, and another program acquires the lock, but the actual Failed to get the lock. This problem is not easy to reproduce（The production environment encountered this problem and the offline environment did not reproduce）. The current poor positioning is a service-side issue (etcd version 3.2.18, etcd cluster contains 3 nodes), or a jetcd（version 0.0.2） issue

The core code is as follows（Java implementation, communication via [jetcd](https://github.com/coreos/jetcd) client and etcd）:
`long leaseId = leaseClient.grant(60).get().getID();`
`new Thread(() -> { leaseClient.keepAliveOnce(leaseId); Thread.sleep(1000); });`
`lockClient.lock(ByteSequence.fromString("lock"), leaseId).get().getKey();`

The use scenario mainly guarantees that the program is highly available through the lock, and the program will only release the lock (expiration release) if it terminates abnormally. It is not known whether the occupation of the lock time has an effect on the deadlock. This is one of the reasons why the problem is more difficult to reproduce. Under normal circumstances (occupying lock time for several hours), there is no problem.

**Comment by liudechi7** [comment]
@gyuho 
We reproduced this issue (etcd to open authentication), two programs run for a week, actively kill the program which gets the lock, and another program tries to acquire the lock failed. The following error appears:
Etcd server error：
2018-06-19 18:26:14.254749 W | auth: invalid auth token: hRRXZQIsFGsHuBFM.3313791
Jetcd error:
Caused by: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNKNOWN: etcdserver: invalid auth token
        at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:528) ~[guava-24.1-jre.jar:?]
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:509) ~[guava-24.1-jre.jar:?]
        at com.coreos.jetcd.internal.impl.Util.lambda$toCompletableFutureWithRetry$1(Util.java:125) ~[jetcd-core-0.0.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_171]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_171]
