### ISSUE TITLE
Slice bounds out of range in raft library

### ISSUE THREAD

**Issue by manishrjain** [etcd-io/etcd#9847]
Please read https://github.com/coreos/etcd/blob/master/Documentation/reporting_bugs.md.

Version:
```
			"checksumSHA1": "h1nLibY0IliypSG0cwbXpSpcsMA=",
			"path": "github.com/coreos/etcd/raft",
			"revision": "9d43462d174c664f5edf313dec0de31e1ef4ed47",
			"revisionTime": "2017-08-21T17:40:55Z",
			"version": "v3.2.6",
			"versionExact": "v3.2.6"
```

```
2018/06/13 16:10:01 raft.go:567: INFO: 7 became follower at term 0
2018/06/13 16:10:01 raft.go:315: INFO: newRaft 7 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2018/06/13 16:10:01 raft.go:567: INFO: 7 became follower at term 1
2018/06/13 16:10:01 raft.go:708: INFO: 7 [term: 1] received a MsgHeartbeat message with higher term from 3 [term: 21]
2018/06/13 16:10:01 raft.go:567: INFO: 7 became follower at term 21
2018/06/13 16:10:01 node.go:301: INFO: raft.node: 7 elected leader 3 at term 21
panic: runtime error: slice bounds out of range

goroutine 1835811 [running]:
github.com/dgraph-io/dgraph/vendor/github.com/coreos/etcd/raft.(*raftLog).maybeAppend(0xc4201a93b0, 0x0, 0x0, 0xc92, 0xc434d70000, 0x7, 0x8, 0x0, 0x0)
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/vendor/github.com/coreos/etcd/raft/log.go:86 +0x280
github.com/dgraph-io/dgraph/vendor/github.com/coreos/etcd/raft.(*raft).handleAppendEntries(0xc4201d2a50, 0x3, 0x7, 0x3, 0x15, 0x0, 0x0, 0xc434d70000, 0x7, 0x8, ...)
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/vendor/github.com/coreos/etcd/raft/raft.go:1090 +0xaa
github.com/dgraph-io/dgraph/vendor/github.com/coreos/etcd/raft.stepFollower(0xc4201d2a50, 0x3, 0x7, 0x3, 0x15, 0x0, 0x0, 0xc434d70000, 0x7, 0x8, ...)
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/vendor/github.com/coreos/etcd/raft/raft.go:1042 +0x22c
github.com/dgraph-io/dgraph/vendor/github.com/coreos/etcd/raft.(*raft).Step(0xc4201d2a50, 0x3, 0x7, 0x3, 0x15, 0x0, 0x0, 0xc434d70000, 0x7, 0x8, ...)
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/vendor/github.com/coreos/etcd/raft/raft.go:778 +0xf3d
github.com/dgraph-io/dgraph/vendor/github.com/coreos/etcd/raft.(*node).run(0xc42d3637a0, 0xc4201d2a50)
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/vendor/github.com/coreos/etcd/raft/node.go:323 +0xfe5
created by github.com/dgraph-io/dgraph/vendor/github.com/coreos/etcd/raft.StartNode
	/home/mrjn/go/src/github.com/dgraph-io/dgraph/vendor/github.com/coreos/etcd/raft/node.go:210 +0x618

```

**Comment by gyuho** [comment]
Could you provide a simple test case?

**Comment by manishrjain** [comment]
For whatever reason, this is happening repeatedly. I've never seen this before though.

**Comment by joelegasse** [comment]
@manishrjain If you could provide some simple steps, even if it's just "start dgraph like this", we would really appreciate it. Even some more context, like if this is a brand new dgraph node or a longer-running node? Does this happen all the time on every dgraph instance or did this get triggered on a single node, and just that node is panicking repeatedly?

**Comment by manishrjain** [comment]
It happened on one node, and then just repeatedly happened for that node. It was a brand new dgraph node.

**Comment by manishrjain** [comment]
Hey guys, we're again able to see this issue. What can I provide you to help debug this?
